# -*- coding: utf-8 -*-
"""The summaries of III. HA MdA, III. Nr. 12366, written in the working session.

    python units/iiihamdaiiinr12366/intake/summaries_draft.py

Each document was read whole against its scan on 2026-10-04 and summarised in
German; the English is a translation of the German. Neither went through the
paid claim check (read_letters.py --verify), and the English was not made by
summarise.py: this script writes the records those tools would have written
(units/<slug>/summaries_de.yml, cache/summaries-raw-de/, cache/summaries-raw/),
so that `summarise.py --build` publishes them.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UNIT_DIR = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(UNIT_DIR))
SLUG = 'iiihamdaiiinr12366'
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

S = {
 1: ("Der russische Gesandte in Berlin, Alopeus, übersendet dem preußischen Außenminister Graf Bernstorff auf Befehl seines Hofes einen beiliegenden Bericht des Statthalters des Königreichs Polen über eine Forderung, die Gräfin Michalina Miączyńska, geborene Prusimska, gegen die preußische Regierung erhebt, und unterstützt sie. Der Bericht enthalte so schlüssige Gründe, dass er nichts hinzuzufügen wisse. Er bittet Bernstorff, die Sache der Gräfin den Behörden zu empfehlen, die darüber zu entscheiden haben.",
     "The Russian envoy at Berlin, Alopeus, sends the Prussian foreign minister Count Bernstorff, on the orders of his court, an enclosed report of the Viceroy of the Kingdom of Poland on a claim that Countess Michalina Miączyńska, born Prusimska, makes against the Prussian government, and supports it. The report, he writes, contains arguments so conclusive that he has nothing to add. He asks Bernstorff to recommend the Countess's case to the authorities who will have to decide it."),
 2: ("Abschrift eines Berichts aus Warschau über die Forderung der Gräfin Michalina Miączyńska, geborene Prusimska, wie die bevollmächtigten Kommissare für die Liquidation des ehemaligen Herzogtums Warschau sie dargelegt haben. Ihre Erbgüter wurden 1796 ihrem Vater, dem Starosten Prusimski, von der preußischen Regierung konfisziert und an Fürst Hohenlohe-Ingelfingen und General Sanitz vergeben; ein Beschluss der Regierungskommission des Herzogtums vom 21. Juli 1807 setzte sie wieder in den Besitz ein. Sie verlangt, dass die Schulden, die die Beschenkten auf die Güter aufgenommen haben, zu Lasten Preußens gehen: Der Fürst habe Trąbczyn und Szetlewek mit 156.000 Talern belastet, und auf Kolno und Kamionna, die er für 142.000 Taler an den Bankkassierer Leixner verkaufte, lägen 160.000 Taler. Der Bericht führt an, dass sie als minderjährige Waise Anspruch auf den Schutz der preußischen Regierung hatte, dass Niemojewski und Wichrowski ihre Güter schuldenfrei zurückerhielten und dass Preußen die Generale Sanitz und Zastrow für die zurückgegebenen Güter mit anderen entschädigte. Ebenso könne es den Fürsten entschädigen, indem es dessen Schulden übernimmt. Ein Leser im preußischen Ministerium hat mit Bleistift Einwände an den Rand geschrieben: Preußen sei für Regierungsakte im ehemaligen Südpreußen niemandem verantwortlich, nicht einmal Napoleon habe einen Anspruch wegen des in der Zwischenzeit Geschehenen zugestanden, und der Fürst habe die Güter, solange er sie besaß, rechtmäßig und mit vollem Eigentumsrecht besessen.",
     "Copy of a report from Warsaw on the claim of Countess Michalina Miączyńska, born Prusimska, as the commissioners for the liquidation of the former Duchy of Warsaw set it out. Her hereditary estates were confiscated from her father, the Starost Prusimski, by the Prussian government in 1796 and given to Prince Hohenlohe-Ingelfingen and General Sanitz; a decision of the Duchy's governing commission of 21 July 1807 put her back in possession. She asks that the debts the donees raised on the estates be charged to Prussia: the Prince, the report says, loaded Trąbczyn and Szetlewek with 156,000 thalers, and Kolno and Kamionna, which he sold to the bank cashier Leixner for 142,000 thalers, carry 160,000 thalers. The report argues that as an orphan under age she was entitled to the protection of the Prussian government, that Niemojewski and Wichrowski recovered their estates free of debt, and that Prussia compensated Generals Sanitz and Zastrow with other estates for those returned. It could compensate the Prince in the same way, by taking over his debts. A reader in the Prussian ministry wrote objections in the margin in pencil: Prussia is answerable to no one for acts of government in the former South Prussia, not even Napoleon granted a claim for what was done in the years between, and the Prince, for as long as he possessed the estates, possessed them lawfully and with full right of ownership."),
 3: ("Entwurf der Antwort des preußischen Außenministers an den russischen Gesandten Alopeus auf dessen Note und die Denkschrift über die Forderungen der Gräfin Miączyńska. Der Starost Prusimski habe am Aufstand der Polen teilgenommen und sei geflohen; seine Güter wurden durch gerichtliches Urteil konfisziert, der König verfügte darüber, und die Beschenkten nahmen Hypotheken darauf auf. Prusimski starb 1803 im Ausland, und seine Tochter erhielt die Güter nach dem Frieden von Tilsit von der Regierung des Herzogtums Warschau zurück. Sie verlangt nun, dass die Schulden getilgt werden, die auf den Gütern ruhen. Die preußische Regierung hat das Gesuch schon einmal abgelehnt; nach erneuter Prüfung bleibt es bei der Entscheidung der preußischen Gerichte, deren Gründe eine beigefügte Denkschrift darlegt.",
     "Draft of the Prussian foreign minister's reply to the Russian envoy Alopeus, answering his note and the memorandum on the claims of Countess Miączyńska. The Starost Prusimski, it says, took part in the Polish uprising and fled; his estates were confiscated by a court's judgment, the King disposed of them, and the donees raised mortgages on them. Prusimski died abroad in 1803, and after the Peace of Tilsit his daughter received the estates back from the government of the Duchy of Warsaw. She now asks that the debts resting on the estates be paid off. The Prussian government has refused the request once already; after a fresh examination the decision of the Prussian courts stands, and an enclosed memorandum sets out its reasons."),
 4: ("Abschrift eines Schreibens des Advokaten Tarczewski aus Warschau an einen nicht genannten Mandanten: Mitschke in Kalisz hat ihm die Akten des Prozesses gegen Frau Miączyńska geschickt. Sie sind in Ordnung; es fehlen nur die Hypothekenscheine über die eingeklagte Summe, die im Original oder in beglaubigter Abschrift vorzulegen sind. Die Gegenseite betreibt die Einführung der Sache vor dem Appellationsgericht. Er zieht die Instruktion hin, doch wenn alle Fristen erschöpft sind, muss die Sache zur Entscheidung gestellt werden.",
     "Copy of a letter from the advocate Tarczewski at Warsaw to a client who is not named: Mitschke at Kalisz has sent him the files of the suit against Madame Miączyńska. They are in order; only the mortgage certificates for the sum claimed are missing, and these must be produced in the original or in certified copies. The other side is pressing to bring the case before the court of appeal. He is drawing out the preparation of the case, but once all the time limits are used up it will have to go to judgment."),
 5: ("Abschrift einer Note des preußischen Gesandten in St. Petersburg, General von Schöler, an den russischen Außenminister Graf Nesselrode. Fürst Hohenlohe-Ingelfingen, dem König Friedrich Wilhelm II. am 9. August 1796 die konfiszierte Herrschaft Trąbczyn geschenkt hatte, nahm bei Grotowski 30.000 Taler auf; die Hypothek wurde gerichtlich an den Breslauer Kaufmann Weigel abgetreten. 1807 gab die Regierungskommission des Herzogtums Warschau die Güter an Prusimskis Tochter Michalina zurück, die jetzige Gräfin Miączyńska; die eingetragenen Forderungen blieben bestehen. Als die Zinsen ausblieben, klagte Weigel; das Ziviltribunal in Kalisz wies ihn am 6. März 1819 ab und ließ die Forderung löschen. Preußen verlangte 1819 und 1820 ohne Antwort, die Frage der diplomatischen Verhandlung vorzubehalten; inzwischen hat das Appellationsgericht das Urteil verworfen, das Obertribunal in Warschau es aber am 17. Juli 1826 bestätigt. Schöler beruft sich auf den Frieden von Tilsit und auf die Konventionen von 1815 und 1819, die Hypothekenforderungen aufrechterhalten, und bittet, das Urteil aufheben und seine Vollstreckung zunächst aussetzen zu lassen.",
     "Copy of a note from the Prussian envoy at St Petersburg, General von Schöler, to the Russian foreign minister Count Nesselrode. Prince Hohenlohe-Ingelfingen, to whom King Friedrich Wilhelm II gave the confiscated lordship of Trąbczyn on 9 August 1796, borrowed 30,000 thalers from Grotowski; the mortgage was assigned through the court to the Breslau merchant Weigel. In 1807 the governing commission of the Duchy of Warsaw returned the estates to Prusimski's daughter Michalina, now Countess Miączyńska; the registered claims remained. When the interest went unpaid Weigel sued; the civil tribunal at Kalisz dismissed his suit on 6 March 1819 and ordered the claim struck out. Prussia asked in 1819 and 1820, without an answer, that the question be kept for diplomatic negotiation; meanwhile the court of appeal set the judgment aside, but the high tribunal at Warsaw confirmed it on 17 July 1826. Schöler relies on the Peace of Tilsit and on the conventions of 1815 and 1819, which uphold mortgage claims, and asks that the judgment be annulled and, first of all, that its execution be suspended."),
 6: ("Beglaubigter Auszug eines Urteils des Ziviltribunals erster Instanz der Woiwodschaft Kalisz vom 30. Juli 1827, in polnischer Sprache. Klägerin ist Michalina Miączyńska, geborene Prusimska, mit ihrem Mann Graf Stanisław Miączyński, Erbherrin von Trąbczyn; Beklagte sind die Brüder Lichnowski als Erben des Karl Heinrich Lichnowski und Maria Anna, geborene Blacha, die Witwe des Franciszek Grotowski. Das Gericht weist zwei Einreden gegen die Ladung zurück und erwägt: Trąbczyn und Szetlewek gehörten Antoni Prusimski, wurden ihm wegen seiner Teilnahme am Aufstand konfisziert und dem Fürsten Hohenlohe-Ingelfingen geschenkt; die Regierungskommission gab sie der Klägerin zurück. Der Fürst sei nur bedingter Besitzer gewesen, mit seinem Titel seien auch die von ihm aufgenommenen Schulden erloschen, und der Vertrag von Tilsit ändere daran nichts; gegen Weigel habe die Klägerin in gleicher Sache bereits endgültige Urteile erlangt. Es lässt die Forderung der Brüder Lichnowski und die der Witwe Grotowski aus dem Hypothekenbuch von Trąbczyn und Szetlewek löschen und legt den Beklagten die Kosten auf.",
     "Certified extract of a judgment of the civil tribunal of first instance of the Kalisz voivodeship, of 30 July 1827, in Polish. The plaintiff is Michalina Miączyńska, born Prusimska, with her husband Count Stanisław Miączyński, hereditary owner of Trąbczyn; the defendants are the Lichnowski brothers, as heirs of Karl Heinrich Lichnowski, and Maria Anna, born Blacha, the widow of Franciszek Grotowski. The court rejects two objections to the summons and reasons as follows: Trąbczyn and Szetlewek belonged to Antoni Prusimski, were confiscated from him for his part in the uprising and given to Prince Hohenlohe-Ingelfingen; the governing commission returned them to the plaintiff. The Prince, it holds, was only a conditional possessor, the debts he raised lapsed with his title, and the Treaty of Tilsit does not change this; against Weigel the plaintiff has already won final judgments in the same matter. It orders the claim of the Lichnowski brothers and that of Grotowski's widow struck out of the mortgage register of Trąbczyn and Szetlewek and awards costs against the defendants."),
}


def main():
    with open(os.path.join(UNIT_DIR, 'summaries_de.yml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('# German summaries of III. HA MdA, III. Nr. 12366, written in the working session from a\n'
                '# reading of each document against its scan (intake/summaries_draft.py, 2026-10-04).\n'
                '# Not yet checked by the separate claim check (read_letters.py --verify).\n'
                '# A finding aid, not part of the edition text. Published through\n'
                '# summarise.py --build --lang de.\n')
        for n, (de, _en) in sorted(S.items()):
            f.write(f'{SLUG}-{n:03d}: {json.dumps(de, ensure_ascii=False)}\n')
    for lang, sub, i in (('de', 'summaries-raw-de', 0), ('en', 'summaries-raw', 1)):
        d = os.path.join(ROOT, 'cache', sub)
        os.makedirs(d, exist_ok=True)
        for n, pair in S.items():
            pad = f'{SLUG}-{n:03d}'
            json.dump({'letter': str(n), 'pad': pad, 'summary': pair[i],
                       'model': 'in-session, 2026-10-04; not claim-checked',
                       'usage': {'input': 0, 'output': 0, 'cache_read': 0}},
                      open(os.path.join(d, pad + '.json'), 'w', encoding='utf-8'),
                      ensure_ascii=False, indent=1)
    print(len(S), 'summaries written, German and English')


if __name__ == '__main__':
    main()
