# -*- coding: utf-8 -*-
"""The summaries of I. HA GR, Rep. 7 C, Nr. 3709, written in the working session.

    python units/ihagrrep7cnr3709/intake/summaries_draft.py

Each document was read whole against its scan on 2026-10-04 and summarised in
German; the English is a translation of the German. Neither went through the
paid claim check (read_letters.py --verify), and the English was not made by
summarise.py: this script writes the records those tools would have written
(units/<slug>/summaries_de.yml, cache/summaries-raw-de/, cache/summaries-raw/),
so that `summarise.py --build` publishes them. Run the build for both languages
afterwards.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UNIT_DIR = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(UNIT_DIR))
SLUG = 'ihagrrep7cnr3709'
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

S = {
 1: ("Die Regierung zu Posen überreicht dem König eine Abschrift der Kabinettsordre, die in der Sache Prusimska gegen den Fürsten von Hohenlohe an sie ergangen ist. Die empfangende Behörde legt den Bericht am 23. Juni 1800 zu den Akten.",
     "The Government at Poznań submits to the King a copy of the cabinet order issued to it in the case of Prusimska against the Prince of Hohenlohe. The receiving office files the report on 23 June 1800."),
 2: ("Abschrift einer Kabinettsordre des Königs an die Regierung zu Posen, dort eingegangen am 16. Juni 1800: Durch eine beiliegende Beschwerde der von Prusimska veranlasst, fordert der König die Akten ihrer Sache gegen den Fürsten von Hohenlohe-Ingelfingen wegen des mütterlichen Vermögens der Bittstellerin ein, so wie sie liegen, und befiehlt, sie sofort einzusenden.",
     "Copy of a cabinet order of the King to the Government at Poznań, received there on 16 June 1800: prompted by an enclosed complaint of von Prusimska, the King calls in the files of her case against the Prince of Hohenlohe-Ingelfingen over the petitioner's maternal property, as they stand, and orders them sent in at once."),
 3: ("Die Regierung zu Posen überreicht dem König eine Abschrift der Kabinettsordre vom 1. Juli, eingegangen am 7. Juli, unter Bezug auf ihren Bericht vom 18. des Vormonats. Sie bemerkt, dass der Termin zur Beweisaufnahme und zum Schlussverfahren in der Sache der Michalina von Prusimska gegen den Fürsten zu Hohenlohe-Ingelfingen auf den 22. Juli ansteht. Die empfangende Behörde legt den Bericht am 1. August 1800 in Berlin zu den Akten.",
     "The Government at Poznań submits to the King a copy of the cabinet order of 1 July, received on 7 July, with reference to its report of the 18th of the previous month. It notes that the hearing for taking evidence and closing the proceedings in the case of Michalina von Prusimska against the Prince of Hohenlohe-Ingelfingen is set for 22 July. The receiving office files the report in Berlin on 1 August 1800."),
 4: ("Abschrift einer Kabinettsordre des Königs an die Regierung zu Posen: Er sendet die mit dem Bericht vom 18. des Vormonats eingesandten Akten der Sache Prusimska gegen den Fürsten zu Hohenlohe-Ingelfingen zurück. Die Regierung soll die Instruktion, die durch zu viel Nachsicht gegen den Bevollmächtigten des Beklagten sehr verzögert worden sei, mit allem Fleiß beenden und dann angemessene Vergleichsvorschläge machen lassen. Kommt der Vergleich nicht zustande, soll sie für ein rasches Urteil sorgen, besonders falls nach den Gesetzen nochmals in erster Instanz erkannt werden müsste.",
     "Copy of a cabinet order of the King to the Government at Poznań: he returns the files of the case of Prusimska against the Prince of Hohenlohe-Ingelfingen that were sent in with the report of the 18th of the previous month. The Government is to finish preparing the case, which has been much delayed by too much indulgence towards the defendant's agent, with all diligence, and then to have suitable proposals for a settlement made. If no settlement is reached, it is to see to a speedy judgment, especially if the laws should require judgment to be given once more in the first instance."),
 5: ("Der Fürst von Hohenlohe schreibt dem Großkanzler: Die minderjährige Michalina von Prusimska hat bei der Regierung zu Posen gegen ihn auf Herausgabe der ihm vom König geschenkten Brzycer Güter geklagt; die Sache soll nun zum Spruch vorgelegt werden. Da das Pupillenkollegium zu Posen den Prozess im Namen der Klägerin betreibt und seine Mitglieder zugleich Mitglieder der Regierung sind, also seine Richter wären, bittet er, das Urteil der Regierung zu Kalisch zu übertragen und ihr die Akten zuzuschicken. Das Schreiben ging am 2. Dezember 1800 ein.",
     "The Prince of Hohenlohe writes to the Grand Chancellor: the minor Michalina von Prusimska has sued him before the Government at Poznań for the recovery of the Brzyce estates, which the King gave him; the case is now to be laid before the court for judgment. Since the guardianship board at Poznań conducts the suit in the plaintiff's name and its members are also members of the Government, and so would be his judges, he asks that the judgment be entrusted to the Government at Kalisz and the files sent there. The letter came in on 2 December 1800."),
 6: ("Begleitschreiben des Fürsten von Hohenlohe an den Großkanzler zu seinem Bittschreiben vom selben Tag. Der Vergleichsvorschlag, den der Deputierte im letzten Termin gemacht hat, lasse ihn fürchten, dass die Regierung zu Posen nicht unbefangen urteilen werde. Das Lebtagsrecht des noch lebenden Vaters der Klägerin am Vermögen seiner verstorbenen Frau sei ein Teil des ihm konfiszierten Vermögens; der Deputierte habe dennoch bezweifelt, dass es dem Fiskus zustehe. Der Fürst bittet nochmals dringend, den Spruch der Regierung zu Kalisch oder einem anderen südpreußischen Kollegium aufzutragen.",
     "The Prince of Hohenlohe's covering letter to the Grand Chancellor, sent with his petition of the same day. The settlement proposal made by the court's deputy at the last hearing makes him fear that the Government at Poznań will not judge impartially. The lifetime right of the plaintiff's father, who is still living, in his late wife's property is, he says, part of the father's confiscated property; the deputy nevertheless doubted that it belongs to the fisc. The Prince asks again, urgently, that the judgment be entrusted to the Government at Kalisz or to another South Prussian court."),
 7: ("Verfügung von Amts wegen: Da die meisten Räte der Regierung zu Posen Mitglieder des dortigen Vormundschaftskollegiums sind, das die Klage des Vormunds der minderjährigen Michalina von Prusimska gegen den Fürsten von Hohenlohe-Ingelfingen auf Herausgabe der Brzycer Güter veranlasst hat und den Prozess leitet, soll die Sache in erster Instanz vom Plenum der Regierung zu Warschau und in zweiter Instanz vom Oberappellationssenat des Kammergerichts entschieden werden. Dies ist der Regierung zu Posen mitzuteilen; Reskripte ergehen auch an die Regierung zu Warschau und an den Senat.",
     "A decree made of the office's own motion: since most councillors of the Government at Poznań are members of the guardianship board there, which occasioned the suit of the guardian of the minor Michalina von Prusimska against the Prince of Hohenlohe-Ingelfingen for the recovery of the Brzyce estates and directs it, the case is to be decided in the first instance by the full bench of the Government at Warsaw and in the second by the Senate of Higher Appeal of the Kammergericht. The Government at Poznań is to be told; rescripts go also to the Government at Warsaw and to the Senate."),
 8: ("Entwurf eines königlichen Reskripts an die Regierung zu Posen: Da die meisten ihrer Räte Mitglieder des dortigen Vormundschaftskollegiums sind, das die Klage des Vormunds der Michalina von Prusimska gegen den Fürsten von Hohenlohe-Ingelfingen auf Herausgabe der Brzycer Güter veranlasst hat und leitet, wird festgesetzt, dass die Sache in erster Instanz vom Plenum der Regierung zu Warschau und in zweiter vom Oberappellationssenat des Kammergerichts entschieden wird. Beide Kollegien sind am selben Tag angewiesen worden.",
     "Draft of a royal rescript to the Government at Poznań: since most of its councillors are members of the guardianship board there, which occasioned and directs the suit of Michalina von Prusimska's guardian against the Prince of Hohenlohe-Ingelfingen for the recovery of the Brzyce estates, it is laid down that the case will be decided in the first instance by the full bench of the Government at Warsaw and in the second by the Senate of Higher Appeal of the Kammergericht. Both courts have been instructed the same day."),
 9: ("Entwurf eines königlichen Reskripts an die Regierung zu Warschau: Bei der Posener Regierung schwebt zwischen dem Vormund der minderjährigen Michalina von Prusimska und dem Fürsten von Hohenlohe-Ingelfingen ein Prozess auf Herausgabe der Brzycer Güter. Da das dortige Pupillenkollegium die Klage veranlasst hat und leitet und die meisten Posener Räte ihm angehören, soll die Sache in erster Instanz vom Plenum der Regierung zu Warschau entschieden werden. Die Regierung zu Posen ist benachrichtigt. Die Reskripte gingen am 13. zur Post.",
     "Draft of a royal rescript to the Government at Warsaw: a suit for the recovery of the Brzyce estates is pending before the Government at Poznań between the guardian of the minor Michalina von Prusimska and the Prince of Hohenlohe-Ingelfingen. Since the guardianship board there occasioned and directs the suit and most of the Poznań councillors belong to it, the case is to be decided in the first instance by the full bench of the Government at Warsaw. The Government at Poznań has been informed. The rescripts went to the post on the 13th."),
 10: ("Entwurf eines königlichen Reskripts an den Oberappellationssenat des Kammergerichts: Zwischen der minderjährigen Michalina von Prusimska und dem Fürsten von Hohenlohe-Ingelfingen schwebt bei der Posener Regierung ein Prozess auf Herausgabe der Brzycer Güter. Da das Posener Vormundschaftskollegium die Klage veranlasst hat und leitet und die meisten Posener Räte ihm angehören, soll die Sache in erster Instanz vom Plenum der Regierung zu Warschau und in zweiter Instanz vom Senat entschieden werden. Die Regierungen in Posen und Warschau sind angewiesen.",
      "Draft of a royal rescript to the Senate of Higher Appeal of the Kammergericht: a suit for the recovery of the Brzyce estates is pending before the Government at Poznań between the minor Michalina von Prusimska and the Prince of Hohenlohe-Ingelfingen. Since the Poznań guardianship board occasioned and directs the suit and most of the Poznań councillors belong to it, the case is to be decided in the first instance by the full bench of the Government at Warsaw and in the second by the Senate. The Governments at Poznań and Warsaw have been instructed."),
 11: ("Entwurf einer Antwort an den Fürsten von Hohenlohe: Sein Wunsch, dass seine Sache mit dem Vormund der Michalina von Prusimska nicht von der Regierung zu Posen entschieden werde, sei schon dadurch begründet, dass die meisten dortigen Räte dem Vormundschaftskollegium angehören, das den Rechtsstreit veranlasst hat. Der Schreiber hat deshalb verfügt, dass in erster Instanz das Plenum der Regierung zu Warschau und in zweiter der Appellationssenat des Kammergerichts entscheidet. Warschau statt Kalisch habe er gewählt, weil der Posener Präsident Graf von Danckelmann kürzlich zur Regierung in Kalisch übergegangen ist.",
      "Draft of a reply to the Prince of Hohenlohe: his wish that his case with Michalina von Prusimska's guardian should not be decided by the Government at Poznań is well founded by the one fact that most of the councillors there belong to the guardianship board that occasioned the lawsuit. The writer has therefore ordered that the full bench of the Government at Warsaw decide in the first instance and the Senate of Appeal of the Kammergericht in the second. He chose Warsaw and not Kalisz because the president at Poznań, Count von Danckelmann, has lately moved to the Government at Kalisz."),
 12: ("Die Regierung zu Posen berichtet auf das Reskript vom 7., eingegangen am 16. Dezember: In der Sache des Vormunds der Michalina von Prusimska gegen den Fürsten von Hohenlohe-Ingelfingen ist bereits am 9. Dezember in erster Instanz erkannt worden, weil die Kabinettsordre vom 1. Juli die Beschleunigung besonders empfohlen hatte. Wird ein Rechtsmittel eingelegt, will sie die Akten an den Oberappellationssenat des Kammergerichts zur Entscheidung in zweiter Instanz einsenden. Die empfangende Behörde verfügt am 31. Dezember 1800, der Regierung zu Warschau mitzuteilen, dass das Reskript vom 7. Dezember keine Anwendung finde.",
      "The Government at Poznań reports on the rescript of the 7th, received on 16 December: in the case of Michalina von Prusimska's guardian against the Prince of Hohenlohe-Ingelfingen, judgment in the first instance was already given on 9 December, because the cabinet order of 1 July had especially urged speed. If an appeal is lodged, it will send the files to the Senate of Higher Appeal of the Kammergericht for decision in the second instance. The receiving office decrees on 31 December 1800 that the Government at Warsaw be told the rescript of 7 December does not apply."),
 13: ("Entwurf eines königlichen Reskripts an die Regierung zu Warschau: Ihr war durch das Reskript vom 7. Dezember das Urteil erster Instanz im Prozess zwischen dem Vormund der Michalina von Prusimska und dem Fürsten von Hohenlohe-Ingelfingen wegen der Brzycer Güter aufgetragen worden. Die Posener Regierung hat aber angezeigt, dass sie das Urteil bereits am 9. gefällt hat, also vor Eingang der Verfügung; das Reskript findet daher keine Anwendung. Zur Post gegeben am 5. Januar 1801.",
      "Draft of a royal rescript to the Government at Warsaw: by the rescript of 7 December it had been charged with the judgment in the first instance in the suit between Michalina von Prusimska's guardian and the Prince of Hohenlohe-Ingelfingen over the Brzyce estates. The Government at Poznań has reported, however, that it gave judgment on the 9th, before the order reached it; the rescript therefore does not apply. Sent to the post on 5 January 1801."),
 14: ("Entwurf eines Schreibens an den Fürsten von Hohenlohe, stark korrigiert und schlecht lesbar: Die Regierung zu Posen hat seine Sache gegen Michalina von Prusimska infolge der Kabinettsordre vom 1. Juli, die ihr den schnellen Betrieb empfahl, so beschleunigt, dass bereits erkannt war, als die Verfügung vom 7. Dezember dort einging. Es bleibt bei der Verfügung, dass die Akten zum Spruch in zweiter Instanz an den Oberappellationssenat des Kammergerichts eingeschickt werden.",
      "Draft of a letter to the Prince of Hohenlohe, heavily corrected and hard to read: the Government at Poznań, following the cabinet order of 1 July that urged it to move the case quickly, so hastened his case against Michalina von Prusimska that judgment had already been given when the order of 7 December arrived there. The order stands that the files are to be sent to the Senate of Higher Appeal of the Kammergericht for judgment in the second instance."),
 15: ("Michalina Prusimska bittet den König auf Französisch um Beschleunigung: Vor achtzehn Monaten habe sie ihm in Posen eine Denkschrift überreicht und um das Vermögen gebeten, das ihr nach dem Tod ihrer Mutter zustehe; er habe versprochen, die Justiz zu beschleunigen. Nach vier Jahren sei der in Posen begonnene Prozess erst in erster Instanz entschieden, und die Entscheidung sei nun an den Gerichtshof in Berlin gegangen. Als verlassene Waise klage sie gegen den Fürsten von Hohenlohe. Das Kabinett gibt die Bitte am 26. Januar 1802 an Minister von der Reck; er lässt ihr am 29. Januar mitteilen, sie habe die Publikation des Appellationsurteils zu erwarten.",
      "Michalina Prusimska asks the King, in French, to hasten her case: eighteen months ago she handed him a memorandum at Poznań asking for the fortune due to her after her mother's death, and he promised to speed justice. After four years the suit begun at Poznań has been decided only in the first instance, and the decision has now gone to the court in Berlin. She is, she writes, an abandoned orphan pleading against the Prince of Hohenlohe. The Cabinet passes the petition to Minister von der Reck on 26 January 1802; on 29 January he has her told that she may expect the appeal judgment to be published."),
}


def main():
    with open(os.path.join(UNIT_DIR, 'summaries_de.yml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('# German summaries of I. HA GR, Rep. 7 C, Nr. 3709, written in the working session from a\n'
                '# reading of each document against its scan (intake/summaries_draft.py, 2026-10-04).\n'
                '# Not yet checked by the separate claim check (read_letters.py --verify).\n'
                '# A finding aid, not part of the edition text. Published through\n'
                '# summarise.py --build --lang de.\n')
        for n, (de, _en) in sorted(S.items()):
            f.write(f'{SLUG}-{n:03d}: {json.dumps(de, ensure_ascii=False)}\n')
    for lang, sub, i in (('de', 'summaries-raw-de', 0), ('en', 'summaries-raw', 1)):
        d = os.path.join(ROOT, 'cache', sub)
        os.makedirs(d, exist_ok=True)
        for n, pair in S.items():
            pad = f'{SLUG}-{n:03d}'
            json.dump({'letter': str(n), 'pad': pad, 'summary': pair[i],
                       'model': 'in-session, 2026-10-04; not claim-checked',
                       'usage': {'input': 0, 'output': 0, 'cache_read': 0}},
                      open(os.path.join(d, pad + '.json'), 'w', encoding='utf-8'),
                      ensure_ascii=False, indent=1)
    print(len(S), 'summaries written, German and English')


if __name__ == '__main__':
    main()
