# -*- coding: utf-8 -*-
"""What the full check of APP 53/17/0/-/Konin Gr.145 against the scans found.

The editor asked (2026-10-06) for every page to be read for dropped phrases,
and for each to be listed with a word on whether it matters to the meaning.
One entry per finding, in page order:

    page    the page id (leaf N recto is <N>_a2, leaf N verso is <N+1>_a1)
    kind    'dropped'  words on the scan that the transcription lacks
            'misread'  a reading that changes the sense (small slips of spelling are not collected)
    old     the transcription as it stood; must stand exactly once on the page
    new     the same with the scan's words put in, in the modern spelling of the rest
    scan    the words as the scan has them
    en_old, en_new   the English before and after, where it has to follow ('' where it need not)
    weight  'court'    changes what the court found or ordered
            'fact'     adds or changes a place, person, measure, date or party
            'formula'  wording only
    note    anything else

Which pages have been read is in full_check_pages.txt (full_check_note.py).
The rows are applied by corrections_full.py when the check is finished.
"""

ROWS = [
    dict(page='0655_a2', kind='misread', weight='formula',
         old='obtulit officium prosequenti ad actandum et in acta prosequenti ingrossandum porrexit Decretum Commissoriale graniciale imprimis Haereditates eodem decreto specificatas pro illustris magnificos commissarios prolaturus sigillisque Gentilicis communitum sanum salvum ex illesum',
         new='obtulit officio praesenti ad acticandum et in acta praesentia ingrossandum porrexit Decretum Commissoriale graniciale inter Haereditates eodem decreto specificatas per illustres magnificos commissarios prolatum sigillisque Gentilitiis communitum sanum salvum et illesum',
         scan='obtulit Offo pnti ad acticand et in Acta pntia ingrossand porrexit Decrum Comissoriale graniciale inr Hareditates Eod Decro specificatas p Illres Mgcos Commissarios prolatum sigillisq Gentilicus communitum sanum salvum et illesum',
         en_old="presented to the office for prosecution, and submitted for enrollment in the present records, a Commissorial Boundary Decree, setting forth in the first instance the estates specified in the said decree, to be laid before the illustrious Right Honourable commissioners, sealed with family seals",
         en_new="presented to the present office for entry, and submitted for enrollment in the present records, a Commissorial Boundary Decree between the estates specified in the said decree, pronounced by the illustrious Right Honourable commissioners, sealed with family seals",
         note='the abbreviations of the Latin formula were filled out wrongly: "pnti" is praesenti, "inr" inter, "p" per, "prolatum" agrees with Decretum'),
    dict(page='0655_a2', kind='dropped', weight='fact',
         old='oraz dla Drzewiec konwentskich zaś Drzewice i Trąbczyna dla dóbr swoich',
         new='oraz dla Drzewiec konwentskich z odpychaniem tylko z tąd dziedziny Trąbczyna, dziedzicy zaś Drzewiec i Trąbczyna dla dóbr swoich',
         scan='oraz dla Drzewiec Konwentskich z odpychaniem tylko z tąd Dziedziny Trąbczyna, Dziedzicy zaś Drzewiec y Trąbczyna dla Dobr swoich',
         en_old="and for the convent's Drzewce — and for Drzewce and Trąbczyn Mały, for their own estates and for Łukomia with rejection, and also Bukowe",
         en_new="and for the convent's Drzewce, with rejection only of the estate of Trąbczyn from here; while the heirs of Drzewce and Trąbczyn, for their own estates and for Łukomia with rejection, and also Bukowe",
         note='eight words skipped between two mentions of Drzewce and Trąbczyn. They say which neighbour each side acknowledged the three corner mounds for: the Chełmski brothers for Łukomia, Bukowe and Drzewce but not for Trąbczyn; the heirs of Drzewce and Trąbczyn for their own estates and Łukomia'),
    dict(page='0657_a1', kind='misread', weight='formula',
         old='w tę rotę ja wyżej przysięgam', new='w tę rotę: Ja N. przysięgam', scan='w tę Rotę. Ja N. Przysięgam',
         en_old='', en_new='', note='"N." for the name of the man swearing; check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='zeznam świadectw sądzie będę', new='zeznań świadectw sądził będę', scan='zeznań świadectw sądził będę',
         en_old='', en_new='', note='check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='kary na Ziemi o gwałtowności poczynione będzie należeć ściągną, nad grodę szkody przez wiolencych,',
         new='kary na kiem o gwałtowności poczynione będzie należeć ściągną, nadgrodę szkody przez wiolencje,',
         scan='kary na kiem o gwałtowności poczynione będzie należeć ściągną, nadgrodę szkody przez wiolencye,',
         en_old='', en_new='', note='"on whom it shall fall", not "on the land"; "compensation for damage", one word; check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='wyznaczeni przez nas wyżej wyrażonej i urodzeni komisarze', new='wyznaczeni przez nas wielmożni i urodzeni komisarze',
         scan='wyznaczeni przez nas WW. y Uro: Kommisarze',
         en_old='', en_new='', note='"WW." is Wielmożni, the style of the commissioners; check the English'),
    dict(page='0660_a1', kind='misread', weight='formula',
         old='komisja a statibus ani wypadła', new='komisja a statibus Regni wypadła', scan='Kommissya a Statibus Rni wypadła',
         en_old='', en_new='', note='"Rni" is Regni: issued by the Estates of the Kingdom'),
    dict(page='0660_a1', kind='dropped', weight='formula',
         old='ażeby urodzony Prusimski konstytucji wypadłej też przypozwy',
         new='ażeby urodzony Prusimski zadość czyniąc tak prawu koronnemu jako też konstytucji wypadłej też przypozwy',
         scan='ażeby Uro: Prusimski zadosyć czyniąc tak Prawu Koronnemu jako też Konstytucyi wypadłey też Przypozwy',
         en_old='', en_new='', note='seven words: the court orders Prusimski to file his summonses "satisfying both the law of the Crown and the constitution"'),
    dict(page='0661_a1', kind='misread', weight='fact',
         old='Osin, Łazów, Szetlewka dziedzic dukt swój', new='Osin, Łazów, Szetlewa dziedzic dukt swój', scan='Osin, Łazow Szetlewa Dziedzic Dukt swoy',
         en_old='', en_new='', note='Szetlew, as in the list of his estates on the page before, not Szetlewek'),
    dict(page='0661_a2', kind='misread', weight='formula',
         old='dziewięćdziesiątego drugiego ze znanej od drogi', new='dziewięćdziesiątego drugiego zeznanej od drogi', scan='Drugiego zeznaney od Drogi',
         en_old='', en_new='', note='"zeznanej", recorded; the same slip as on leaf 673'),
    dict(page='0661_a2', kind='misread', weight='fact',
         old='teraz do Pyzdr naukom bieżąca', new='teraz do Pyzdr na Łukom bieżąca', scan='teraz do Pyzdr na Łukom bieżąca',
         en_old='', en_new='', note='the road from Osiny "now running to Pyzdry by way of Łukom"'),
    dict(page='0662_a1', kind='misread', weight='formula',
         old='jeszcze pokłada manifest i wzywa o podobnyż postępek', new='jeszcze pokłada manifest i wizją o podobnyż postępek',
         scan='ieszcze pokłada manifest y wizyą o podobnyż postępek',
         en_old='', en_new='', note='he lays before the court a protest and an inspection ("wizją"), not "and calls"'),
    dict(page='0662_a2', kind='misread', weight='formula',
         old='bez wielkiej dyskwizycji będących', new='bez wszelkiej dyskwizycji będących', scan='bez wszelkiey dyskwizycyi będących',
         en_old='', en_new='', note='"beyond all question", not "without great question"'),
    dict(page='0662_a2', kind='dropped', weight='fact',
         old='i jakoby od tegoż narożnika przez Konwent jednostajnie zawsze',
         new='i jakoby od tegoż narożnika przez urodzonego Prusimskiego przedtem i teraz formowanego a przez Konwent jednostajnie zawsze',
         scan='y iakoby od tegoż narożnika przez Uro Prusimskiego przedtym y teraz formowanego a przez Konwent iednostaynie zawsze',
         en_old='', en_new='', note='eight words skipped between two "przez": the corner point is the one "formed by the Honourable Prusimski before and now, and acknowledged by the Convent" at all three earlier sittings'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='oblatowany twierdzące podług tego Kompromisu lub inszego jakowego, aktu którego nie można ob revolutionem temporum z na lesć kopce',
         new='oblatowany twierdząc że podług tego Kompromisu lub inszego jakowego, aktu którego nie można ob revolutionem temporum znaleźć kopce',
         scan='Oblatowany twierdząc że podług tego Kompromissu lub inszego iakowego, Aktu, ktorego nie można ob revolutionem temporum znaleść kopce',
         en_old='', en_new='', note='"asserting that ... which act cannot be found by reason of the passage of time"'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='Łomowa jednym gruncie jako to jest per directum wtej kontumacji wyrażono będących z Trąbczynem i innymi wsiami pryncypał nie pozwanych',
         new='Łomowa w jednym gruncie jako to jest per directum w tej kontumacji wyrażono będących z Trąbczynem i innymi wsiami pryncypalnie pozwanych',
         scan='Łomowa w iednym gruncie iako to iest per directum w tey kontumacyi wyrażono będących z Trąbczynem y innemi wsiami pryncypalnie pozwanych',
         en_old='', en_new='', note='"summoned as principals"; the words "dziedzicach o rozgraniczenie tychże dziedzin Łukomia Imielna i Łomowa" are a clerk\'s insertion from the foot of the page, and the transcription has them in the right place'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='ani Bukowe ab illo od Łukomia', new='ani Bukowe ab aevo od Łukomia', scan='ani Bukowe ab ævo od Łukomia',
         en_old='', en_new='', note='"from of old"; the ligature æ was read as "ill". Fairly sure, not certain'),
    dict(page='0664_a2', kind='misread', weight='formula',
         old='od narogu zagórowskiego, o nez między', new='od narogu zagórowskiego, oneż między', scan='od narogu zagorowskiego, oneż między',
         en_old='', en_new='', note='"oneż", the same (boundary)'),
    dict(page='0665_a1', kind='misread', weight='fact',
         old='w głowie lasu Ostrowie zaraz', new='w głowie lasu Ostrowce zaraz', scan='w Głowie lasu Ostrowce zaraz',
         en_old='', en_new='', note='the wood is Ostrowce, as everywhere else'),
    dict(page='0665_a1', kind='misread', weight='formula',
         old='zeznanej za sądzą jako też', new='zeznanej zasadza jako też', scan='zeznaney zasadza iako też',
         en_old='', en_new='', note='"zasadza", sets up (his corner point), not "judges"'),
    dict(page='0665_a1', kind='misread', weight='formula',
         old='urodzonego Starosty osądzając Bukowe', new='urodzonego Starosty osadzając Bukowe', scan='Uo Starosty osadzaiąc Bukowe',
         en_old='', en_new='', note='"osadzając", putting Bukowe in the place of Trąbczyn, not "judging"'),
    dict(page='0665_a2', kind='misread', weight='fact',
         old='czerniakowic Tomasz i Fabian', new='Czerniakowie Tomasz i Fabian', scan='Czerniakowie Tomasz y Fabian',
         en_old='', en_new='', note='a surname in the plural: the Czerniaks, Tomasz and Fabian'),
    dict(page='0665_a2', kind='misread', weight='fact',
         old='borowy Piotr, Szyman, narożnik, Wojciech Zelak', new='borowy Piotr Szyman, Nadolnik, Wojciech Zelak', scan='Borowy Piotr Szyman, Nadolnik, Woyciech Zelak',
         en_old='Piotr, Szyman, [uncertain: narożnik], Wojciech Zelak', en_new='Piotr Szyman, Nadolnik, Wojciech Zelak',
         note='a name in the list of Trąbczyn witnesses; the editor had marked "narożnik" as doubtful in the English. The scan has Nadolnik'),
    dict(page='0665_a2', kind='misread', weight='formula',
         old='dawno i teraz wyzwany a zaś', new='dawno i teraz używany a zaś', scan='dawno y teraz używany a zaś',
         en_old='', en_new='', note='"used", not "challenged": the Łukom forest "of old and now used" by Łukomia'),
    dict(page='0666_a2', kind='misread', weight='formula',
         old='zamiast Trąbczyna osądzał podczas', new='zamiast Trąbczyna osadzał podczas', scan='zamiast Trąbczyna osadzał podczas',
         en_old='', en_new='', note='"osadzał", put Bukowe in the place of Trąbczyn; the same slip as on the page before'),
    dict(page='0666_a2', kind='dropped', weight='fact',
         old='ale w granicach Łukomia Drzewiec i Trąbczyna przyznawali',
         new='ale w granicach Łukomia leżącą nie Bukowia ale tylko Łukomia Drzewiec i Trąbczyna przyznawali',
         scan='ale w Granicach Łukomia leżącą nie Bukowia ale tylko Łukomia Drzewiec y Trąpczyna przyznawali',
         en_old='', en_new='', note='five words skipped between two "Łukomia": the heirs of Drzewce and Trąbczyn rejected Bukowe "as having no boundaries of its own but lying within those of Łukomia", and acknowledged the corner mounds "not of Bukowe but only of Łukomia, Drzewce and Trąbczyn"'),
    dict(page='0667_a1', kind='misread', weight='formula',
         old='dziewięćdziesiąt drugiego zeznaje którą sobie', new='dziewięćdziesiąt drugiego zeznanej którą sobie', scan='Dziewięćdziesiąt Drugiego zeznaney ktorą sobie',
         en_old='', en_new='', note='"zeznanej", recorded, not "he testifies"'),
    dict(page='0667_a1', kind='misread', weight='fact',
         old='pomiędzy dziedzicami Trąbczyna małego Osin Łukomia', new='pomiędzy dziedzinami Trąbczyna małego Osin Łukomia', scan='pomiędzy Dziedzinami Trąbczyna małego Osin Łukomia',
         en_old='', en_new='', note='the old Pyzdry road runs "between the estates", not "between the heirs"'),
    dict(page='0667_a1', kind='misread', weight='formula',
         old='uczyniona i proces ucły,', new='uczyniona i proces uczy,', scan='uczyniona y Process uczy,',
         en_old='', en_new='', note='"uczy", shows'),
    dict(page='0667_a2', kind='misread', weight='formula',
         old='wziąwszy kondukt z urodzonym Chełmskim', new='wziąwszy kondykt z urodzonym Chełmskim', scan='wziąwszy kondykt z Urodz: Chełmskim',
         en_old='', en_new='', note='"kondykt", a compact: the abbey "having made common cause with Chełmski"'),
    dict(page='0659_a1', kind='misread', weight='fact',
         old='odda urodzonemu uczciwemu Radomskiemu', new='odda urodzonemu Radońskiemu', scan='odda Uu Radonskiemu',
         en_old='', en_new='', note='the surveyor Radoński, as on the page before; "Uu" is Urodzonemu, once'),
    dict(page='0668_a1', kind='misread', weight='fact',
         old='żalącego się z mównic z urodzonym Chełmskim czyniąc', new='żalącego się zmownie z urodzonym Chełmskim czyniąc', scan='żalącego się zmownie z Uro. Chełmskim czyniąc',
         en_old='acting in the matter of the ruin and wrong of the complainant with the Honourable Chełmski from the same platform',
         en_new='acting in collusion with the Honourable Chełmski to the ruin and wrong of the complainant',
         note='"zmownie", in collusion: Prusimski charges the abbey with colluding with Chełmski. The transcription had "z mównic" and the English "from the same platform"'),
    dict(page='0668_a1', kind='misread', weight='formula',
         old='in quantum bymu praepidicare miała', new='in quantum by mu praejudicare miała', scan='inquantum by mu præjudicare miała',
         en_old='', en_new='', note='"in so far as it might prejudice him"'),
    dict(page='0668_a1', kind='misread', weight='fact',
         old='Choczowi i Tomcom idąc', new='Choczowi i Tomicom idąc', scan='Choczowi y Tomicom idąc',
         en_old='', en_new='', note='Tomice, the neighbouring estate'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='Chocza i Tomie podle', new='Chocza i Tomic podle', scan='Chocza y Tomic podle',
         en_old='', en_new='', note='Tomice; the English already has Tomice'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='będącym do Tomie także', new='będącym do Tomic także', scan='będącym do Tomic także', en_old='', en_new='', note='Tomice'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='z Osin do Tomie szagowało', new='z Osin do Tomic szagowato', scan='z Osin do Tomic szagowato', en_old='', en_new='', note='Tomice; "szagowato", slantwise'),
    dict(page='0656_a1', kind='misread', weight='formula',
         old='pod górą pod górą przechodzącą', new='pod górą przechodzącą', scan='pod gorą [pod gorą, struck out] przechodzącą',
         en_old='', en_new='', note='the clerk wrote the two words twice and struck the second out; struck text is not transcribed'),
    dict(page='0669_a1', kind='misread', weight='formula',
         old='gdy ią i staw dziedziczy Łukomia na błotach swych takich że jak i stawisko z drogą stronę drogi w prawo duktu do nich należących wymyślił albo raczej za trzymaniem i wsparciem',
         new='gdy ią i staw dziedzicy Łukomia na błotach swych takich że jak i stawisko z drogą stronę drogi w prawo duktu do nich należących wymyślili albo raczej zatrzymaniem i wsparciem',
         scan='gdy ią y staw dziedzicy Łukomia na błotach swych ... wymyslili albo raczey zatrzymaniem y wsparciem',
         en_old='', en_new='', note='the subject is "the heirs of Łukomia", plural: they devised the pond and dyke and, by holding back the water, flooded the pond-ground'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='wyrażonych misze stawy albo raczej', new='wyrażonych insze stawy albo raczej', scan='wyrażonych insze stawy albo raczy',
         en_old='', en_new='', note='"insze", other ponds'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='drukowanym przez Ląd swój podpisanym', new='drukowanym przez Sąd swój podpisanym', scan='drukowanym przez Sąd swoy podpisanym',
         en_old='', en_new='', note='the printed summary "signed by his court"'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='że po niewaz dział roku tysiąc', new='że ponieważ przez dział roku tysiąc', scan='że ponieważ przez Dział Roku Tysiąc',
         en_old='', en_new='', note='"since by the division of the year ..."; "przez" was left out'),
    dict(page='0671_a1', kind='dropped', weight='fact',
         old='do kopca więcej nad inne większego niezbyt od ziemi wyniosłego',
         new='do kopca więcej nad inne większego płaskiego rowek koło siebie także okrągłość mającego niezbyt od ziemi wyniosłego',
         scan='do kopca więcey nad inne większego Płaskiego rowek koło siebie także okrągłość maiącego niezbyt od ziemi wyniosłego',
         en_old='', en_new='', note='seven words of the description of the fifth wall mound: it is "flat, having a small ditch round it and also a roundness"'),
    dict(page='0671_a2', kind='misread', weight='formula',
         old='one zagraniczną między Trąpczynem', new='one za graniczną między Trąpczynem', scan='one za graniczną między Trąpczynem',
         en_old='', en_new='', note='"za graniczną", as the boundary road, two words; written as one it means "foreign"'),
    dict(page='0671_a2', kind='misread', weight='formula',
         old='zawsze tęż drogę zagraniczną', new='zawsze tęż drogę za graniczną', scan='zawsze tęż drogę za graniczną',
         en_old='', en_new='', note='the same'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='miały trzymał i ścianę', new='miał i trzymał i ścianę', scan='miał y trzymał y ścianę',
         en_old='', en_new='', note='"miał i trzymał", held and kept'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='granicach Łukomskich odprzedaria i oddzielona', new='granicach Łukomskich odprzedana i oddzielona', scan='granicach Łukomskich odprzedana y oddzielona',
         en_old='', en_new='', note='"odprzedana", sold off: Grądzyń is a part of the Łukom ground sold to the abbey'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='urodzony Prusimski jaz ścianę', new='urodzony Prusimski już ścianę', scan='Uro. Prusimski już ścianę',
         en_old='', en_new='', note='"już", now'),
    dict(page='0672_a2', kind='misread', weight='formula',
         old='w własnym gruncie i boni onego z niezbyt dawno wybity', new='w własnym gruncie i boru onegoż niezbyt dawno wybity', scan='w własnym gruncie y boru onegoż nie zbyt dawno wybity',
         en_old='', en_new='', note='the ditch was dug "in his own ground and forest"'),
    dict(page='0674_a1', kind='misread', weight='fact',
         old='Biskupskiego i Koziechowskich', new='Biskupskiego i Kożuchowskich', scan='Biskupskiego y Kożuchowskich',
         en_old='', en_new='', note='the heirs of Biskupice are the Kożuchowskis, as five lines further down'),
    dict(page='0674_a2', kind='misread', weight='formula',
         old='czterdziestym piątym ze znaną którą fatentur', new='czterdziestym piątym zeznaną którą fatentur', scan='czterdziestym piątym zeznaną ktorą fatentur',
         en_old='', en_new='', note='"zeznaną", recorded'),
    dict(page='0674_a2', kind='misread', weight='formula',
         old='cuadendo paenas succubitas', new='evadendo paenas succubitas', scan='evadendo pænas succubitas',
         en_old='', en_new='', note='"evadendo", to escape the penalties'),
    # --- add above ---
]
