# -*- coding: utf-8 -*-
"""What the full check of APP 53/17/0/-/Konin Gr.145 against the scans found.

The editor asked (2026-10-06) for every page to be read for dropped phrases,
and for each to be listed with a word on whether it matters to the meaning.
One entry per finding, in page order:

    page    the page id (leaf N recto is <N>_a2, leaf N verso is <N+1>_a1)
    kind    'dropped'  words on the scan that the transcription lacks
            'misread'  a reading that changes the sense (small slips of spelling are not collected)
    old     the transcription as it stood; must stand exactly once on the page
    new     the same with the scan's words put in, in the modern spelling of the rest
    scan    the words as the scan has them
    en_old, en_new   the English before and after, where it has to follow ('' where it need not)
    weight  'court'    changes what the court found or ordered
            'fact'     adds or changes a place, person, measure, date or party
            'formula'  wording only
    note    anything else

Which pages have been read is in full_check_pages.txt (full_check_note.py).
The rows are applied by corrections_full.py when the check is finished.
"""

ROWS = [
    dict(page='0655_a2', kind='misread', weight='formula',
         old='obtulit officium prosequenti ad actandum et in acta prosequenti ingrossandum porrexit Decretum Commissoriale graniciale imprimis Haereditates eodem decreto specificatas pro illustris magnificos commissarios prolaturus sigillisque Gentilicis communitum sanum salvum ex illesum',
         new='obtulit officio praesenti ad acticandum et in acta praesentia ingrossandum porrexit Decretum Commissoriale graniciale inter Haereditates eodem decreto specificatas per illustres magnificos commissarios prolatum sigillisque Gentilitiis communitum sanum salvum et illesum',
         scan='obtulit Offo pnti ad acticand et in Acta pntia ingrossand porrexit Decrum Comissoriale graniciale inr Hareditates Eod Decro specificatas p Illres Mgcos Commissarios prolatum sigillisq Gentilicus communitum sanum salvum et illesum',
         en_old="presented to the office for prosecution, and submitted for enrollment in the present records, a Commissorial Boundary Decree, setting forth in the first instance the estates specified in the said decree, to be laid before the illustrious Right Honourable commissioners, sealed with family seals",
         en_new="presented to the present office for entry, and submitted for enrollment in the present records, a Commissorial Boundary Decree between the estates specified in the said decree, pronounced by the illustrious Right Honourable commissioners, sealed with family seals",
         note='the abbreviations of the Latin formula were filled out wrongly: "pnti" is praesenti, "inr" inter, "p" per, "prolatum" agrees with Decretum'),
    dict(page='0655_a2', kind='dropped', weight='fact',
         old='oraz dla Drzewiec konwentskich zaś Drzewice i Trąbczyna dla dóbr swoich',
         new='oraz dla Drzewiec konwentskich z odpychaniem tylko z tąd dziedziny Trąbczyna, dziedzicy zaś Drzewiec i Trąbczyna dla dóbr swoich',
         scan='oraz dla Drzewiec Konwentskich z odpychaniem tylko z tąd Dziedziny Trąbczyna, Dziedzicy zaś Drzewiec y Trąbczyna dla Dobr swoich',
         en_old="and for the convent's Drzewce — and for Drzewce and Trąbczyn Mały, for their own estates and for Łukomia with rejection, and also Bukowe",
         en_new="and for the convent's Drzewce, with rejection only of the estate of Trąbczyn from here; while the heirs of Drzewce and Trąbczyn, for their own estates and for Łukomia with rejection, and also Bukowe",
         note='eight words skipped between two mentions of Drzewce and Trąbczyn. They say which neighbour each side acknowledged the three corner mounds for: the Chełmski brothers for Łukomia, Bukowe and Drzewce but not for Trąbczyn; the heirs of Drzewce and Trąbczyn for their own estates and Łukomia'),
    dict(page='0657_a1', kind='misread', weight='formula',
         old='w tę rotę ja wyżej przysięgam', new='w tę rotę: Ja N. przysięgam', scan='w tę Rotę. Ja N. Przysięgam',
         en_old='', en_new='', note='"N." for the name of the man swearing; check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='zeznam świadectw sądzie będę', new='zeznań świadectw sądził będę', scan='zeznań świadectw sądził będę',
         en_old='', en_new='', note='check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='kary na Ziemi o gwałtowności poczynione będzie należeć ściągną, nad grodę szkody przez wiolencych,',
         new='kary na kiem o gwałtowności poczynione będzie należeć ściągną, nadgrodę szkody przez wiolencje,',
         scan='kary na kiem o gwałtowności poczynione będzie należeć ściągną, nadgrodę szkody przez wiolencye,',
         en_old='', en_new='', note='"on whom it shall fall", not "on the land"; "compensation for damage", one word; check the English'),
    dict(page='0657_a2', kind='misread', weight='formula',
         old='wyznaczeni przez nas wyżej wyrażonej i urodzeni komisarze', new='wyznaczeni przez nas wielmożni i urodzeni komisarze',
         scan='wyznaczeni przez nas WW. y Uro: Kommisarze',
         en_old='', en_new='', note='"WW." is Wielmożni, the style of the commissioners; check the English'),
    dict(page='0660_a1', kind='misread', weight='formula',
         old='komisja a statibus ani wypadła', new='komisja a statibus Regni wypadła', scan='Kommissya a Statibus Rni wypadła',
         en_old='', en_new='', note='"Rni" is Regni: issued by the Estates of the Kingdom'),
    dict(page='0660_a1', kind='dropped', weight='formula',
         old='ażeby urodzony Prusimski konstytucji wypadłej też przypozwy',
         new='ażeby urodzony Prusimski zadość czyniąc tak prawu koronnemu jako też konstytucji wypadłej też przypozwy',
         scan='ażeby Uro: Prusimski zadosyć czyniąc tak Prawu Koronnemu jako też Konstytucyi wypadłey też Przypozwy',
         en_old='', en_new='', note='seven words: the court orders Prusimski to file his summonses "satisfying both the law of the Crown and the constitution"'),
    dict(page='0661_a1', kind='misread', weight='fact',
         old='Osin, Łazów, Szetlewka dziedzic dukt swój', new='Osin, Łazów, Szetlewa dziedzic dukt swój', scan='Osin, Łazow Szetlewa Dziedzic Dukt swoy',
         en_old='', en_new='', note='Szetlew, as in the list of his estates on the page before, not Szetlewek'),
    dict(page='0661_a2', kind='misread', weight='formula',
         old='dziewięćdziesiątego drugiego ze znanej od drogi', new='dziewięćdziesiątego drugiego zeznanej od drogi', scan='Drugiego zeznaney od Drogi',
         en_old='', en_new='', note='"zeznanej", recorded; the same slip as on leaf 673'),
    dict(page='0661_a2', kind='misread', weight='fact',
         old='teraz do Pyzdr naukom bieżąca', new='teraz do Pyzdr na Łukom bieżąca', scan='teraz do Pyzdr na Łukom bieżąca',
         en_old='', en_new='', note='the road from Osiny "now running to Pyzdry by way of Łukom"'),
    dict(page='0662_a1', kind='misread', weight='formula',
         old='jeszcze pokłada manifest i wzywa o podobnyż postępek', new='jeszcze pokłada manifest i wizją o podobnyż postępek',
         scan='ieszcze pokłada manifest y wizyą o podobnyż postępek',
         en_old='', en_new='', note='he lays before the court a protest and an inspection ("wizją"), not "and calls"'),
    dict(page='0662_a2', kind='misread', weight='formula',
         old='bez wielkiej dyskwizycji będących', new='bez wszelkiej dyskwizycji będących', scan='bez wszelkiey dyskwizycyi będących',
         en_old='', en_new='', note='"beyond all question", not "without great question"'),
    dict(page='0662_a2', kind='dropped', weight='fact',
         old='i jakoby od tegoż narożnika przez Konwent jednostajnie zawsze',
         new='i jakoby od tegoż narożnika przez urodzonego Prusimskiego przedtem i teraz formowanego a przez Konwent jednostajnie zawsze',
         scan='y iakoby od tegoż narożnika przez Uro Prusimskiego przedtym y teraz formowanego a przez Konwent iednostaynie zawsze',
         en_old='', en_new='', note='eight words skipped between two "przez": the corner point is the one "formed by the Honourable Prusimski before and now, and acknowledged by the Convent" at all three earlier sittings'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='oblatowany twierdzące podług tego Kompromisu lub inszego jakowego, aktu którego nie można ob revolutionem temporum z na lesć kopce',
         new='oblatowany twierdząc że podług tego Kompromisu lub inszego jakowego, aktu którego nie można ob revolutionem temporum znaleźć kopce',
         scan='Oblatowany twierdząc że podług tego Kompromissu lub inszego iakowego, Aktu, ktorego nie można ob revolutionem temporum znaleść kopce',
         en_old='', en_new='', note='"asserting that ... which act cannot be found by reason of the passage of time"'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='Łomowa jednym gruncie jako to jest per directum wtej kontumacji wyrażono będących z Trąbczynem i innymi wsiami pryncypał nie pozwanych',
         new='Łomowa w jednym gruncie jako to jest per directum w tej kontumacji wyrażono będących z Trąbczynem i innymi wsiami pryncypalnie pozwanych',
         scan='Łomowa w iednym gruncie iako to iest per directum w tey kontumacyi wyrażono będących z Trąbczynem y innemi wsiami pryncypalnie pozwanych',
         en_old='', en_new='', note='"summoned as principals"; the words "dziedzicach o rozgraniczenie tychże dziedzin Łukomia Imielna i Łomowa" are a clerk\'s insertion from the foot of the page, and the transcription has them in the right place'),
    dict(page='0664_a1', kind='misread', weight='formula',
         old='ani Bukowe ab illo od Łukomia', new='ani Bukowe ab aevo od Łukomia', scan='ani Bukowe ab ævo od Łukomia',
         en_old='', en_new='', note='"from of old"; the ligature æ was read as "ill". Fairly sure, not certain'),
    dict(page='0664_a2', kind='misread', weight='formula',
         old='od narogu zagórowskiego, o nez między', new='od narogu zagórowskiego, oneż między', scan='od narogu zagorowskiego, oneż między',
         en_old='', en_new='', note='"oneż", the same (boundary)'),
    dict(page='0665_a1', kind='misread', weight='fact',
         old='w głowie lasu Ostrowie zaraz', new='w głowie lasu Ostrowce zaraz', scan='w Głowie lasu Ostrowce zaraz',
         en_old='', en_new='', note='the wood is Ostrowce, as everywhere else'),
    dict(page='0665_a1', kind='misread', weight='formula',
         old='zeznanej za sądzą jako też', new='zeznanej zasadza jako też', scan='zeznaney zasadza iako też',
         en_old='', en_new='', note='"zasadza", sets up (his corner point), not "judges"'),
    dict(page='0665_a1', kind='misread', weight='formula',
         old='urodzonego Starosty osądzając Bukowe', new='urodzonego Starosty osadzając Bukowe', scan='Uo Starosty osadzaiąc Bukowe',
         en_old='', en_new='', note='"osadzając", putting Bukowe in the place of Trąbczyn, not "judging"'),
    dict(page='0665_a2', kind='misread', weight='fact',
         old='czerniakowic Tomasz i Fabian', new='Czerniakowie Tomasz i Fabian', scan='Czerniakowie Tomasz y Fabian',
         en_old='', en_new='', note='a surname in the plural: the Czerniaks, Tomasz and Fabian'),
    dict(page='0665_a2', kind='misread', weight='fact',
         old='borowy Piotr, Szyman, narożnik, Wojciech Zelak', new='borowy Piotr Szyman, Nadolnik, Wojciech Zelak', scan='Borowy Piotr Szyman, Nadolnik, Woyciech Zelak',
         en_old='Piotr, Szyman, [uncertain: narożnik], Wojciech Zelak', en_new='Piotr Szyman, Nadolnik, Wojciech Zelak',
         note='a name in the list of Trąbczyn witnesses; the editor had marked "narożnik" as doubtful in the English. The scan has Nadolnik'),
    dict(page='0665_a2', kind='misread', weight='formula',
         old='dawno i teraz wyzwany a zaś', new='dawno i teraz używany a zaś', scan='dawno y teraz używany a zaś',
         en_old='', en_new='', note='"used", not "challenged": the Łukom forest "of old and now used" by Łukomia'),
    dict(page='0666_a2', kind='misread', weight='formula',
         old='zamiast Trąbczyna osądzał podczas', new='zamiast Trąbczyna osadzał podczas', scan='zamiast Trąbczyna osadzał podczas',
         en_old='', en_new='', note='"osadzał", put Bukowe in the place of Trąbczyn; the same slip as on the page before'),
    dict(page='0666_a2', kind='dropped', weight='fact',
         old='ale w granicach Łukomia Drzewiec i Trąbczyna przyznawali',
         new='ale w granicach Łukomia leżącą nie Bukowia ale tylko Łukomia Drzewiec i Trąbczyna przyznawali',
         scan='ale w Granicach Łukomia leżącą nie Bukowia ale tylko Łukomia Drzewiec y Trąpczyna przyznawali',
         en_old='', en_new='', note='five words skipped between two "Łukomia": the heirs of Drzewce and Trąbczyn rejected Bukowe "as having no boundaries of its own but lying within those of Łukomia", and acknowledged the corner mounds "not of Bukowe but only of Łukomia, Drzewce and Trąbczyn"'),
    dict(page='0667_a1', kind='misread', weight='formula',
         old='dziewięćdziesiąt drugiego zeznaje którą sobie', new='dziewięćdziesiąt drugiego zeznanej którą sobie', scan='Dziewięćdziesiąt Drugiego zeznaney ktorą sobie',
         en_old='', en_new='', note='"zeznanej", recorded, not "he testifies"'),
    dict(page='0667_a1', kind='misread', weight='fact',
         old='pomiędzy dziedzicami Trąbczyna małego Osin Łukomia', new='pomiędzy dziedzinami Trąbczyna małego Osin Łukomia', scan='pomiędzy Dziedzinami Trąbczyna małego Osin Łukomia',
         en_old='', en_new='', note='the old Pyzdry road runs "between the estates", not "between the heirs"'),
    dict(page='0667_a1', kind='misread', weight='formula',
         old='uczyniona i proces ucły,', new='uczyniona i proces uczy,', scan='uczyniona y Process uczy,',
         en_old='', en_new='', note='"uczy", shows'),
    dict(page='0667_a2', kind='misread', weight='formula',
         old='wziąwszy kondukt z urodzonym Chełmskim', new='wziąwszy kondykt z urodzonym Chełmskim', scan='wziąwszy kondykt z Urodz: Chełmskim',
         en_old='', en_new='', note='"kondykt", a compact: the abbey "having made common cause with Chełmski"'),
    dict(page='0659_a1', kind='misread', weight='fact',
         old='odda urodzonemu uczciwemu Radomskiemu', new='odda urodzonemu Radońskiemu', scan='odda Uu Radonskiemu',
         en_old='', en_new='', note='the surveyor Radoński, as on the page before; "Uu" is Urodzonemu, once'),
    dict(page='0668_a1', kind='misread', weight='fact',
         old='żalącego się z mównic z urodzonym Chełmskim czyniąc', new='żalącego się zmownie z urodzonym Chełmskim czyniąc', scan='żalącego się zmownie z Uro. Chełmskim czyniąc',
         en_old='acting in the matter of the ruin and wrong of the complainant with the Honourable Chełmski from the same platform',
         en_new='acting in collusion with the Honourable Chełmski to the ruin and wrong of the complainant',
         note='"zmownie", in collusion: Prusimski charges the abbey with colluding with Chełmski. The transcription had "z mównic" and the English "from the same platform"'),
    dict(page='0668_a1', kind='misread', weight='formula',
         old='in quantum bymu praepidicare miała', new='in quantum by mu praejudicare miała', scan='inquantum by mu præjudicare miała',
         en_old='', en_new='', note='"in so far as it might prejudice him"'),
    dict(page='0668_a1', kind='misread', weight='fact',
         old='Choczowi i Tomcom idąc', new='Choczowi i Tomicom idąc', scan='Choczowi y Tomicom idąc',
         en_old='', en_new='', note='Tomice, the neighbouring estate'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='Chocza i Tomie podle', new='Chocza i Tomic podle', scan='Chocza y Tomic podle',
         en_old='', en_new='', note='Tomice; the English already has Tomice'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='będącym do Tomie także', new='będącym do Tomic także', scan='będącym do Tomic także', en_old='', en_new='', note='Tomice'),
    dict(page='0656_a1', kind='misread', weight='fact',
         old='z Osin do Tomie szagowało', new='z Osin do Tomic szagowato', scan='z Osin do Tomic szagowato', en_old='', en_new='', note='Tomice; "szagowato", slantwise'),
    dict(page='0656_a1', kind='misread', weight='formula',
         old='pod górą pod górą przechodzącą', new='pod górą przechodzącą', scan='pod gorą [pod gorą, struck out] przechodzącą',
         en_old='', en_new='', note='the clerk wrote the two words twice and struck the second out; struck text is not transcribed'),
    dict(page='0669_a1', kind='misread', weight='formula',
         old='gdy ią i staw dziedziczy Łukomia na błotach swych takich że jak i stawisko z drogą stronę drogi w prawo duktu do nich należących wymyślił albo raczej za trzymaniem i wsparciem',
         new='gdy ią i staw dziedzicy Łukomia na błotach swych takich że jak i stawisko z drogą stronę drogi w prawo duktu do nich należących wymyślili albo raczej zatrzymaniem i wsparciem',
         scan='gdy ią y staw dziedzicy Łukomia na błotach swych ... wymyslili albo raczey zatrzymaniem y wsparciem',
         en_old='', en_new='', note='the subject is "the heirs of Łukomia", plural: they devised the pond and dyke and, by holding back the water, flooded the pond-ground'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='wyrażonych misze stawy albo raczej', new='wyrażonych insze stawy albo raczej', scan='wyrażonych insze stawy albo raczy',
         en_old='', en_new='', note='"insze", other ponds'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='drukowanym przez Ląd swój podpisanym', new='drukowanym przez Sąd swój podpisanym', scan='drukowanym przez Sąd swoy podpisanym',
         en_old='', en_new='', note='the printed summary "signed by his court"'),
    dict(page='0670_a1', kind='misread', weight='formula',
         old='że po niewaz dział roku tysiąc', new='że ponieważ przez dział roku tysiąc', scan='że ponieważ przez Dział Roku Tysiąc',
         en_old='', en_new='', note='"since by the division of the year ..."; "przez" was left out'),
    dict(page='0671_a1', kind='dropped', weight='fact',
         old='do kopca więcej nad inne większego niezbyt od ziemi wyniosłego',
         new='do kopca więcej nad inne większego płaskiego rowek koło siebie także okrągłość mającego niezbyt od ziemi wyniosłego',
         scan='do kopca więcey nad inne większego Płaskiego rowek koło siebie także okrągłość maiącego niezbyt od ziemi wyniosłego',
         en_old='', en_new='', note='seven words of the description of the fifth wall mound: it is "flat, having a small ditch round it and also a roundness"'),
    dict(page='0671_a2', kind='misread', weight='formula',
         old='one zagraniczną między Trąpczynem', new='one za graniczną między Trąpczynem', scan='one za graniczną między Trąpczynem',
         en_old='', en_new='', note='"za graniczną", as the boundary road, two words; written as one it means "foreign"'),
    dict(page='0671_a2', kind='misread', weight='formula',
         old='zawsze tęż drogę zagraniczną', new='zawsze tęż drogę za graniczną', scan='zawsze tęż drogę za graniczną',
         en_old='', en_new='', note='the same'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='miały trzymał i ścianę', new='miał i trzymał i ścianę', scan='miał y trzymał y ścianę',
         en_old='', en_new='', note='"miał i trzymał", held and kept'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='granicach Łukomskich odprzedaria i oddzielona', new='granicach Łukomskich odprzedana i oddzielona', scan='granicach Łukomskich odprzedana y oddzielona',
         en_old='', en_new='', note='"odprzedana", sold off: Grądzyń is a part of the Łukom ground sold to the abbey'),
    dict(page='0672_a1', kind='misread', weight='formula',
         old='urodzony Prusimski jaz ścianę', new='urodzony Prusimski już ścianę', scan='Uro. Prusimski już ścianę',
         en_old='', en_new='', note='"już", now'),
    dict(page='0672_a2', kind='misread', weight='formula',
         old='w własnym gruncie i boni onego z niezbyt dawno wybity', new='w własnym gruncie i boru onegoż niezbyt dawno wybity', scan='w własnym gruncie y boru onegoż nie zbyt dawno wybity',
         en_old='', en_new='', note='the ditch was dug "in his own ground and forest"'),
    dict(page='0674_a1', kind='misread', weight='fact',
         old='Biskupskiego i Koziechowskich', new='Biskupskiego i Kożuchowskich', scan='Biskupskiego y Kożuchowskich',
         en_old='', en_new='', note='the heirs of Biskupice are the Kożuchowskis, as five lines further down'),
    dict(page='0674_a2', kind='misread', weight='formula',
         old='czterdziestym piątym ze znaną którą fatentur', new='czterdziestym piątym zeznaną którą fatentur', scan='czterdziestym piątym zeznaną ktorą fatentur',
         en_old='', en_new='', note='"zeznaną", recorded'),
    dict(page='0674_a2', kind='misread', weight='formula',
         old='cuadendo paenas succubitas', new='evadendo paenas succubitas', scan='evadendo pænas succubitas',
         en_old='', en_new='', note='"evadendo", to escape the penalties'),
    dict(page='0675_a1', kind='dropped', weight='fact',
         old='w poniedziałek Świętą Jadwigą nastąpiony', new='w poniedziałek przed Świętą Jadwigą nastąpiony', scan='w Poniedziałek przed Swiętą Jadwigą nastąpiony',
         en_old='', en_new='', note='one word, but it is the date of the Konin land court decree of 1647: the Monday before St Hedwig; check the English'),
    dict(page='0675_a1', kind='dropped', weight='formula',
         old='usypane i poczynione być wyłuszczają się przeto mówi',
         new='usypane i poczynione być wyłuszczają i twierdzą a te aktu nad lasem Lusnie znajdują się przeto mówi',
         scan='usypane y poczynione być wyłuszczaią y twierdzą a te aktu nad lasem Lusnie znayduią się przeto mowi',
         en_old='', en_new='', note='eight words: the documents "set out and assert" that the mounds were newly raised on Trąbczyn ground, "and these are actually found above the Lusnie wood"; it repeats what the sentence has already said'),
    dict(page='0675_a2', kind='dropped', weight='formula',
         old='jako to wszystko zagraniczające i rzeczywistą istność',
         new='jako to wszystko zagraniczające i zajmujące dla Trąpczyna jawnie ewinkują i dowodzą i rzeczywistą istność',
         scan='jako to wszystko zagraniczaiące y zaymuiące dla Trąpczyna jawnie ewinkuią y dowodzą y rzeczywistą istność',
         en_old='', en_new='', note='seven words of Prusimski\'s argument: the mounds and blazes, "enclosing and taking in all this, openly vindicate and prove it for Trąbczyn"'),
    dict(page='0675_a2', kind='misread', weight='formula',
         old='z ujmą znaczną grątą Trąpczynskiego', new='z ujmą znaczną gruntu Trąpczynskiego', scan='z uymą znaczną gruntu Trąpczynskiego',
         en_old='', en_new='', note='"gruntu", of the ground'),
    dict(page='0675_a2', kind='misread', weight='formula',
         old='dziewięćdziesiąt drugiego ze znaną ze wszech miar', new='dziewięćdziesiąt drugiego zeznaną ze wszech miar', scan='Dziewięćdziesiąt Drugiego zeznaną, ze wszech miar',
         en_old='', en_new='', note='"zeznaną", recorded'),
    dict(page='0676_a1', kind='misread', weight='formula',
         old='drugiego ze znanej ani do ściany', new='drugiego zeznanej ani do ściany', scan='Drugiego zeznaney ani do ściany', en_old='', en_new='', note='"zeznanej", recorded'),
    dict(page='0676_a1', kind='misread', weight='formula',
         old='ale tez i włecsną wizja dziedziców Łukomia', new='ale też i własna wizja dziedziców Łukomia', scan='ale też y własna wizya Dziedzicow Łukomia',
         en_old='', en_new='', note='"the heirs of Łukomia\'s own inspection" of 1593'),
    dict(page='0676_a1', kind='misread', weight='formula',
         old='tylko pro limites Osińskich', new='tylko per limites Osińskich', scan='tylko p limites Osińskich',
         en_old='', en_new='', note='"per limites", through the bounds of Osiny: the words quoted from the inspection of 1593'),
    dict(page='0676_a1', kind='misread', weight='formula',
         old='drugiego ze znanej tak dokumentów jako i też i kopcom', new='drugiego zeznanej tak dokumentom jakoliteż i kopcom', scan='Drugiego zeznaney tak Dokumentom iakoliteż y kopcom',
         en_old='', en_new='', note='"zeznanej"; "as much to the documents as to the mounds"'),
    dict(page='0676_a2', kind='dropped', weight='fact',
         old='co i wizja sama okazuje gdy ta wizja w roku',
         new='co i wizja sama okazuje gdy tylko z części jego jest zeznana a nadto gdy ta wizja w roku',
         scan='co y wizya sama okazuie gdy tylko z części jego iest zeznana a nadto gdy ta wizya w Roku',
         en_old='', en_new='', note='nine words skipped between two "gdy": one of Prusimski\'s grounds against the inspection of 1592, that "it is recorded only for his share" (Wojciech Trąpczyński\'s), "and moreover" that he was then guardian of his four nephews'),
    dict(page='0676_a2', kind='misread', weight='formula',
         old='Beatissimae Virginis Mariae jest że znana a dato non concessa', new='Beatissimae Virginis Mariae jest zeznana a dato non concesso', scan='Beatissimæ Virginis Mariæ iest zeznana a dato non concesso',
         en_old='', en_new='', note='"zeznana", recorded; "dato non concesso", granted but not conceded'),
    dict(page='0676_a2', kind='misread', weight='formula',
         old='z instancji jego ze znana była', new='z instancji jego zeznana była', scan='z Instancyi Jego zeznana była', en_old='', en_new='', note='"zeznana"'),
    dict(page='0676_a2', kind='misread', weight='formula',
         old='to cząc proceso zalewek gruntów', new='tocząc proces o zalewek gruntów', scan='tocząc Process o zalewek gruntow',
         en_old='', en_new='', note='"conducting a suit over the flooding of the grounds"'),
    dict(page='0677_a1', kind='misread', weight='formula',
         old='z synowcami swemi mianego jest ze znana', new='z synowcami swemi mianego jest zeznana', scan='z Synowcami swemi mianego iest zeznana', en_old='', en_new='', note='"zeznana"'),
    dict(page='0677_a1', kind='misread', weight='fact',
         old='trybunału bydgowskiego', new='trybunału bydgoskiego', scan='Trybunału Bydgoskiego',
         en_old='', en_new='', note='the Tribunal sitting at Bydgoszcz, 1768'),
    dict(page='0677_a2', kind='dropped', weight='fact',
         old='którym dowodzi że Wojciech Trąpczyńskie był całego Trąpczyna dziedzicem a był opiekunem',
         new='którym dowodzi że Wojciech Trąpczyński nie był całego Trąpczyna dziedzicem a był opiekunem',
         scan='ktorym dowodzi że Woyciech Trąpczynski nie był całego Trąpczyna Dziedzicem a był opiekunem',
         en_old='', en_new='', note='one word, "nie", and it reverses the sense: the decree proves that Wojciech Trąpczyński was NOT heir of the whole of Trąbczyn but guardian of his nephews. The same is said correctly twice further down the page. Check the English'),
    dict(page='0677_a2', kind='misread', weight='formula',
         old='Trąpczyńskiemi synowcami już na ten czas z opieki wyczynskiemi synowcami już na ten czas z opieki wysztemi ziednej',
         new='Trąpczyńskiemi synowcami już na ten czas z opieki wyszłemi ziednej',
         scan='Trąpczynskiemi Synowcami iuż na ten czas z opieki wyszłemi z iedney',
         en_old='', en_new='', note='seven words stood twice in the transcription; the scan has them once'),
    dict(page='0677_a2', kind='misread', weight='formula',
         old='najświętszej Panny Marii ze znaną, którą similiter', new='najświętszej Panny Marii zeznaną, którą similiter', scan='Nayswiętszey Panny Maryi zeznaną, ktorą similiter', en_old='', en_new='', note='"zeznaną"'),
    dict(page='0677_a2', kind='misread', weight='formula',
         old='wyżej wyrażonych jest ze znana item', new='wyżej wyrażonych jest zeznana item', scan='wyżey wyrażonych iest zeznana Item', en_old='', en_new='', note='"zeznana"'),
    dict(page='0677_a2', kind='misread', weight='formula',
         old='jako i przed zeznanemi onej', new='jako i przed zeznaniem onej', scan='jako y przed zeznaniem oney', en_old='', en_new='', note='"before its recording"'),
    dict(page='0678_a1', kind='misread', weight='formula',
         old='z łaką (podatkiem od) szkody co do części swojej oprócz mnych wspoł', new='z taxą szkody co do części swojej oprócz innych współ',
         scan='z Taxą szkody co do części swoiey oprocz innych wspoł',
         en_old='', en_new='', note='"z taxą szkody", with an assessment of the damage; the transcription had "łaką" and a gloss in round brackets'),
    dict(page='0678_a1', kind='misread', weight='fact',
         old='niegdyś urodzony uczciwy Szczęsny z Popowa niegdy urodzonego Jana Trąpczyńskiego pozostałe małzonka matką',
         new='niegdy urodzoną Szczęsną z Popowa niegdy urodzonego Jana Trąpczyńskiego pozostałą małżonką matką',
         scan='niegdy Uu. Szczęsną z Popowa niegdy Uro. Jana Trąpczynskiego pozostałą małżonką matką',
         en_old='', en_new='', note='a woman: Szczęsna of Popowo, widow of Jan Trąpczyński, the mother, of the one part, and her sons of the other; check the English'),
    dict(page='0678_a1', kind='misread', weight='formula',
         old='sobie pretensji i na rogu z Łukomiemi nie zakładali albowiem Biskupice żadnej konkurencji i na lasu lusni sobie pretensji i na rogu z Łukomiemi nie zakładali albowiem Biskupice żadnej konkurrencji i na rogu z Łukomiem ani w tem',
         new='sobie pretensji i narogu z Łukomiem nie zakładali albowiem Biskupice żadnej konkurencji i narogu z Łukomiem ani w tem',
         scan='sobie pretensyi y narogu z Łukomiem nie zakładali albowiem Biskupice żadney konkurencyi y narogu z Łukomiem ani w tem',
         en_old='', en_new='', note='a run of words stood twice in the transcription; the scan has it once. "narogu", a corner point'),
    dict(page='0678_a1', kind='misread', weight='formula',
         old='jedno z nim rozumiejąc i kondukt przeciwko', new='jedno z nim rozumiejąc i kondykt przeciwko', scan='iedno z nim rozumieiąc y kondykt przeciwko',
         en_old='', en_new='', note='"kondykt", a compact'),
    dict(page='0678_a2', kind='misread', weight='formula',
         old='z wywrotów trzech który podobne drugie trzy', new='z wywrotów trzech którym podobne drugie trzy', scan='z wywrotow trzech ktorym podobne drugie trzy',
         en_old='', en_new='', note='"to which three others are alike"'),
    dict(page='0678_a2', kind='misread', weight='formula',
         old='respektem załego duktu', new='respektem całego duktu', scan='respektem całego duktu', en_old='', en_new='', note='"całego", the whole'),
    dict(page='0678_a2', kind='misread', weight='fact',
         old='staroście bydgowskiemu dziedzicowi', new='staroście bydgoskiemu dziedzicowi', scan='Staroście Bydgoskiemu Dziedzicowi', en_old='', en_new='', note='Starost of Bydgoszcz'),
    dict(page='0678_a2', kind='misread', weight='fact',
         old='ani konkurencji żadnej i Łukomiem nie mając', new='ani konkurencji żadnej z Łukomiem nie mając', scan='ani konkurrencyi żadney z Łukomiem nie maiąc',
         en_old='', en_new='', note='"with Łukomia": Gałecki has no common corner point with Łukomia'),
    dict(page='0678_a2', kind='misread', weight='formula',
         old='konduktem z urodzonym Chełmskim', new='kondyktem z urodzonym Chełmskim', scan='kondyktem z Uro. Chełmskim', en_old='', en_new='', note='"kondyktem", by compact'),
    dict(page='0680_a1', kind='misread', weight='fact',
         old='ile też na różniczanie ani z Tumic ani z Biskupic', new='ile też narożniczanie ani z Tomic ani z Biskupic', scan='ile też narożniczanie ani z Tumic ani z Biskupic',
         en_old='', en_new='', note='"narożniczanie", the neighbours at the corner point, one word; Tomice (the scan has "Tumic")'),
    dict(page='0680_a1', kind='misread', weight='formula',
         old='okazania swego w Lądzie swym nie stawa', new='okazania swego w sądzie swym nie stawa', scan='okazania swego w Sądzie swym nie stawa',
         en_old='', en_new='', note='"in his court", not "at Ląd": Chełmski does not appear in his court to rebut Prusimski\'s line. Check the English'),
    dict(page='0680_a1', kind='misread', weight='formula',
         old='ze wszech miar w rol sądzeniu', new='ze wszech miar w rozsądzeniu', scan='ze wszech miar w rozsądzeniu', en_old='', en_new='', note='"w rozsądzeniu", in judging'),
    dict(page='0680_a1', kind='misread', weight='formula',
         old='duktu urodzonego Chełmskiego ile wytknięto a tymczasem', new='duktu urodzonego Chełmskiego wiechami wytkniętego a tymczasem', scan='Duktu Uro. Chełmskiego wie[chami] wytknięto a tym czasem',
         en_old='', en_new='', note='"marked out with stakes", as on the next page ("ile wiechami wytkniętego"); the word runs into the fold here and is supplied from there'),
    dict(page='0680_a1', kind='misread', weight='formula',
         old='pomieniony jaśnie wielmożny ksiądz Woronowski', new='pomieniony imć ksiądz Woronowski', scan='pomieniony Jmć Xiądz Woronowski',
         en_old='', en_new='', note='"Jmć", Jegomość, the style of a priest; not "jaśnie wielmożny"'),
    dict(page='0680_a1', kind='misread', weight='formula',
         old='także situs usi obocznych', new='także situs wsi obocznych', scan='także situs wsi obocznych', en_old='', en_new='', note='"the position of the neighbouring villages"'),
    dict(page='0680_a2', kind='dropped', weight='fact',
         old='i wpada w drogę Zagórowską pod górą przechodzi',
         new='i wpada w drogę Zagórowską o kilka staj stąd a potym i przez drogę Zagórowską pod górą przechodzi',
         scan='y wpada w drogę Zagorowską o kilka stay ztąd a potym y przez drogę Zagorowską pod gorą przechodzi',
         en_old='', en_new='', note='nine words skipped between two "drogę Zagórowską": the Osiny road "falls into the Zagórów road a few staje from here, and then also crosses the Zagórów road below the hill"'),
    dict(page='0680_a2', kind='misread', weight='fact',
         old='w głowie czyli w zaczęciu lasu Ostrowce rzeczonego przy samej drodze Osińskiej między kopcami dwiema jakoby narożnymi urodzonego Chełmskiego a w rzeczy samej ściennymi drzewieckiemi i trąpczyńskiemi bieżącej będącego, na którą drogę sąd swój ku Osinom wprowadziwszy',
         new='w głowie czyli w zaczęciu lasu Ostrowce rzeczonego przy samej drodze Osińskiej między kopcami dwiema jakoby narożnymi urodzonego Chełmskiego a w rzeczy samej ściennymi drzewieckiemi i trąpczyńskiemi bieżącej będącego, na którą drogę sąd swój ku Osinom wyprowadziwszy',
         scan='na ktorą drogę Sąd swoy ku Osinom wyprowadziwszy',
         en_old='', en_new='', note='"wyprowadziwszy", having led the court out onto the road'),
    dict(page='0681_a2', kind='misread', weight='formula',
         old='z dawna ndawnosći Trąpczyńskie', new='z dawna z dawności Trąpczyńskie', scan='z dawna z dawności Trąpczynskie', en_old='', en_new='', note='a slip of typing'),
    dict(page='0681_a2', kind='misread', weight='fact',
         old='przez Olędry Trąpczyńskiego więcej', new='przez olędra Trąpczyńskiego więcej', scan='przez olędra Trąpczynskiego więcey',
         en_old='', en_new='', note='one Olęder of Trąbczyn, who had held and worked the small field for more than thirty years'),
    dict(page='0682_a1', kind='misread', weight='formula',
         old='będący szeroki przyszedłszy na drugą stronę', new='będący szeroki przeszedłszy na drugą stronę', scan='będący szeroki przeszedłszy na drugą stronę',
         en_old='', en_new='', note='"having crossed" the Lusnie wood to its far side'),
    dict(page='0682_a2', kind='misread', weight='fact',
         old='Gałecki starosta bydgowski dziedzic', new='Gałecki starosta bydgoski dziedzic', scan='Gałecki Starosta Bydgoski Dziedzic', en_old='', en_new='', note='Starost of Bydgoszcz'),
    dict(page='0682_a2', kind='misread', weight='formula',
         old='jedno z sobą na wyme gruntu trąpczyna', new='jedno z sobą na ujmę gruntu trąpczyna', scan='iedno z sobą na uymę gruntu Trąpczyna',
         en_old='', en_new='', note='"na ujmę", to the loss of the Trąbczyn ground'),
    dict(page='0683_a1', kind='dropped', weight='fact',
         old='i drodze Osińskiej przez dziedzica Biskupic ex praehabito condicto przynane są',
         new='i drodze Osińskiej przez Konwent mu, a drugi przy lesie Lusnie przez dziedzica Biskupic ex praehabito condicto przyznane są',
         scan='y drodze Osinskiey przez Konwent mu, a drugi przy lesie Lusnie przez Dziedzica Biskupic ex præhabito condicto przyznane są',
         en_old='', en_new='', note='eight words skipped between two "przez": the first corner point, at the Ostrowce wood and the Osiny road, was acknowledged to Chełmski "by the Convent, and the second, at the Lusnie wood," by the heir of Biskupice. As it stood, the heir of Biskupice acknowledged the first'),
    dict(page='0683_a1', kind='dropped', weight='formula',
         old='całego duktu urodzonego Chełmskiego i wyschniętego a oraz',
         new='całego duktu urodzonego Chełmskiego przez grunt własny Trąpczyna uformowanego i wytkniętego a oraz',
         scan='całego Duktu Uro. Chełmskiego przez grunt własny Trąpczyna uformowanego y wytchniętego a oraz',
         en_old='', en_new='', note='five words, and "wyschniętego" (dried up) for "wytkniętego" (marked out): Chełmski\'s whole line "formed and marked out through Trąbczyn\'s own ground"'),
    dict(page='0683_a1', kind='misread', weight='fact',
         old='Gałeckiemu staroście bydgowskiemu dziedzicowi', new='Gałeckiemu staroście bydgoskiemu dziedzicowi', scan='Gałeckiemu Staroście Bydgoskiemu Dziedzicowi', en_old='', en_new='', note='Starost of Bydgoszcz'),
    dict(page='0683_a2', kind='misread', weight='formula',
         old='wszedłszy i kilka stajnią na wschód', new='wszedłszy i kilka staj nią na wschód', scan='wszedłszy y kilka stay nią na wschod',
         en_old='', en_new='', note='"several staje along it", two words; as one word it is "stable"'),
    dict(page='0684_a1', kind='dropped', weight='court',
         old='nie mogą o tej ściany dalej kończyć, dalszych czynności w wyprowadzonych duktach udał się',
         new='nie mogąc tej ściany dalej kończyć, dalszy w niej dukt zawiesił a tymczasem do dalszych czynności w wyprowadzonych duktach udał się',
         scan='nie mogąc tey ściany daley konczyć, dalszy w niey Dukt zawiesił a tym czasem do dalszych czynności w wyprowadzonych Duktach udał się',
         en_old='', en_new='', note='seven words: at the bank of Czarny Bród the court, unable to finish this boundary because of the rain, "suspended the further line in it and meanwhile" turned to its other business. This is the suspension that the adjournment to 21 May 1776 later takes up'),
    dict(page='0684_a1', kind='misread', weight='fact',
         old='sive dezerty Drzęzgi Lasów i Biskupic', new='sive dezerty Drzęzgi Łazów i Biskupic', scan='sive Deserty Drzęzgi Łazow y Biskupic',
         en_old='', en_new='', note='Łazy, the third estate at the Tomala mound, as five lines above; not "Lasów"'),
    dict(page='0684_a1', kind='misread', weight='formula',
         old='w którego kopca stanąwszy', new='u którego kopca stanąwszy', scan='u ktorego kopca stanąwszy', en_old='', en_new='', note='"at which mound"'),
    dict(page='0684_a2', kind='dropped', weight='formula',
         old='ani przez siebie nie namówiłem i nie przekupiłem', new='ani przez siebie nie namówiłem nie przenajęłem i nie przekupiłem',
         scan='ani przez siebie nie namowiłem # nie przenaiąłem # y nie przekupiłem (the two words added by the clerk in the margin)',
         en_old='', en_new='', note='two words of the oath Prusimski was to swear about his witnesses, added by the clerk at the foot of the page: "nor hired"'),
    dict(page='0684_a2', kind='misread', weight='formula',
         old='czytania inkwizycji i sądzie swoim', new='czytania inkwizycji w sądzie swoim', scan='czytania Inkwizycyi w Sądzie swoim', en_old='', en_new='', note='"in its court"'),
    dict(page='0685_a1', kind='misread', weight='formula',
         old='solito more wywiodły wyprowadził', new='solito more wywiódł i wyprowadził', scan='solito more wywiodł y wyprowadził', en_old='', en_new='', note='"conducted and carried out" the examination'),
    dict(page='0685_a2', kind='misread', weight='formula',
         old='grodzkich konińskich ze znaną za największy', new='grodzkich konińskich zeznaną za największy', scan='Grodzkich Koninskich zeznaną za naywiększy', en_old='', en_new='', note='"zeznaną"'),
    dict(page='0686_a1', kind='misread', weight='formula',
         old='sancitam zdziałały wyprawił', new='sancitam udziałał i wyprawił', scan='sancitam udziałał y wyprawił', en_old='', en_new='', note='"made and carried out"'),
    dict(page='0686_a1', kind='misread', weight='formula',
         old='konińskich terme in praejudicium', new='konińskich ferme in praejudicium', scan='Koninskich ferme in pjudicium', en_old='', en_new='', note='Latin "ferme", almost: recorded "all but to the prejudice of his nephews". The same word stands plainly on the next leaf ("ac ferme in condicto")'),
    dict(page='0686_a1', kind='misread', weight='formula',
         old='dalszy proces o tem że podział', new='dalszy proces o tenże podział', scan='dalszy Process o tenże Podział', en_old='', en_new='', note='"over the same division"'),
    dict(page='0686_a1', kind='misread', weight='fact',
         old='w poniedziałek to Świętej', new='w poniedziałek po Świętej', scan='w Poniedziałek po Swiętey', en_old='', en_new='', note='"the Monday after" St Hedwig'),
    dict(page='0686_a2', kind='dropped', weight='fact',
         old='względem podziału z grodu pyzdrskiego wyjętym, is jeszcze',
         new='względem podziału Trąpczyna Nowej Wsi Osin i Łazów nastąpionym z grodu pyzdrskiego wyjętym, iż jeszcze',
         scan='względem podziału Trąpczyna Nowey Wsi Osin y Łazow nastąpionym z Grodu Pyzdrskiego wyiętym, Jż ieszcze',
         en_old='', en_new='', note='seven words: the division of 1693 was "of Trąbczyn, Nowa Wieś, Osiny and Łazy"'),
    dict(page='0686_a2', kind='misread', weight='formula',
         old='nie jako kondukt z dziedzicami', new='niejako kondykt z dziedzicami', scan='nieiako kondykt z Dziedzicami', en_old='', en_new='', note='"as it were a compact with the heirs of Łukomia"'),
    dict(page='0686_a2', kind='misread', weight='formula',
         old='jak świadczy rozracja a kontraktu między nigdy i Janem na Kolnie', new='jak świadczy roboracja kontraktu między niegdy Janem na Kolnie',
         scan='jak swiadczy Roboracya kontraktu między niegdy Janem na Kolnie', en_old='', en_new='', note='"the confirmation of the contract between the late Jan of Kolno ..."'),
    dict(page='0687_a1', kind='misread', weight='formula',
         old='onych ac terme in condicto', new='onych ac ferme in condicto', scan='onych ac ferme in condicto', en_old='', en_new='', note='Latin "ferme", almost: "and all but by arrangement with the heirs of Łukomia"'),
    dict(page='0687_a1', kind='misread', weight='formula',
         old='tychże dóbr za wartego w grodzie poznańskim w poniedziałek po Świętej Małgorzewie', new='tychże dóbr zawartego w grodzie poznańskim w poniedziałek po Świętej Małgorzacie',
         scan='tychże Dobr zawartego w Grodzie Poznanskim w Poniedziałek po Swiętey Małgorzacie', en_old='', en_new='', note='"zawartego", concluded; St Margaret'),
    dict(page='0687_a1', kind='misread', weight='formula',
         old='wyprawiona i udzielana, a nie tylko', new='wyprawiona i udziałana, nie tylko', scan='wyprawiona y udziałana, nie tylko', en_old='', en_new='', note='"udziałana", made'),
    dict(page='0687_a2', kind='misread', weight='formula',
         old='z dawna Osińska a te nie Pyzdrska stara', new='z dawna Osińska ale nie Pyzdrska stara', scan='z dawna Osinska ale nie Pyzdrska stara',
         en_old='', en_new='', note='"but not the old Pyzdry road"'),
    dict(page='0687_a2', kind='misread', weight='formula',
         old='z prawej strony leżą gdzie ponad lasem', new='z prawej strony leżą idzie ponad lasem', scan='z prawey strony leżą Jdzie po nad Lasem',
         en_old='', en_new='', note='"idzie", it runs (above the Ostrowce wood)'),
    dict(page='0688_a1', kind='misread', weight='formula',
         old='ani też to w tym miejscu dziedzina', new='ani też tu w tym miejscu dziedzina', scan='ani też tu w tym mieyscu Dziedzina', en_old='', en_new='', note='"tu", here'),
    dict(page='0688_a1', kind='misread', weight='formula',
         old='z Drzewcami brat i przywłaszczał', new='z Drzewcami brał i przywłaszczał', scan='z Drzewcami brał y przywłaszczał',
         en_old='', en_new='', note='"brał", took (as wall mounds), not "brother"'),
    dict(page='0689_a1', kind='misread', weight='formula',
         old='wraz z Łukomiem i jędów to jest Bukowe', new='wraz z Łukomiem i jedno to jest Bukowe', scan='wraz z Łukomiem y iedno to iest Bukowe',
         en_old='', en_new='', note='"and Bukowe is one and the same as Łukom"'),
    dict(page='0689_a2', kind='misread', weight='fact',
         old='pracowia Tomasz i Kazimierz Czerzniakowie Tomasz i Pabian', new='pracowici Tomasz i Kazimierz Czerniakowie Tomasz i Fabian',
         scan='Pracowici Tomasz y Kazimierz Czerzniakowie Tomasz y Fabian', en_old='', en_new='', note='the Drzewce witnesses again: "pracowici" (the working men), and Fabian, as on leaf 665'),
    dict(page='0689_a2', kind='misread', weight='formula',
         old='tak jak i teraz przyznawały twierdził', new='tak jak i teraz przyznawał i twierdził', scan='tak iak y teraz przyznawał y twierdził', en_old='', en_new='', note='"acknowledged and asserted"'),
    dict(page='0690_a1', kind='misread', weight='formula',
         old='Prusimskiego determinam musi zostawiwszy tylko samą ścianę Drzewiecką dalszą brać która', new='Prusimskiego determinari musi zostawiwszy tylko samą ścianę Drzewiecką dalszą bieżeć która',
         scan='Prusimskiego determinari musi zostawiwszy tylko samę ścianę Drzewiecką dalszą bieżeć ktora', en_old='', en_new='', note='"must end" (determinari); the Drzewce boundary "to run on"'),
    dict(page='0690_a1', kind='misread', weight='formula',
         old='a drugi ex controversiis, a dziedzicami Łukomia', new='a drugi ex controversiis, z dziedzicami Łukomia', scan='a drugi ex controversiis, z Dziedzicami Łukomia', en_old='', en_new='', note='"with the heirs of Łukomia"'),
    dict(page='0690_a2', kind='misread', weight='formula',
         old='przeciwnie swym przeszłym przyznawańcom uczynioną', new='przeciwnie swym przeszłym przyznawaniom uczynioną', scan='przeciwnie swym przeszłym przyznawaniom uczynioną',
         en_old='', en_new='', note='"contrary to its own earlier acknowledgements"'),
    dict(page='0690_a2', kind='misread', weight='formula',
         old='niedaleko leżących i wschodzie aktualnym trzech dziedzin to jest Łukomia Drzewiec i Trąpczyna to widocznym', new='niedaleko leżących i w schodzie aktualnym trzech dziedzin to jest Łukomia Drzewiec i Trąpczyna tu widocznym',
         scan='nie daleko leżących y w schodzie aktualnym trzech Dziedzin to iest Łukomia Drzewiec y Trąpczyna tu widocznym',
         en_old='', en_new='', note='in the court\'s ruling on the corner point: the mounds lie "at the actual meeting of the three estates, visible here"; "wschodzie" as one word is "east"'),
    dict(page='0690_a2', kind='misread', weight='formula',
         old='Drzewieckich i Trąpczyńskich a drogą od stawiska', new='Drzewieckich i Trąpczyńskich a drugą od stawiska', scan='Drzewieckich y Trąpczynskich a drugą od Stawiska',
         en_old='', en_new='', note='"and with the other side from the pond-ground", not "by the road"'),
    dict(page='0690_a2', kind='misread', weight='fact',
         old='jeden niedaleko na różnych kopców u wilczego do tu głębokiego', new='jeden niedaleko narożnych kopców u wilczego dołu głębokiego', scan='ieden nie daleko narożnych kopcow u wilczego dołu głębokiego',
         en_old='', en_new='', note='"one not far from the corner mounds, at the deep wolf pit"'),
    dict(page='0691_a1', kind='misread', weight='formula',
         old='świadkowie nie który zasięgają dalszą zaś ścianę tychże dziedzin że drogą za górowska sive Kaliska', new='świadkowie niektórzy zasięgają dalszą zaś ścianę tychże dziedzin że droga Zagórowska sive Kaliska',
         scan='swiadkowie niektorzy zasięgaią Dalszą zaś ścianę tychże Dziedzin że Droga Zagorowska sive Kaliska',
         en_old='', en_new='', note='"some witnesses reach back"; "that the Zagórów or Kalisz road ... divides and bounds"'),
    dict(page='0691_a1', kind='misread', weight='formula',
         old='którego imiego i łąk prócz tego stawiska', new='którego innego i łąk prócz tego stawiska', scan='ktorego innego y Łąk procz tego Stawiska',
         en_old='', en_new='', note='"no other [pond] and meadows than this pond-ground"'),
    dict(page='0691_a2', kind='dropped', weight='fact',
         old='którym aż Trąpczynscy dzieląc się likerowa insze stawy',
         new='którym urodzeni Trąpczynscy dzieląc się majętnością Trąpczyńską prócz stawów Garmin i Likerowa insze stawy',
         scan='ktorym UU. Trąpczynscy dzieląc się maiętnością Trąpczynską procz stawow Garmin y Likerowa insze stawy',
         en_old='', en_new='', note='six words: in the division of 1693 the Trąpczyńskis, "dividing the Trąbczyn estate, besides the ponds Garmin and Likerowa", reserve the other ponds for common fishing. Two ponds are named; "Garmin" is my reading of a name I do not know from elsewhere'),
    dict(page='0691_a2', kind='dropped', weight='fact',
         old='i potem nie prozekwowany na dziedzinie Trąpczyna Wielkiego',
         new='i potem nie prozekwowany, o zalewek gruntów, łąk, pastwisk, drzewa posuszenie na dziedzinie Trąpczyna Wielkiego',
         scan='y potem nie prozekwowany, o zalewek Gruntow, Łąk, pastwisk, Drzewa posuszenie na Dziedzinie Trąpczyna Wielkiego',
         en_old='', en_new='', note='seven words saying what the oath of 1589 was about: "the flooding of grounds, meadows and pastures and the killing of timber" on the estates of Trąbczyn Wielki and Mały and Osiny'),
    dict(page='0691_a2', kind='misread', weight='formula',
         old='zowego stawu successu temporis spasztoszałego', new='z owego stawu successu temporis spustoszałego', scan='z owego Stawu successu temporis spusztoszałego',
         en_old='', en_new='', note='"made out of that pond, gone to waste in the course of time"'),
    dict(page='0691_a2', kind='misread', weight='formula',
         old='(subo jednego czasu zastał chłopa siekącego pod samą groblą) nie bronił i nie mu nie mówił', new='(lubo jednego czasu zastał chłopa siekącego pod samą groblą) nie bronił i nic mu nie mówił',
         scan='/: lubo iednego czasu zastał chłopa siekącego pod samą Groblą :/ nie bronił y nic mu nie mowił', en_old='', en_new='', note='"although ... he said nothing to him"'),
    dict(page='0691_a2', kind='misread', weight='formula',
         old='ile i do tych i zaś drzewa nie mało', new='ile i do tych czas drzewa nie mało', scan='ile y do tych czas drzewa nie mało', en_old='', en_new='', note='"to this day"'),
    dict(page='0692_a1', kind='dropped', weight='fact',
         old='także w boru wyrobiony i jako jest kępami i różnym drzewem zarosły',
         new='także w boru wyrobiony i jako jest z takichże błot jako i to stawisko wyrobiony, tak jest kępami i różnym drzewem zarosły',
         scan='także w boru wyrobiony y Jako iest z takichże błot iako y to Stawisko wyrobiony, tak iest kępami y roznym drzewem zarosły',
         en_old='', en_new='', note='eight words skipped between two "wyrobiony": Chełmski\'s own pond "is made out of the same kind of marsh as this pond-ground, and so is overgrown" in the same way'),
    dict(page='0692_a1', kind='misread', weight='formula',
         old='są błota nie inne które się zowią kaczeługi', new='są błota insze które się zowią kacze ługi', scan='są błota insze ktore się zowią kaczeługi',
         en_old='', en_new='', note='"other marshes, called the duck bogs"; the transcription had "nie inne", not other. Fairly sure of "insze"'),
    dict(page='0692_a1', kind='misread', weight='formula',
         old='tamę z hojny a potym z drzewa', new='tamę z chojny a potym z drzewa', scan='tamę z hoyny a potym z drzewa', en_old='', en_new='', note='"z chojny", of pine brush'),
    dict(page='0692_a1', kind='misread', weight='formula',
         old='bronili i roznicali', new='bronili i rozrzucali', scan='bronili y rozrzucali', en_old='', en_new='', note='"defended [the meadows] and threw down [the dam]"'),
    dict(page='0692_a2', kind='misread', weight='formula',
         old='czego urodzony Chełmski to to tractu sprawy nie pokazuje', new='czego urodzony Chełmski toto tractu sprawy nie pokazuje', scan='czego Uro. Chełmski toto tractu Sprawy nie pokazuie',
         en_old='', en_new='', note='Latin "toto tractu", in the whole course of the case'),
    dict(page='0693_a1', kind='misread', weight='fact',
         old='a oraz i tamy z drzewa na nim położone', new='a oraz i ławy z drzewa na nim położone', scan='a oraz y ławy z drzewa na nim położone',
         en_old='', en_new='', note='"ławy", planks laid across the ford (the "ławiska" of leaf 671), not "tamy", dams; check the English'),
    dict(page='0693_a1', kind='misread', weight='formula',
         old='opisane rzetelnie i realnie take i naciosy', new='opisane rzetelne i realne także i naciosy', scan='opisane rzetelne y realne także y naciosy', en_old='', en_new='', note='the mounds are "genuine and real"; "także"'),
    dict(page='0693_a1', kind='misread', weight='formula',
         old='być się okazują i wylaszczaią i też', new='być się okazują i wyłuszczają i też', scan='być się okazuią y wyłuszczaią y też', en_old='', en_new='', note='"wyłuszczają"'),
    dict(page='0693_a2', kind='dropped', weight='fact',
         old='w tej ścianie nad kacze ługami jako już wyżej wyrażono jest należą',
         new='w tej ścianie nad kaczemi ługami ciągnącego się ponieważ okazuje się iż kacze ługi jako już wyżej wyrażono jest należą',
         scan='w tey ścianie nad kaczemi Ługami ciągnącego się ponieważ okazuie się iż kacze Ługi iako już wyżey wyrażono iest należą',
         en_old='', en_new='', note='eight words skipped between "kaczemi ługami" and "kacze ługi", in the court\'s reasons: "As to the further line in this boundary, running above the duck bogs: since it is shown that the duck bogs, as said above, belong and belonged to Trąbczyn"'),
    dict(page='0693_a2', kind='dropped', weight='fact',
         old='co do tej ściany aż u Studzience będących a przy tym',
         new='co do tej ściany aż u Studzienki i karczemnych gór i ługów przy tej Studzience będących a przy tym',
         scan='co do tey ściany aż u Studzienki y karczemnych gor y Ługow przy tey Studzience będących a przytym',
         en_old='', en_new='', note='seven words skipped between "Studzienki" and "Studzience": the end point of the boundary is "at the Studzienka and the tavern hills and bogs lying by that Studzienka"'),
    dict(page='0693_a2', kind='misread', weight='formula',
         old='i Trąpczyn jesiekał y do czasu', new='i Trąpczyn je siekał i do czasu', scan='y Trąpczyn Je siekał y do czasu', en_old='', en_new='', note='"Trąbczyn mowed them"'),
    dict(page='0693_a2', kind='misread', weight='formula',
         old='gruntu trąpczynskiego usypane ale kopce, co do pierwszego', new='gruntu trąpczynskiego usypane a te kopce, co do pierwszego', scan='Gruntu Trąpczynskiego usypane a te kopce, co do pierwszego',
         en_old='', en_new='', note='"and these mounds", not "but mounds"'),
    dict(page='0693_a2', kind='misread', weight='formula',
         old='a przez to dalszy dukty ciągłość ściany', new='a przez to dalszy dukt i ciągłość ściany', scan='a przez to dalszy dukt y ciągłość ściany', en_old='', en_new='', note='"the further line and the continuity of the boundary"'),
    dict(page='0693_a2', kind='misread', weight='formula',
         old='względem w sypania prywatnego kopcy ośm y naciosów', new='względem usypania prywatnego kopcy ośm i naciosów', scan='względem usypania prywatnego kopcy osm y naciosow', en_old='', en_new='', note='"usypania", the raising'),
    dict(page='0694_a1', kind='misread', weight='formula',
         old='tamże bydź mi ane okazują się na ostatek zej karczemne góry i ługi tam się znajdujące i dezarz sądowi swemu podległe',
         new='tamże bydź miane okazują się na ostatek że i karczemne góry i ługi tam się znajdujące i oczom sądowi swemu podległe',
         scan='tamże bydź miane okazuią się naostatek że y karczemne Gory y Ługi tam się znayduiące y oczom Sądowi swemu podległe',
         en_old='', en_new='', note='"held to be there"; "and that the tavern hills and bogs, found there and lying before the eyes of the court"'),
    dict(page='0694_a1', kind='misread', weight='formula',
         old='rezelwowanego i od sądzonego duktem', new='rezolwowanego i odsądzonego duktem', scan='rezolwowanego y odsądzonego Duktem', en_old='', en_new='', note='"resolved and adjudged away"'),
    dict(page='0694_a1', kind='misread', weight='formula',
         old='tak pro quem et ad quem', new='tak per quem et ad quem', scan='tak p quem et ad quem', en_old='', en_new='', note='"per quem", the course through'),
    dict(page='0694_a2', kind='misread', weight='formula',
         old='circa reis sionem ductus ejus habita tudzież iż wizji roku tego', new='circa revisionem ductus ejus habita tudzież i z wizji roku tego',
         scan='circa revisionem ductus ejus habita tudzież y z wizyi Roku tego', en_old='', en_new='', note='"at the review of his line"; "and also from the inspection of this year"'),
    dict(page='0694_a2', kind='misread', weight='formula',
         old='przez woźnego i szlachtę ze znanej ze tak w ścianie', new='przez woźnego i szlachtę zeznanej że tak w ścianie', scan='przez Woznego y Szlachtę zeznaney że tak w ścianie', en_old='', en_new='', note='"zeznanej, że"'),
    dict(page='0694_a2', kind='misread', weight='formula',
         old='tak wziemsture Kaliskiem na rokach', new='tak w ziemstwie Kaliskiem na rokach', scan='tak w Ziemstwie Kaliskiem na rokach', en_old='', en_new='', note='"in the land court"'),
    dict(page='0694_a2', kind='misread', weight='formula',
         old='nakazane od przy się ze nie się Biskupskiemu', new='nakazane odprzysiężenie się Biskupskiemu', scan='nakazane odprzysiężenie się Biskupskiemu', en_old='', en_new='', note='"the oath of denial ordered of Biskupski"; one word broken into five'),
    dict(page='0695_a1', kind='misread', weight='formula',
         old='te kopce i naciosy z wymą i szkodą wielką', new='te kopce i naciosy z ujmą i szkodą wielką', scan='te kopce y naciosy z uymą y szkodą wielką', en_old='', en_new='', note='"z ujmą", to the loss'),
    dict(page='0695_a2', kind='dropped', weight='fact',
         old='że ani urodzony Chełmski dziedzic Biskupic konkurencji swojej',
         new='że ani urodzony Chełmski narożnika ani urodzony Gałecki starosta bydgoski dziedzic Biskupic konkurencji swojej',
         scan='że ani Uro. Chełmski Narożnika ani Uro. Gałecki Starosta Bydgoski Dziedzic Biskupic konkurencyi swoiey',
         en_old='', en_new='', note='six words skipped between two "urodzony": "neither the Honourable Chełmski a corner point, nor the Honourable Gałecki, Starost of Bydgoszcz, heir of Biskupice, his convergence" can have here. As it stood, the text made Chełmski the heir of Biskupice and left Gałecki out'),
    dict(page='0696_a1', kind='misread', weight='formula',
         old='obstante hoc pariente Trąpczyna', new='obstante hoc pariete Trąpczyna', scan='obstante hoc pariete Trąpczyna', en_old='', en_new='', note='"pariete", the boundary (wall) of Trąbczyn standing in the way'),
    dict(page='0696_a1', kind='misread', weight='fact',
         old='drugiego ze znanej do Biskupie dochodzić', new='drugiego zeznanej do Biskupic dochodzić', scan='drugiego zeznaney do Biskupic dochodzić', en_old='', en_new='', note='"zeznanej"; Biskupice'),
    dict(page='0696_a2', kind='misread', weight='court',
         old='przeciwne tym wszystkiem dowodów być nie okazują, i sądowi swemu dowodzą',
         new='przeciwne tym wszystkiem dowodom być się okazują, i sądowi swemu dowodzą',
         scan='przeciwne tym wszystkiem dowodom być się okazuią, y Sądowi swemu dowodzą',
         en_old='', en_new='', note='"się", not "nie": in the court\'s reasons, the inspection of 1592, Chełmski\'s boundary and his corner point "are shown to be contrary to all these proofs". The transcription said they are not shown to be. Check the English'),
    dict(page='0696_a2', kind='misread', weight='formula',
         old='które probabilitetatem majorem w granicach zachowywać i obserwować et partem meliorationem ac notabiliora signa demonstrantem',
         new='które probabilitatem majorem w granicach zachowywać i obserwować et partem meliora ac notabiliora signa demonstrantem',
         scan='ktore pbabilitatem majorem w granicach zachowywać y obserwować et partem meliora ac notabiliora signa demonstrantem',
         en_old='', en_new='', note='the rule of Crown law the court applies: to follow the greater probability and admit to the oath "the party showing the better and more notable signs"'),
    dict(page='0696_a2', kind='misread', weight='formula',
         old='i owszem stante site et discordia', new='i owszem stante lite et discordia', scan='y owszem stante lite et discordia', en_old='', en_new='', note='"while the suit and the quarrel with them were pending"'),
    dict(page='0697_a1', kind='misread', weight='formula',
         old='et cum projudicio ich terme in condicto cum haeredibus Łukomia pro habito przeciw prawni natury i koronnemu',
         new='et cum praejudicio ich ferme in condicto cum haeredibus Łukomia praehabito przeciw prawu natury i koronnemu',
         scan='et cum pjudicio Jch ferme in condicto cum hæredibus Łukomia phabito przeciw Prawu Natury y koronnemu',
         en_old='', en_new='', note='"to their prejudice, all but by prior arrangement with the heirs of Łukomia, against the law of nature and of the Crown"'),
    dict(page='0697_a1', kind='misread', weight='formula',
         old='wyżej wyrażonym i inkwizycja on a na ostatek i samego urodzonego Chełmskiego duktowi o narożnikom przeciwną',
         new='wyżej wyrażonym i inkwizycjom a na ostatek i samego urodzonego Chełmskiego duktowi i narożnikom przeciwną',
         scan='wyżey wyrażonym y Inkwizycyom a naostatek y samego Uro Chełmskiego Duktowi y Narożnikom przeciwną',
         en_old='', en_new='', note='contrary "to the sworn inquiries, and in the end to Chełmski\'s own line and corner points"'),
    dict(page='0697_a1', kind='misread', weight='fact',
         old='dekret ostatni tybunału bygdowskiego roku', new='dekret ostatni trybunału bydgoskiego roku', scan='Dekret ostatni Trybunału Bydgoskiego Roku', en_old='', en_new='', note='the Tribunal at Bydgoszcz'),
    dict(page='0697_a1', kind='misread', weight='court',
         old='ani też nowych stanowić nie mogą się nie zważając, i owszem one jako nie prawną i nie woźną prawem samem',
         new='ani też nowych stanowić nie mogącą nie zważając, i owszem onę jako nieprawną i nieważną prawem samem',
         scan='ani też nowych stanowić nie mogącą nie zważaiąc, y owszem onę Jako nie prawną y nie ważną Prawem samem',
         en_old='', en_new='', note='in the ruling itself: the court, "not regarding" the inspection of 1592, "as unable to prejudice the old boundaries or set new ones", sets it aside "as unlawful and invalid". The transcription had "nie woźną" (not a bailiff) for "nieważną" (invalid). Check the English'),
    dict(page='0697_a1', kind='misread', weight='formula',
         old='co do ściany terminumque pro quem', new='co do ściany terminumque per quem', scan='co do ściany Terminumq pquem', en_old='', en_new='', note='"per quem"'),
    dict(page='0697_a2', kind='misread', weight='formula',
         old='alias in omni et in toto a próbuje konfirmuje', new='alias in omni et in toto aprobuje konfirmuje', scan='alias in omni et in toto aprobuie konfirmuie',
         en_old='', en_new='', note='in the ruling: the court "approves, confirms" Prusimski\'s line; written as two words it read "and tries". The English already has "approves"'),
    dict(page='0697_a2', kind='misread', weight='formula',
         old='ob intercedentia tuta niegdy', new='ob intercedentia fata niegdy', scan='ob intercedentia fata niegdy', en_old='', en_new='', note='"by reason of the intervening deaths" of Wolski and Kraszewski'),
    dict(page='0697_a2', kind='misread', weight='formula',
         old='jako confirmiter z inkwizycjami', new='jako conformiter z inkwizycjami', scan='iako conformiter z Inkwizycyami', en_old='', en_new='', note='"in conformity with"'),
    dict(page='0697_a2', kind='misread', weight='formula',
         old='jak in termini pro quem et ad quem, reprobuje', new='jak in termini per quem et ad quem, reprobuje', scan='Jak in termini p quem, et ad quem reprobuie', en_old='', en_new='', note='"per quem"'),
    dict(page='0697_a2', kind='misread', weight='formula',
         old='jako in termino pro quem at ad quem', new='jako in termino per quem et ad quem', scan='iako in Termino p quem et ad quem', en_old='', en_new='', note='"per quem et ad quem"'),
    dict(page='0698_a1', kind='misread', weight='formula',
         old='co potrzeba wyciąg w stanowic i one', new='co potrzeba wyciągać stanowić i one', scan='co potrzeba wyciągać stanowić y one', en_old='', en_new='', note='the commission\'s power "to require and to settle whatever is needed"'),
    dict(page='0698_a2', kind='misread', weight='fact',
         old='i laske na ośm łoku dla wymiani kopców ustanowi wszy', new='i laskę na ośm łokci dla wymiaru kopców ustanowiwszy', scan='y laskę na osm łokci dla wymiaru kopcow ustanowiwszy',
         en_old='', en_new='', note='"having fixed a rod of eight ells for measuring the mounds"; "łokci" and "wymiaru" are plain on the scan'),
    dict(page='0698_a2', kind='misread', weight='formula',
         old='butelkę szklaną z opisem komisji będącą przyło żywszy', new='butelkę szklaną z opisem komisji będącą przyłożywszy', scan='Butelkę szklaną z opisem kommissyi będącą przyłożywszy', en_old='', en_new='', note='one word'),
    dict(page='0698_a2', kind='misread', weight='formula',
         old='Trąpczyn na południe, Drzewce na północ, leżące i bory ich', new='Trąpczyn na południe, Drzewce na północ, leżący i bory ich', scan='Trąpczyn na południe, Drzewce na pułnoc, leżący y Bory Jch', en_old='', en_new='', note='small'),
    dict(page='0699_a1', kind='misread', weight='formula',
         old='in signum boni wydzielonego', new='in signum boru wydzielonego', scan='in signum Boru wydzielonego', en_old='', en_new='', note='the abbey\'s mound "as a sign of the forest set apart"; the same phrase is right on leaf 691'),
    dict(page='0699_a2', kind='misread', weight='formula',
         old='w końcu nimy tej seu polka o prętów tyleż usypany prej którym', new='w końcu niwy tej seu polka o prętów tyleż usypany przy którym',
         scan='w końcu niwy tey seu Polka o prętow tyleż usypany przy ktorym', en_old='', en_new='', note='"at the end of that field"; "przy którym"'),
    dict(page='0699_a2', kind='misread', weight='formula',
         old='na sośnie korytkowa to wycięty', new='na sośnie korytkowato wycięty', scan='na sosnie korytkowato wycięty', en_old='', en_new='', note='"cut trough-wise", one word'),
    dict(page='0700_a1', kind='dropped', weight='fact',
         old='dotykającym się niedaleko o prętów dwadzieścia pięć wysypany',
         new='dotykającym się niedaleko nowin Łomowskich na których jeszcze pnie stoją o prętów dwadzieścia pięć wysypany',
         scan='dotykaiącym się nie daleko nowin Łomowskich na ktorych ieszcze pnie stoią o prętow dwadzieścia pięć wysypany',
         en_old='', en_new='', note='seven words placing the twenty-first wall mound: "not far from the Łomowo clearings, on which the stumps still stand"'),
    dict(page='0700_a1', kind='misread', weight='formula',
         old='niedaleki nowim Łomowskich', new='niedaleko nowin Łomowskich', scan='nie daleko nowin Łomowskich', en_old='', en_new='', note='"not far from the Łomowo clearings"'),
    dict(page='0700_a1', kind='misread', weight='formula',
         old='tychże nowim łomowskich', new='tychże nowin łomowskich', scan='tychże nowin Łomowskich', en_old='', en_new='', note='"nowin", clearings'),
    dict(page='0700_a1', kind='misread', weight='fact',
         old='opuszczając w pracow drogę', new='opuszczając w prawo drogę', scan='opuszczaiąc w prawo drogę', en_old='', en_new='', note='"leaving on the right the road" to Tomice'),
    dict(page='0701_a2', kind='misread', weight='formula',
         old='wyżej w luzbie opisane', new='wyżej w liczbie opisane', scan='wyżey w liczbie opisane', en_old='', en_new='', note='"described above by number"'),
    dict(page='0702_a1', kind='misread', weight='formula',
         old='zadosyć czyniąc tak prawie koronnemu', new='zadosyć czyniąc tak prawu koronnemu', scan='zadosyć czyniąc tak prawu koronnemu', en_old='', en_new='', note='"satisfying both the law of the Crown"'),
    dict(page='0702_a2', kind='misread', weight='fact',
         old='Janem Zalanowskim', new='Janem Zdanowskim', scan='Janem Zdanowskim',
         en_old='Jan Zalanowski', en_new='Jan Zdanowski', note='one of the six witnesses who swore with Prusimski on the last mound; a Jan Zdanowski is also among those present on leaf 656'),
    dict(page='0702_a2', kind='misread', weight='formula',
         old='zadosyć czyniąc tak prawa koronnemu', new='zadosyć czyniąc tak prawu koronnemu', scan='zadosyć czyniąc tak Prawu koronnemu', en_old='', en_new='', note='"prawu"'),
    dict(page='0703_a1', kind='misread', weight='fact',
         old='w ścianie teraźniejszej z Biskupcami wyprowadzonego', new='w ścianie teraźniejszej z Biskupicami wyprowadzonego', scan='w ścianie teraznieyszey z Biskupicami wyprowadzonego', en_old='', en_new='', note='Biskupice'),
    dict(page='0703_a2', kind='misread', weight='fact',
         old='dziedzica Biskupie testante', new='dziedzica Biskupic testante', scan='Dziedzica Biskupic testante', en_old='', en_new='', note='Biskupice'),
    dict(page='0704_a1', kind='dropped', weight='formula',
         old='szerokość gruntu trąpczyńskiego biorąc ją od drogi Kaliskiej',
         new='szerokość gruntu trąpczyńskiego, ta zaś ciągłość gruntu Trąpczyńskiego biorąc ją od drogi Kaliskiej',
         scan='szerokość gruntu Trąpczynskiego, ta zaś ciągłość gruntu Trąpczynskiego biorąc ią od drogi Kaliskiey',
         en_old='', en_new='', note='five words skipped between two "gruntu Trąpczyńskiego": "and this continuity of the Trąbczyn ground, taking it from the Kalisz road" is shown to reach the corner point at Czarny Bród. It gives the long sentence its subject'),
    dict(page='0704_a2', kind='misread', weight='fact',
         old='w dekretach trybunalskich bydgowskich dwóch', new='w dekretach trybunalskich bydgoskich dwóch', scan='w Dekretach Trybunalskich Bydgoskich dwoch', en_old='', en_new='', note='the Tribunal at Bydgoszcz'),
    dict(page='0704_a2', kind='misread', weight='formula',
         old='na którym się kopce cygany i naciosy', new='na którym są kopce cygany i naciosy', scan='na ktorym są kopce Cygany y naciosy', en_old='', en_new='', note='"on which the Cygany mounds and the blazes are"'),
    dict(page='0705_a1', kind='misread', weight='fact',
         old='i Biskupcami sive dezerta Bystrzyce', new='i Biskupicami sive dezerta Bystrzyce', scan='y Biskupicami sive Dezertą Bystrzyce', en_old='', en_new='', note='Biskupice'),
    dict(page='0705_a2', kind='misread', weight='formula',
         old='Trąpczyna małego su Nowej Wsi', new='Trąpczyna małego seu Nowej Wsi', scan='Trąpczyna małego seu Nowey wsi', en_old='', en_new='', note='"seu"'),
    dict(page='0706_a1', kind='misread', weight='formula',
         old='która idzie a Łazów nimo olędrów', new='która idzie z Łazów nimo olędrów', scan='ktora idzie z Łazow nimo Olędrow', en_old='', en_new='', note='"from Łazy"'),
    dict(page='0707_a1', kind='misread', weight='formula',
         old='gdzie też jest podłe starego kopca', new='gdzie też jest podle starego kopca', scan='gdzie też iest podle starego kopca', en_old='', en_new='', note='"podle", beside; "podłe" is "base, mean"'),
    dict(page='0706_a2', kind='misread', weight='formula',
         old='kopce usypane i prętów tyleż są', new='kopce usypane o prętów tyleż są', scan='kopce usypane o prętow tyleż są', en_old='', en_new='', note='"at as many rods"'),
    # --- add above ---
]
