# -*- coding: utf-8 -*-
"""The summaries of III. HA MdA, III. Nr. 12367, written in the working session.

    python units/iiihamdaiiinr12367/intake/summaries_draft.py

Each document was read whole against its scan on 2026-10-04 and summarised in
German; the English is a translation of the German. They were claim-checked in
session on 2026-10-05 (claim_check.yml beside this file), as read_letters.py
--verify checks, not by the paid run: one sentence of document 6 weakened in the German.
The English was not made by summarise.py: this script writes the records
those tools would have written (units/<slug>/summaries_de.yml,
cache/summaries-raw-de/, cache/summaries-raw/), so that `summarise.py --build`
publishes them. Follows units/iiihamdaiiinr12366/intake/summaries_draft.py.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UNIT_DIR = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(UNIT_DIR))
SLUG = 'iiihamdaiiinr12367'
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

S = {
 1: ("Baron Mohrenheim antwortet aus Warschau, unter dem Briefkopf der auswärtigen Angelegenheiten des Königreichs Polen, dem preußischen Generalkonsul Schmidt auf dessen Schreiben vom 6. Februar (Nr. 275): Er verliere die Sache Weigel nicht aus den Augen und werde ihm nach der Rückkehr des Großfürsten Konstantin mitteilen, was darin geregelt werden konnte.",
     "Baron Mohrenheim, writing from Warsaw under the letterhead of the foreign affairs of the Kingdom of Poland, answers the note of the Prussian consul general Schmidt of 6 February (no. 275): he is not losing sight of the Weigel matter and, once Grand Duke Constantine has returned, will tell him what it has been possible to settle."),
 2: ("Undatiertes Billett Mohrenheims an Schmidt, beim Aufbruch geschrieben: Er habe am Vortag im Rat seine Denkschrift über die Sache Weigel und Eisenhardt vorgelesen, und dort sei einstimmig anerkannt worden, dass gezahlt werden müsse. Wie, darüber werde man noch beraten.",
     "An undated note from Mohrenheim to Schmidt, written as he was leaving: the day before he read his memorandum on the affair of Weigel and Eisenhardt to the council, which recognised unanimously that payment must be made. How it is to be made will be deliberated."),
 3: ("Undatiertes Billett Mohrenheims an Schmidt, an einem Dienstag geschrieben. Er schickt ihm dessen „Dubois“ zurück, den er mit großem Interesse gelesen habe, und bittet dringend um die Fortsetzung. Die Sache Weigel werde er vorantreiben; wegen des Übrigen solle Schmidt ruhig sein, man werde mit Ehren herauskommen. Er habe dort schreckliches Wetter, das zuweilen seine Lust am Landleben dämpfe. In einer quer an den Rand geschriebenen Zeile bittet er Schmidt, ihm für zwei Tage etwas zu überlassen; was, ist nicht gelesen.",
     "An undated note from Mohrenheim to Schmidt, written on a Tuesday. He returns Schmidt's “Dubois”, which he says he read with great interest, and asks pressingly for the continuation. He will push the Weigel matter; Schmidt should be easy about the rest, they will come out of it with honour. He has dreadful weather where he is, which at times dampens his pleasure in the country. In a line written sideways in the margin he asks Schmidt to let him have something for two days; what it is has not been read."),
 4: ("Mohrenheim teilt Schmidt mit, er habe dessen Schreiben vom 18. Februar (Nr. 352) dem Großfürsten Konstantin vorgelegt. Der Administrationsrat habe dem Großfürsten im August des Vorjahres berichtet, es sei anerkannt worden, dass die Zuständigkeit der Gerichte, die in der Sache der Bankiers Weigel und Eisenhardt geurteilt haben, in Frage gestellt werden könne, weil der Fall seiner Natur nach nur auf diplomatischem Weg zu lösen sei. Der Rat habe deshalb die Kommission der Finanzen und des Schatzes ermächtigt, einen Zuständigkeitskonflikt zu erklären und ihn der Generalversammlung des Staatsrats zur Entscheidung vorzulegen. Da der Großfürst seither keine weitere Mitteilung erhalten hat, hat er den Rat aufgefordert, den Abschluss der Sache zu beschleunigen.",
     "Mohrenheim tells Schmidt that he has laid his note of 18 February (no. 352) before Grand Duke Constantine. The Administrative Council reported to the Grand Duke in August of the previous year that the competence of the courts which had ruled in the case of the bankers Weigel and Eisenhardt was recognised as open to question, because by its nature the case could be resolved only by diplomatic means. The Council therefore authorised the Commission of Finance and Treasury to declare a conflict of jurisdiction and to bring it before the general assembly of the Council of State for decision. Having heard nothing further since, the Grand Duke has asked the Council to hasten the conclusion of the matter."),
 5: ("Ein Schreiben aus Warschau an den Generalkonsul Schmidt; die Unterschrift ist nicht gelesen. Der Verfasser hat Schmidts Schreiben vom 26. Juli (Nr. 1648) über den Prozess, der vor den Gerichten des Königreichs zwischen Frau Miączyńska und ihren Gläubigern wegen der vom Fürsten Hohenlohe aufgenommenen Schulden anhängig ist, dem Finanzminister vorgelegt. Er hat den Minister außerdem, wie Schmidt wünschte, an die Forderung erinnert, die der Bankier Weigel gegen den Fiskus des Königreichs erhebt, weil Urteile ihm eine Forderung dieser Art aberkannt haben. Aus zwei beiliegenden Stücken werde Schmidt sehen, dass seine Mitteilungen die nötigen Maßnahmen veranlasst haben und dass sein Schreiben vom 26. Juli der polnischen Verwaltung einen großen Dienst erwiesen hat, weil es sie rechtzeitig vor einem ungünstigen Ausgang dieser Prozesse warnte.",
     "A letter from Warsaw to the consul general Schmidt; the signature has not been read. The writer has laid Schmidt's note of 26 July (no. 1648), on the suit pending before the courts of the Kingdom between Madame Miączyńska and her creditors over the debts contracted by Prince Hohenlohe, before the minister of finance. As Schmidt wished, he has also reminded the minister of the claim that the banker Weigel raises against the treasury of the Kingdom because judgments denied him a debt of this kind. From two enclosed pieces Schmidt will see that his communications have brought about the measures needed, and that his note of 26 July did the Polish administration a signal service by warning it in time against an unfavourable outcome of these suits."),
 6: ("Abschrift eines Schreibens des Finanzministers Fürst Lubecki an Weigel, in polnischer Sprache. Er hat Weigels Schreiben vom 10. August und dessen Erneuerung vom 14. September erhalten, die Entschädigung für die Verluste verlangen, die Weigel dadurch erlitt, dass die Gerichte des Landes seine Forderung von 30.000 Talern aus den Gütern von Trąbczyn löschen ließen. Dem ersten Schreiben lag eine Aufstellung bei: 30.000 Taler Kapital, 31.800 Zinsen und 1300 Kosten, zusammen 63.100 Taler. Lubecki hält diese Forderung für überhöht, weil Weigel nach den im Land geltenden Gesetzen selbst beim günstigsten Ausgang des Prozesses nie so viel hätte erlangen können. Da er aber die wirklich erlittenen, nicht die nominellen Verluste ersetzen will, hat er angeordnet, den Wert der früher mit der Forderung belasteten Güter an Ort und Stelle festzustellen, um den wirklichen Wert des verlorenen Kapitals zu schätzen. Deshalb habe er bisher keine genaue Antwort geben können.",
     "Copy of a letter from the minister of finance, Prince Lubecki, to Weigel, in Polish. He has received Weigel's letter of 10 August and its renewal of 14 September, which ask compensation for the losses Weigel suffered when the courts of the country had his claim of 30,000 thalers struck off the Trąbczyn estates. With the first letter came a reckoning: 30,000 thalers of capital, 31,800 of interest and 1300 of costs, 63,100 thalers in all. Lubecki finds this demand excessive, because under the laws in force in the country Weigel could never have obtained so much even had the suit gone wholly in his favour. Wishing nonetheless to make good the losses really suffered, not the nominal ones, he has ordered the value of the estates once charged with the claim to be established on the spot, so as to assess the real value of the capital lost. That is why he has not yet been able to give a detailed answer."),
 7: ("Abschrift der Antwort Weigels an den Finanzminister Fürst Lubecki, aus Breslau. Auf dessen Schreiben vom 22. September (Nr. 59607/938) übersendet er in beglaubigter Abschrift den Hypothekenschein vom 14. August 1803 und die gerichtliche Taxe vom 6. Mai 1803 über die Güter Trąbczyn, Osiny, Łazy, Nowawieś, Zarobna und die Trąbczyner Hauländer. Nach dem Hypothekenschein ist der Wert der Güter auf 160000 Reichstaler angenommen. Vor seiner Forderung sind eingetragen: Kirchenkapitalien von 7000 Gulden oder 1166 Reichstalern 16 Groschen, für von Przepolewski, obschon bezahlt, 5000 und für von Lichnowski 42000, zusammen 48166 Reichstaler 16 Groschen. Für seinen Posten, für von Grottowski und jetzt für ihn eingetragen, blieben 111833 Reichstaler 8 Groschen, also 48733 Reichstaler 8 Groschen mehr als seine Forderung von 63100. Die Taxe sei nach den niedrigen Grundsätzen der Domänenveranschlagung angelegt und komme deshalb nur auf 128917 Reichstaler 17 Groschen; auch davon blieben nach Abzug der vorstehenden Posten 80751 Reichstaler 1 Groschen zu seiner Deckung. Seine Forderung sei also ganz sicher gewesen, und wäre ihm die Rechtshilfe nicht versagt worden, hätte er die vorstehenden Posten ablösen und in der Zwangsversteigerung mitbieten können. Er erwartet, dass der Fürst seine Befriedigung veranlasst und einen nahen Termin für eine Übereinkunft bestimmt, zu dem er selbst oder ein Bevollmächtigter erscheinen würde.",
     "Copy of Weigel's reply to the minister of finance, Prince Lubecki, from Wrocław. In answer to the minister's letter of 22 September (no. 59607/938) he sends certified copies of the mortgage certificate of 14 August 1803 and of the court valuation of 6 May 1803 for the estates of Trąbczyn, Osiny, Łazy, Nowawieś, Zarobna and the Trąbczyn settlers' villages. By the mortgage certificate the estates are taken to be worth 160000 Reichstaler. Entered ahead of his claim are church capitals of 7000 florins or 1166 Reichstaler 16 groschen, 5000 for von Przepolewski, though paid, and 42000 for von Lichnowski, 48166 Reichstaler 16 groschen together. For his own entry, made for von Grottowski and now standing in his name, 111833 Reichstaler 8 groschen remained, which is 48733 Reichstaler 8 groschen more than his claim of 63100. The valuation, he says, was drawn up on the low principles used for assessing crown domains and so comes to only 128917 Reichstaler 17 groschen; even of that, 80751 Reichstaler 1 groschen remain to cover him once the prior entries are deducted. His claim was therefore wholly secure, and had he not been denied the help of the law he could have paid off the prior entries and bid at the forced sale. He expects the Prince to bring about his satisfaction and to set an early date for an agreement, at which he or an agent would appear."),
 8: ("Abschrift eines zweiten Schreibens des Finanzministers Fürst Lubecki an Weigel (Nr. 77775), in polnischer Sprache. Die Unterlagen zur Schätzung der Güter von Trąbczyn, die Weigel mit seiner Eingabe vom 14. Oktober 1830 gesandt hat, hat er der Behörde übergeben, die er mit der Schätzung des heutigen Werts dieser Güter beauftragt hat. Weigel meine zwar, sein Kapital sei nach der gerichtlichen Taxe auf Trąbczyn vollkommen gesichert gewesen; diese Taxe sei aber 1803 aufgenommen worden, in einer Zeit überhöhter Güterpreise. Der wirkliche Wert der Forderung sei nach dem heutigen Wert der Liegenschaften zu schätzen, weil das letzte Urteil in Weigels Sache 1826 erging und erst von da an die Zwangsvollstreckung hätte betrieben werden können. Da Weigels Schreiben keine annehmbareren Bedingungen für einen Vergleich enthält, müsse er die Fertigstellung der Arbeit abwarten, die er in seiner Antwort vom 22. September erwähnt hat und deren Beschleunigung er überwacht.",
     "Copy of a second letter from the minister of finance, Prince Lubecki, to Weigel (no. 77775), in Polish. He has passed the papers for valuing the Trąbczyn estates, which Weigel sent with his submission of 14 October 1830, to the authority he has charged with assessing what the estates are worth now. Weigel holds that by the court valuation his capital was fully secured on Trąbczyn; but that valuation was made in 1803, at a time of inflated land prices. The real value of the claim must be reckoned by what landed property is worth today, because the last judgment in Weigel's case was given in 1826 and only from then could execution have been sought. As Weigel's letter offers no more acceptable terms for a settlement, he must await the completion of the work he mentioned in his reply of 22 September, which he is seeing hastened."),
 9: ("Ein Schreiben aus Warschau an den Generalkonsul Schmidt (Nr. 301), auf der Aufnahme mit „R. Fuhrmann“ unterzeichnet. Auf Schmidts Verwendung vom 10. Dezember 1831 für das Gesuch Weigels hat der Verfasser die Finanzkommission angewiesen, die Schätzung der Domäne Trąbczyn zu beschleunigen, zugleich die Sicherheit des Kapitals zu prüfen, das Weigel auf diesem Gut hat, und ihm die Sache vorzulegen; mit dieser Arbeit war die Kommission schon im Vorjahr beauftragt. Die besondere Vollmacht, die Seine Majestät dem Fürsten Lubecki zum Verhandeln mit Weigel erteilt hatte, könne keinem anderen dienen; er habe die nötigen Schritte getan, um dieses Hindernis zu beseitigen. Sobald beide Schwierigkeiten behoben sind, werde er alles tun, damit die begründeten Ansprüche eines preußischen Untertanen rasch Erfolg haben.",
     "A letter from Warsaw to the consul general Schmidt (no. 301), signed on the scan “R. Fuhrmann”. Following Schmidt's intervention of 10 December 1831 in support of Weigel's request, the writer has ordered the finance commission to hasten the valuation of the domain of Trąbczyn, to examine at the same time how well secured the capital is that Weigel has on that estate, and to lay the matter before him; the commission was already charged with this work the year before. The special authority that His Majesty had given Prince Lubecki to treat with Weigel can serve no one else, and he has taken the steps needed to remove that obstacle. As soon as both difficulties are lifted he will do all he can so that the well-founded claims of a Prussian subject succeed promptly."),
 10: ("Abschrift eines Schreibens Engels aus Warschau an den Generalkonsul Schmidt (Nr. 2216). Unter Bezug auf sein Schreiben vom 12. Februar (Nr. 1871) teilt er mit, dass der Staatsrat Joseph Lubowidzki, Präsident der Bank von Polen, auf Befehl des Kaisers und Königs mit der Ausführung der Konvention vom 29. Mai 1830 beauftragt ist und die nötigen Anweisungen erhalten hat. Dieser neue Kommissar sei auch ermächtigt, die Fragen zu bereinigen, die sich aus der Forderung des Bankiers Weigel ergeben. Engel hofft, er werde das Vertrauen des Kaisers rechtfertigen und sich um die Regelung aller Punkte bemühen, die zwischen der Regierung von Polen und der des Königs von Preußen noch endgültig zu ordnen sind.",
     "Copy of a letter from Engel at Warsaw to the consul general Schmidt (no. 2216). Referring to his note of 12 February (no. 1871), he reports that the councillor of state Joseph Lubowidzki, president of the Bank of Poland, has been charged by order of the Emperor and King with carrying out the convention of 29 May 1830 and has received the necessary instructions. This new commissioner is also authorised to settle the questions arising from the claim of the banker Weigel. Engel hopes he will justify the Emperor's confidence and work for the adjustment of every point still to be finally settled between the government of Poland and that of the King of Prussia."),
 11: ("Ein zweites Schreiben derselben Hand wie Dokument 9 an den Generalkonsul Schmidt, in Antwort auf dessen Schreiben vom 1. März (Nr. 432) über die Erledigung der Sache des Weigel in Breslau. Infolge der Maßnahmen, die der Verfasser getroffen und Schmidt am 24. Dezember des Vorjahres mitgeteilt hat, hat die Kommission der Finanzen und des Schatzes am 29. Februar Herrn Drake, Kommissar in der Abteilung der Staatsdomänen, mit der Schätzung der Güter von Trąbczyn beauftragt. Die Arbeit werde einige Zeit brauchen; sobald sie abgeschlossen ist, werde er Schmidt unterrichten. Er bittet ihn, dies inzwischen dem Handelshaus Weigel mitzuteilen.",
     "A second letter in the same hand as document 9 to the consul general Schmidt, answering his note of 1 March (no. 432) on the settlement of the affair of Weigel of Wrocław. As a result of the measures the writer took and reported to Schmidt on 24 December of the previous year, the Commission of Finance and Treasury on 29 February charged Mr Drake, a commissioner in the department of state domains, with valuing the Trąbczyn estates. The work will take some time; as soon as it is finished he will inform Schmidt. He asks him meanwhile to tell the trading house of Weigel."),
}


def main():
    with open(os.path.join(UNIT_DIR, 'summaries_de.yml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('# German summaries of III. HA MdA, III. Nr. 12367, written in the working session from a\n'
                '# reading of each document against its scan (intake/summaries_draft.py, 2026-10-04).\n'
                '# Claim-checked in session on 2026-10-05 (intake/claim_check.yml).\n'
                '# A finding aid, not part of the edition text. Published\n'
                '# through summarise.py --build --lang de.\n')
        for n, (de, _en) in sorted(S.items()):
            f.write(f'{SLUG}-{n:03d}: {json.dumps(de, ensure_ascii=False)}\n')
    for lang, sub, i in (('de', 'summaries-raw-de', 0), ('en', 'summaries-raw', 1)):
        d = os.path.join(ROOT, 'cache', sub)
        os.makedirs(d, exist_ok=True)
        for n, pair in S.items():
            pad = f'{SLUG}-{n:03d}'
            json.dump({'letter': str(n), 'pad': pad, 'summary': pair[i],
                       'model': 'in-session, 2026-10-04; claim-checked in session 2026-10-05',
                       'usage': {'input': 0, 'output': 0, 'cache_read': 0}},
                      open(os.path.join(d, pad + '.json'), 'w', encoding='utf-8'),
                      ensure_ascii=False, indent=1)
    print(len(S), 'summaries written, German and English')


if __name__ == '__main__':
    main()
