# -*- coding: utf-8 -*-
"""The summaries of Oe 1 Bü 14526, written again in the working session.

    python3 units/oe1bu14526/intake/summaries_draft.py

The first summaries of this holding (2026-09) were written by summarise.py from
the English translation, and the German ones beside them were never checked
against the documents. On 2026-10-08 every document was read whole in its
German text (corpus/text/, the corrected corpus) and summarised afresh in
German; the English is a translation of the German. Each statement was then
held to its document in session (claim_check.yml beside this file), as for the
other holdings. Not a paid run: there is no reading.json and no list of
suspected slips from read_letters.py.

The script writes units/<slug>/summaries_de.yml and replaces this holding's
lines, and only these, in site/_data/summaries.yml and summaries_de.yml (never
`summarise.py --build`: WORKING_NOTES, "The English, the summaries and the
claim check"). Where the desktop cache exists it writes the cache files too,
so that a later build there does not bring the old summaries back.
"""
import io
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
UNIT_DIR = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(UNIT_DIR))
SLUG = 'oe1bu14526'
REF = 'Oe 1 Bü 14526'
STAMP = 'in-session, 2026-10-08; claim-checked'
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, ROOT)
from numerals import group_digits  # noqa: E402  the English groups thousands, as english_forms.py does

S = {
 1: ("Ein undatiertes Schreiben ohne Namen: Der Schreiber bittet, mit Grimm über die beiliegenden Akten von Witów zu sprechen. Man habe sie lange in der Registratur zu Trąbczyn gesucht; beim Umzug des Schreibers aus seiner Wohnung in Wrocław nach Wilhelmsruh seien sie unter den Papieren seiner Frau gefunden worden, die sie in seiner Abwesenheit angenommen, verwahrt und ihm zu geben vergessen habe.",
     "An undated note without a name: the writer asks that Grimm be spoken to about the enclosed files on Witów. They had long been looked for in the registry at Trąbczyn; when the writer moved from his lodgings in Wrocław to Wilhelmsruh they were found among his wife's papers, who had received them while he was away, put them away safely and forgotten to give them to him."),
 2: ("Punktation, das heißt vorläufige Abrede, über den Verkauf des adligen Guts Witów im Kreis Warta: Der Forstinspektor Rochlitz verkauft es für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, an Martin Honrichs und Valentin von Kwasieborski für 16000 Rthl in drei Raten. Der Fürst hatte das Gut, das der König dem Obersten von Schlieben verliehen hatte, 1799 von dessen Witwe und Erben gekauft. Für Äcker, die die Bürgerschaft von Warta erstreiten könnte, leistet er keine Gewähr; wird die Erlaubnis zum Erwerb erst nach der Übergabe versagt, behalten die Käufer das Gut ein Jahr als Pacht für 800 Rthl. Danach tritt der Fürst 8000 Rthl der Kaufgelder an den Breslauer Bankier Carl Ferdinand Weigel ab.",
     "A punctation, that is, a preliminary agreement, on the sale of the noble estate of Witów in the Warta district: the forest inspector Rochlitz sells it on behalf of Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, to Martin Honrichs and Valentin von Kwasieborski for 16000 Rthl in three instalments. The Prince had bought the estate, which the King had granted to Colonel von Schlieben, from his widow and heirs in 1799. He gives no warranty for fields that the burgesses of Warta might win at law; if consent to the purchase is refused only after the handover, the buyers keep the estate for a year as a lease at 800 Rthl. After this the Prince assigns 8000 Rthl of the purchase money to the Wrocław banker Carl Ferdinand Weigel."),
 3: ("Das fürstliche Gerichtsamt zu Pszczew bestätigt einen Kaufvertrag: Joseph von Jankowski hat das Freischulzengut in Dormowo bei Birnbaum für 2000 Rthl, bar bezahlt, an den Hauptmann und Kreissteuereinnehmer Andreas Ernst Gneust verkauft. Der Vertrag nennt die Abgaben an den Hof Pszczew, das Recht, 250 Schafe zu halten und Bier für den eigenen Bedarf zu brauen, und freies Brennholz aus dem Pszczewer Forst. Jankowski, der kein Deutsch verstand, ließ sich den Vertrag polnisch vorlesen. Friedrich Ludwig, Fürst zu Hohenlohe, bestätigt ihn unbeschadet seiner Rechte, die er nach den alten Grundbüchern prüfen lassen will.",
     "The Prince's court office at Pszczew confirms a contract of sale: Joseph von Jankowski has sold the free mayor's holding at Dormowo near Birnbaum for 2000 Rthl, paid in cash, to the captain and district tax collector Andreas Ernst Gneust. The contract lists the dues to the manor of Pszczew, the right to keep 250 sheep and to brew beer for the household, and free firewood from the Pszczew forest. Jankowski, who did not understand German, had the contract read to him in Polish. Friedrich Ludwig, Prince of Hohenlohe, confirms it without prejudice to his rights, which he means to have checked against the old land books."),
 4: ("Kaufvertrag: Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, verkauft die Güter Kolno und Kamionna im Kreis Międzyrzecz, die ihm die Schenkungsurkunde vom 9. August 1796 verlieh, für 142000 Rthl an den Bankdirektor George Conrad Leixner in Frankfurt an der Oder. Das Geld ist bezahlt: über 53139 Rthl erhielt der frühere polnische Rittmeister von Broniewski, der als eingewiesener Gläubiger die Güter besaß, den Rest der Fürst. Der Käufer übernimmt zwei Kapitalien der Kirche zu Kamionna und das strittige Holzrecht in den Krobilawer Wäldern; eine Hypothek von 100000 Rthl für den Kriegs- und Forstrat von Triebenfeld ist getilgt. Für Leixner unterschreibt der Bankier Meyer Bernhard; Leixner genehmigt den Vertrag in Frankfurt.",
     "A contract of sale: Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, sells the estates of Kolno and Kamionna in the Międzyrzecz district, granted to him by the deed of gift of 9 August 1796, for 142000 Rthl to the bank director George Conrad Leixner of Frankfurt an der Oder. The money is paid: over 53139 Rthl went to the former Polish cavalry captain von Broniewski, who held the estates as a creditor put in possession, and the rest to the Prince. The buyer takes over two capital sums owed to the church at Kamionna and the disputed right to wood in the Krobilawer forests; a mortgage of 100000 Rthl for the councillor of war and forests von Triebenfeld has been paid off. The banker Meyer Bernhard signs for Leixner; Leixner approves the contract at Frankfurt."),
 5: ("Kaufvertrag, nur vom Fürsten Friedrich Ludwig zu Hohenlohe unterschrieben: Er verkauft die Güter Kolno und Kamionna für 142000 Rthl, ohne Anschlag, an den Bankrendanten George Conrad Leixner in Frankfurt an der Oder. Der Rittmeister von Broniewski, der die Güter innehat, gibt sie nach einem Vergleich vom 3. Juli gegen über 53139 Rthl zurück, die Leixner ihm am 8. September in Poznań zahlt; am 10. September werden die Güter schuldenfrei übergeben. 76000 Rthl hat Leixner bereits an den Bergrat Bernhardi gezahlt. Leixner will die Güter parzellieren, und der Fürst verspricht, das nicht zu hindern.",
     "A contract of sale signed only by Prince Friedrich Ludwig of Hohenlohe: he sells the estates of Kolno and Kamionna for 142000 Rthl, without a valuation, to the bank cashier George Conrad Leixner of Frankfurt an der Oder. Captain von Broniewski, who holds the estates, gives them up under a settlement of 3 July against over 53139 Rthl, which Leixner pays him at Poznań on 8 September; on 10 September the estates are handed over free of debt. Leixner has already paid 76000 Rthl to the mining councillor Bernhardi. Leixner means to divide the estates into smaller holdings, and the Prince promises not to hinder it."),
 6: ("Erbpachtvertrag vor dem Patrimonialgericht des Fürsten zu Hohenlohe-Ingelfingen: Dessen Generalbevollmächtigter, der Kriegs- und Forstrat von Triebenfeld, gibt dem Wirt Blazy Kukulski aus Osiny eine Hufe Ackerland bei Osiny in ewige Erbpacht. Kukulski hat 100 Rthl Einkaufsgeld bezahlt und zahlt jährlich 30 Rthl Erbzins; er ist frei von Hofdiensten und Erbuntertänigkeit, baut auf eigene Kosten und muss seine Getränke aus der herrschaftlichen Brauerei oder dem Krug nehmen. Der Vertrag wurde deutsch und polnisch vorgelesen; Kukulski unterzeichnet mit Kreuzen. Beigefügt ist die Generalvollmacht des Fürsten für Triebenfeld über die Güter Zagórów, Witów und Trąbczyn.",
     "A hereditary-lease contract made before the patrimonial court of the Prince of Hohenlohe-Ingelfingen: his general agent, the councillor of war and forests von Triebenfeld, grants the farmer Blazy Kukulski of Osiny one Hufe of arable land at Osiny in perpetual hereditary lease. Kukulski has paid 100 Rthl entry money and pays 30 Rthl rent a year; he is free of labour services and of hereditary subjection, builds at his own cost and must take his drink from the manor's brewery or inn. The contract was read out in German and Polish; Kukulski signs with crosses. Attached is the Prince's general power of attorney for Triebenfeld over the estates of Zagórów, Witów and Trąbczyn."),
 7: ("Erbpachtvertrag vor dem Patrimonialgericht zu Trąbczyn: Der Kriegs- und Forstrat von Triebenfeld gibt als Generalbevollmächtigter des Fürsten zu Hohenlohe-Ingelfingen dem Hauländer Gottlieb Sarre aus dem Peyserschen Hauland anderthalb Hufen wüstes Land im Wald bei Trąbczyn in ewige Erbpacht. Sarre hat 150 Rthl Einkaufsgeld bezahlt und zahlt jährlich 45 Rthl Erbzins, für das noch zu rodende Land erst nach drei Freijahren; die Hälfte des Zinses kann er ablösen, je 5 Rthl mit 100 Rthl Kapital. Er ist frei von Hofdiensten, baut auf eigene Kosten und muss Getränke und Mahlen bei der Herrschaft nehmen. Kopf und Beglaubigung der Ausfertigung sind polnisch.",
     "A hereditary-lease contract made before the patrimonial court at Trąbczyn: the councillor of war and forests von Triebenfeld, as general agent of the Prince of Hohenlohe-Ingelfingen, grants the Olęder farmer Gottlieb Sarre of the Peyserschen Hauland one and a half Hufen of waste land in the wood by Trąbczyn in perpetual hereditary lease. Sarre has paid 150 Rthl entry money and pays 45 Rthl rent a year, for the land still to be cleared only after three free years; he may redeem half the rent, 5 Rthl for each 100 Rthl of capital. He is free of labour services, builds at his own cost, and must take his drink from the manor and grind at its mill. The heading and the attestation of the engrossment are in Polish."),
 8: ("Erbpachtvertrag vor dem Patrimonialgericht zu Trąbczyn: Der Kriegs- und Forstrat von Triebenfeld gibt als Generalbevollmächtigter des Fürsten zu Hohenlohe-Ingelfingen dem Einsassen Christian Friedenberger aus dem Szymanowicer Hauland eine Hufe Land im Trąbczyner Wald in ewige Erbpacht, gegen 100 Rthl Einkaufsgeld, bezahlt, und 30 Rthl jährlichen Erbzins, für das zu rodende Land nach Freijahren bis 1809. Beigefügt sind die Generalvollmacht des Fürsten für Triebenfeld und die Erlaubnis der Kriegs- und Domänenkammer zu Kalisz vom 28. Januar 1806, die Herrschaften Zagórów und Trąbczyn zu parzellieren, Szetlewek und Oleśnica in Erbpacht zu geben und die Dienste der Untertanen in Geldzins umzuwandeln.",
     "A hereditary-lease contract made before the patrimonial court at Trąbczyn: the councillor of war and forests von Triebenfeld, as general agent of the Prince of Hohenlohe-Ingelfingen, grants the settler Christian Friedenberger of the Szymanowicer Hauland one Hufe of land in the Trąbczyn wood in perpetual hereditary lease, for 100 Rthl entry money, paid, and 30 Rthl rent a year, for the land to be cleared after free years running to 1809. Attached are the Prince's general power of attorney for Triebenfeld and the consent of the War and Domains Chamber at Kalisz of 28 January 1806 to divide the lordships of Zagórów and Trąbczyn into holdings, to give Szetlewek and Oleśnica in hereditary lease and to turn the services of the subjects into a money rent."),
 9: ("Pachtvertrag: Der Kriegs- und Forstrat Peter Friedrich August von Triebenfeld verpachtet für den Fürsten zu Hohenlohe-Ingelfingen das Vorwerk Kopojno, ohne Vieh und ohne Brauerei, für sechs Jahre von Johanni 1805 bis 1811 an den Propinationspächter Maciej von Niedźwiecki, für jährlich 1500 Rthl im Voraus. Der Pächter erhält die Dienste von zehn Komorniks und den Einliegern und übernimmt die Steuern und die Kompetenz für das Kloster Ląd. In einem Nachtrag pachtet er 13 Hufen dazu; die Pacht steigt auf 2125 Rthl. Niedźwiecki verzichtete auf ein polnisches Protokoll; der Vertrag wurde ihm polnisch erklärt.",
     "A lease: the councillor of war and forests Peter Friedrich August von Triebenfeld leases the home farm of Kopojno, on behalf of the Prince of Hohenlohe-Ingelfingen, without livestock and without the brewery, for six years from midsummer 1805 to 1811 to Maciej von Niedźwiecki, lessee of the drink monopoly, for 1500 Rthl a year in advance. The lessee has the services of ten komorniks and of the lodgers, and takes over the taxes and the allowance due to the monastery of Ląd. In a supplement he leases 13 Hufen more; the rent rises to 2125 Rthl. Niedźwiecki waived a record in Polish; the contract was explained to him in Polish."),
 10: ("Erbzinsvertrag: Der Kriegs- und Forstrat von Triebenfeld gibt für den Fürsten zu Hohenlohe-Ingelfingen dem Bauinspektor Johann Wilhelm Wollenhaupt 18 Hufen Acker des Vorwerks Drzewce und 2 Hufen Wiesen bei Wrąbczyn mit Wohnhaus und Brauhaus in Drzewce in ewigen Erbzins, für 6000 Rthl Einkaufsgeld und jährlich 300 Rthl. Wollenhaupt verpflichtet sich, das Land in zehn Bauernstellen von mindestens einer Hufe aufzuteilen. Am 25. August 1805 heben beide den Vertrag wegen veränderter Umstände auf; Triebenfeld zahlt Wollenhaupt 600 Rthl, womit dieser für alle Forderungen aus seiner Verwaltung für den Fürsten befriedigt ist. Wollenhaupt räumt das Wohnhaus in Drzewce bis Michaelis für die Vorwerkspächter Titz und Schatzmann.",
      "A hereditary-rent contract: the councillor of war and forests von Triebenfeld, on behalf of the Prince of Hohenlohe-Ingelfingen, grants the building inspector Johann Wilhelm Wollenhaupt 18 Hufen of arable of the Drzewce home farm and 2 Hufen of meadow at Wrąbczyn, with the dwelling house and brewhouse at Drzewce, at perpetual hereditary rent, for 6000 Rthl entry money and 300 Rthl a year. Wollenhaupt undertakes to divide the land into ten peasant holdings of at least one Hufe each. On 25 August 1805 both cancel the contract because circumstances have changed; Triebenfeld pays Wollenhaupt 600 Rthl, with which he is satisfied for all claims from his administration for the Prince. Wollenhaupt is to leave the house at Drzewce by Michaelmas for the farm lessees Titz and Schatzmann."),
 11: ("Erbzinsvertrag vor dem Patrimonialgericht zu Trąbczyn: Der Kriegs- und Forstrat von Triebenfeld gibt für den Fürsten zu Hohenlohe-Ingelfingen dem Schönfärber und Ratsmann Johann Seymert aus Zagórów drei Hufen vom Vorwerksacker von Trąbczyn, 2 Hufen 24 Morgen Acker und 6 Morgen Wiesen, in ewigen Erbzins, für 900 Rthl Einkaufsgeld zu Johanni und jährlich 45 Rthl. Seymert baut auf eigene Kosten, erhält kein Weide- und Holzrecht, trägt alle Steuern und die Kompetenz für das Kloster Ląd und ist frei von Hofdiensten.",
      "A hereditary-rent contract made before the patrimonial court at Trąbczyn: the councillor of war and forests von Triebenfeld, on behalf of the Prince of Hohenlohe-Ingelfingen, grants Johann Seymert, dyer and town councillor of Zagórów, three Hufen of the Trąbczyn home-farm land, 2 Hufen 24 Morgen of arable and 6 Morgen of meadow, at perpetual hereditary rent, for 900 Rthl entry money due at midsummer and 45 Rthl a year. Seymert builds at his own cost, has no right of pasture or wood, bears all taxes and the allowance due to the monastery of Ląd, and is free of labour services."),
 12: ("Erbzinsvertrag vor dem Patrimonialgericht zu Trąbczyn: Der Kriegs- und Forstrat von Triebenfeld gibt für den Fürsten zu Hohenlohe-Ingelfingen dem Förster George Friedrich Kammer aus Pietrzykowo vom Vorwerk Przybysław 6 Hufen Acker und 20 Morgen Wiesen mit allen Wirtschaftsgebäuden des Vorwerks in ewigen Erbzins. Kammer zahlt 2100 Rthl Einkaufsgeld, davon 100 Rthl für die Gebäude, und jährlich 100 Rthl Erbzins; zum Ausfahren des Mistes auf zwei Hufen stellt ihm die Herrschaft diesmal unentgeltlich die Gespanne.",
      "A hereditary-rent contract made before the patrimonial court at Trąbczyn: the councillor of war and forests von Triebenfeld, on behalf of the Prince of Hohenlohe-Ingelfingen, grants the forester George Friedrich Kammer of Pietrzykowo 6 Hufen of arable and 20 Morgen of meadow of the Przybysław home farm, with all the farm buildings, at perpetual hereditary rent. Kammer pays 2100 Rthl entry money, 100 Rthl of it for the buildings, and 100 Rthl rent a year; this once the manor lends him its teams free to cart the dung onto two Hufen."),
 13: ("Erbpachtvertrag: Der Kriegs- und Forstrat Peter Friedrich August von Triebenfeld überlässt als Generalbevollmächtigter des Fürsten zu Hohenlohe-Ingelfingen dem Amtmann Johann Gottlieb Tschachmann 20 Hufen Felder und Wiesen von Trąbczyn auf der Seite gegen Kopojno für immer, gegen 6000 Rthl Einkaufsgeld und jährlich 15 Rthl je Hufe. Tschachmann darf das Land in Teilen an andere weitergeben. Die Erbpächter sind frei von Erbuntertänigkeit und Hofdiensten, haben kein Weide- und Holzrecht und müssen die neuen Dörfer in einer oder zwei geraden Linien anlegen.",
      "A hereditary-lease contract: the councillor of war and forests Peter Friedrich August von Triebenfeld, as general agent of the Prince of Hohenlohe-Ingelfingen, makes over to the bailiff Johann Gottlieb Tschachmann 20 Hufen of fields and meadows of Trąbczyn, on the side towards Kopojno, for ever, for 6000 Rthl entry money and 15 Rthl a year for each Hufe. Tschachmann may pass the land on to others in parts. The hereditary lessees are free of hereditary subjection and labour services, have no right of pasture or wood, and must lay out the new villages in one or two straight lines."),
 14: ("Erbzinsvertrag vor dem Patrimonialgericht zu Trąbczyn: Der Kriegs- und Forstrat von Triebenfeld gibt für den Fürsten zu Hohenlohe-Ingelfingen dem fürstlichen Forstinspektor Carl Titz fünf Hufen vom Vorwerksacker von Trąbczyn, vom Weg nach Podbiele bis an den Mühlgraben, mit dem Obstgarten neben den Ställen, in ewigen Erbzins, für 1500 Rthl Einkaufsgeld in zwei Raten bis Johanni 1806 und jährlich 75 Rthl.",
      "A hereditary-rent contract made before the patrimonial court at Trąbczyn: the councillor of war and forests von Triebenfeld, on behalf of the Prince of Hohenlohe-Ingelfingen, grants the Prince's forest inspector Carl Titz five Hufen of the Trąbczyn home-farm land, from the road to Podbiele to the mill ditch, with the orchard beside the stables, at perpetual hereditary rent, for 1500 Rthl entry money in two instalments up to midsummer 1806 and 75 Rthl a year."),
 15: ("Punktation, vorbehaltlich der Genehmigung des Fürsten zu Hohenlohe-Ingelfingen: Der Kriegs- und Forstrat von Triebenfeld überlässt den unterzeichneten Erbpächtern, unter ihnen Carl Titz, 270 Hufen Felder, Wiesen und Wälder der Güter Trąbczyn, Łazy, Osiny, Nowawies und Przybysław, gegen 300 Rthl Einkaufsgeld und 15 Rthl jährlichen Zins je Hufe. Sie dürfen weiterverkaufen, müssen den Wald in vier Freijahren roden, sind frei von Erbuntertänigkeit und Hofdiensten und haften gemeinsam; jedes neue Dorf mit Schulzen und Schulmeister erhält 13 Morgen zinsfrei. Ein Vermerk zählt 156 Hufen 25 Morgen auf, die schon an einzelne Erwerber vergeben sind, darunter Tschachmann und Seymert; den Unternehmern bleiben 113 Hufen 4 Morgen.",
      "A punctation, that is, a preliminary agreement, subject to the approval of the Prince of Hohenlohe-Ingelfingen: the councillor of war and forests von Triebenfeld makes over to the undersigned hereditary lessees, Carl Titz among them, 270 Hufen of fields, meadows and woods of the estates of Trąbczyn, Łazy, Osiny, Nowawies and Przybysław, for 300 Rthl entry money and 15 Rthl rent a year for each Hufe. They may sell on, must clear the woodland within four free years, are free of hereditary subjection and labour services, and are jointly liable; each new village with a mayor and a schoolmaster receives 13 Morgen free of rent. A note lists 156 Hufen 25 Morgen already given out to individual buyers, Tschachmann and Seymert among them; 113 Hufen 4 Morgen remain for the contractors."),
 16: ("Erbpachtvertrag vor dem Patrimonialgericht zu Trąbczyn, vom Fürsten Friedrich Ludwig zu Hohenlohe selbst genehmigt: Der Kriegs- und Forstrat von Triebenfeld gibt den Einsassen Martin Giering, Wilhelm Daniel Schulz, Gottfried und Michel Dümmel, Gottfried Dams und Christoph Schoenfisch das Vorwerk Althütte bei Trąbczyn, 10 Hufen 10 Morgen, mit den Wirtschaftsgebäuden außer dem neuen Kuhstall in ewige Erbpacht. Sie zahlen 1500 Rthl Einkaufsgeld und jährlich 225 Rthl, für das zu rodende Land nach Freijahren bis Johanni 1808, und haften gemeinsam. Ein früherer Vertrag mit ihnen über dieselben zehn Hufen, den ein gewisser Kunkel geschlossen hatte, wird aufgehoben.",
      "A hereditary-lease contract made before the patrimonial court at Trąbczyn and approved by Prince Friedrich Ludwig of Hohenlohe himself: the councillor of war and forests von Triebenfeld grants the settlers Martin Giering, Wilhelm Daniel Schulz, Gottfried and Michel Dümmel, Gottfried Dams and Christoph Schoenfisch the home farm of Althütte by Trąbczyn, 10 Hufen 10 Morgen, with the farm buildings except the new cowshed, in perpetual hereditary lease. They pay 1500 Rthl entry money and 225 Rthl a year, for the land to be cleared after free years running to midsummer 1808, and are jointly liable. An earlier contract with them for the same ten Hufen, made by a certain Kunkel, is cancelled."),
 17: ("Vertrag, vorbehaltlich der Genehmigung des Fürsten Friedrich Ludwig zu Hohenlohe-Ingelfingen: Dessen Bevollmächtigter, der Kreisjustizkommissionsaktuar Kunkel, verkauft vom Vorwerk Alte Hütte der Herrschaft Trąbczyn 10 Hufen 10 Morgen mit den Wirtschaftsgebäuden außer dem Kuhstall an sechs Holländer, Martin Giering, Wilhelm Daniel Schulz, Gottfried und Michael Dümel, Gottfried Damt und Christoph Schoenfisch, zur Teilung in sechs gleiche Besitzungen. Sie zahlen 2500 Rthl, haften gemeinsam für alle Abgaben, zahlen einen jährlichen Erbzins, dürfen Raff- und Leseholz aus dem Trąbczyner Forst holen und dort weiden und können sich für die Schule der Holländergemeinde zu Trąbczyn anschließen.",
      "A contract subject to the approval of Prince Friedrich Ludwig of Hohenlohe-Ingelfingen: his agent, Kunkel, actuary of the district justice commission, sells 10 Hufen 10 Morgen of the Alte Hütte home farm of the lordship of Trąbczyn, with the farm buildings except the cowshed, to six Olęder settlers, Martin Giering, Wilhelm Daniel Schulz, Gottfried and Michael Dümel, Gottfried Damt and Christoph Schoenfisch, to be divided into six equal holdings. They pay 2500 Rthl, are jointly liable for all dues, pay a yearly hereditary rent, may gather fallen and dead wood in the Trąbczyn forest and graze there, and may join the Olęder community of Trąbczyn for schooling."),
 18: ("Abschrift eines Erbpachtvertrags vor dem Gerichtsamt zu Pszczew: Der Generalbevollmächtigte Glenck überlässt für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, der Bürgerschaft von Pszczew und den Gemeinden Stołuń, Kuligowo, Szarcz, Stoki, Świechocin und Łowyń die ganze Herrschaft Pszczew mit Vorwerken, Forsten und Propination als Eigentum; der Fürst behält Gerichtsbarkeit, Laudemium, Jagd und das Schloss. Der Preis beträgt 180000 Rthl und jährlich 1000 Rthl Grundzins; die Gemeinden übernehmen Hypothekenschulden von 137000 Rthl und laufende Prozesse. Ihre Bevollmächtigten Matheus Młynkiewicz und Johann Chmara ließen sich den Vertrag verdolmetschen. Beigefügt ist ein Reskript der Kammer zu Poznań von 1806: Der König hat Veräußerung und Parzellierung genehmigt.",
      "A copy of a hereditary-lease contract made before the court office at Pszczew: the general agent Glenck makes over, for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, to the burgesses of Pszczew and the village communities of Stołuń, Kuligowo, Szarcz, Stoki, Świechocin and Łowyń the whole lordship of Pszczew, with its home farms, forests and drink monopoly, as their property; the Prince keeps the jurisdiction, the transfer fee, the hunting and the castle. The price is 180000 Rthl and a ground rent of 1000 Rthl a year; the communities take over mortgage debts of 137000 Rthl and the pending lawsuits. Their agents, Matheus Młynkiewicz and Johann Chmara, had the contract interpreted to them. Attached is a rescript of the Chamber at Poznań of 1806: the King has approved the sale and the division into holdings."),
 19: ("Ausfertigung eines Erbpachtvertrags vor dem Gerichtsamt zu Pszczew: Der Generalbevollmächtigte Glenck überlässt für den regierenden Fürsten zu Hohenlohe-Ingelfingen der Bürgerschaft von Pszczew und den Gemeinden Stołuń, Kuligowo, Szarcz, Stoki, Świechocin und Łowyń die ganze Herrschaft Pszczew als Eigentum, gegen 180000 Rthl und jährlich 1000 Rthl Grundzins. Die Gemeinden übernehmen die eingetragenen Hypothekenschulden und zahlen 35000 Rthl sofort; der Fürst behält Gerichtsbarkeit, Laudemium, Jagd und das Schloss. Der frühere Pächter Bornstädt bleibt bis zum Ende seines Räumungsprozesses auf dem Vorwerk. Die Bevollmächtigten Matheus Młynkiewicz und Johann Chmara ließen sich den Vertrag verdolmetschen.",
      "An engrossment of a hereditary-lease contract made before the court office at Pszczew: the general agent Glenck makes over, for the reigning Prince of Hohenlohe-Ingelfingen, to the burgesses of Pszczew and the village communities of Stołuń, Kuligowo, Szarcz, Stoki, Świechocin and Łowyń the whole lordship of Pszczew as their property, for 180000 Rthl and a ground rent of 1000 Rthl a year. The communities take over the registered mortgage debts and pay 35000 Rthl at once; the Prince keeps the jurisdiction, the transfer fee, the hunting and the castle. The former lessee Bornstädt stays on the home farm until his eviction suit is decided. The agents, Matheus Młynkiewicz and Johann Chmara, had the contract interpreted to them."),
 20: ("Friedrich Ludwig, Fürst zu Hohenlohe, schenkt dem Gastwirt Friedrich Götzinger in Poznań das herrschaftliche Wohnhaus in Swięcia, als Dank für seine Mühe und Reisen beim Erbpachtgeschäft. Die Gebäude und Ländereien des Vorwerks Swięcia hat er am selben Tag Johann Christian Birlack aus Zilenzig, Johann Götzinger, Johann Siebert und Friedrich Götzinger in Erbpacht gegeben, das Wohnhaus ausgenommen; Götzinger kann es mit der übernommenen Brauerei-Erbpacht als Schank brauchen.",
      "Friedrich Ludwig, Prince of Hohenlohe, gives the manor house at Swięcia to Friedrich Götzinger, innkeeper at Poznań, in thanks for his trouble and journeys in the hereditary-lease business. He has the same day given the buildings and lands of the Swięcia home farm in hereditary lease to Johann Christian Birlack of Zilenzig, Johann Götzinger, Johann Siebert and Friedrich Götzinger, the manor house excepted; Götzinger can use the house as a tavern together with the brewery he has taken on hereditary lease."),
 21: ("Punktation: Der Kriegs- und Forstrat Peter Friedrich August von Triebenfeld verpflichtet sich als Generalbevollmächtigter des Fürsten zu Hohenlohe, das Gut Witów im Kreis Warta an Franz Meierowitz zu verkaufen, sobald der Verkauf an Honrichs aufgehoben ist, der weder zum Besitz fähig noch zahlungsfähig sei. Meierowitz zahlt 20000 Rthl und einen ewigen Kanon von jährlich 500 Rthl, den er mit 10000 Rthl ablösen kann. Da er die Fähigkeit, adlige Güter zu besitzen, noch nicht nachweisen kann, will Triebenfeld ihm zur königlichen Erlaubnis verhelfen; die Kosten trägt Meierowitz.",
      "A punctation, that is, a preliminary agreement: the councillor of war and forests Peter Friedrich August von Triebenfeld, as general agent of the Prince of Hohenlohe, undertakes to sell the estate of Witów in the Warta district to Franz Meierowitz as soon as the sale to Honrichs is cancelled, who, it says, is neither qualified to hold the estate nor able to pay. Meierowitz pays 20000 Rthl and a perpetual rent of 500 Rthl a year, which he may redeem with 10000 Rthl. Since he cannot yet show that he is entitled to hold noble estates, Triebenfeld will help him to the King's permission; Meierowitz bears the costs."),
 22: ("Die Regierung zu Poznań sendet dem regierenden Fürsten zu Hohenlohe-Ingelfingen eine Ausfertigung des Kaufvertrags über die Güter Kolno und Kamionna mit dem Bankrendanten Leixner, den sie am selben Tag bestätigt hat.",
      "The Government at Poznań sends the reigning Prince of Hohenlohe-Ingelfingen an engrossment of the contract of sale of the estates of Kolno and Kamionna to the bank cashier Leixner, which it has confirmed the same day."),
 23: ("Bestätigung des Kaufvertrags vom Januar 1805, mit dem Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, die Güter Kolno und Kamionna für 142000 Rthl an den Bankrendanten George Conrad Leixner in Frankfurt an der Oder verkauft, ausgestellt unter dem Siegel der Regierung zu Poznań. Am 6. Februar 1805 bekannten sich die Bevollmächtigten, der Justizrat Melzer für den Fürsten und der Kriminalrat Guderian für Leixner, vor dem Regierungsassessor Bewert zu dem Vertrag. Eingerückt sind der Vertrag und die Vollmachten; Leixner erweiterte seine Vollmacht, weil ein neuer Vertrag den vom 15. Juni 1804 ersetzt hatte.",
      "A confirmation of the contract of January 1805 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, sells the estates of Kolno and Kamionna for 142000 Rthl to the bank cashier George Conrad Leixner of Frankfurt an der Oder, issued under the seal of the Government at Poznań. On 6 February 1805 the agents, the justice councillor Melzer for the Prince and the criminal councillor Guderian for Leixner, acknowledged the contract before the government assessor Bewert. The contract and the powers of attorney are set out in full; Leixner extended his power of attorney because a new contract had replaced the one of 15 June 1804."),
 24: ("Die Kriegs- und Domänenkammer zu Poznań lehnt, auf eine königliche Kabinettsresolution hin, das Gesuch des Fürsten zu Hohenlohe-Ingelfingen ab, die Herrschaft Pszczew an die Bürgerschaft und die übrigen Einsassen in Erbpacht zu geben, und gibt den Vertrag zurück. Andere Grundherren würden folgen, und die Güter des zahlreichen Adels der Provinz, auf dessen Erhaltung zu sehen sei, würden vermindert; der Pszczewer Forst, der einzige beträchtliche der Gegend, könnte nicht ordentlich bewirtschaftet werden; die Einsassen hätten genug Land, die Bürger sollten eher städtische Gewerbe treiben, und die meisten seien zu arm.",
      "The War and Domains Chamber at Poznań, on a royal cabinet resolution, refuses the request of the Prince of Hohenlohe-Ingelfingen to give the lordship of Pszczew in hereditary lease to the burgesses and the other inhabitants, and returns the contract. Other lords, it says, would follow, and the estates of the province's numerous nobility, whose preservation must be considered, would be diminished; the Pszczew forest, the only large one in the area, could not be properly managed; the inhabitants have land enough, the burgesses should rather follow town trades, and most are too poor."),
 25: ("Vertrag, vorbehaltlich der Genehmigung des Fürsten zu Hohenlohe-Ingelfingen: Dessen Bevollmächtigter, der Bau- und Ökonomierat Johann Wilhelm Glenck, verkauft dem Mahlmüller Samuel Lucke von der Mühle Białobrzeg bei Wrąbczynek 1000 Morgen Vorwerksland des Guts Szetlewek mit den Vorwerksgebäuden für 12333 Rthl, davon 8333 Rthl an den Pfandbesitzer von Radzinski bei der Räumung, und einen jährlichen Kanon von 500 Rthl. Schankrecht, Brauhaus und Brennerei erhält Lucke gegen einen jährlichen Zins von 400; die Dienste der Untertanen sind ausgenommen, die Herrschaft hat sich bereit erklärt, sie auf ihren Wunsch davon freizulassen. Lucke handelt für mehrere Kaufinteressenten und erbittet zwei bis vier Wochen.",
      "A contract subject to the approval of the Prince of Hohenlohe-Ingelfingen: his agent, the councillor for building and estate management Johann Wilhelm Glenck, sells to the miller Samuel Lucke of the Białobrzeg mill near Wrąbczynek 1000 Morgen of the home-farm land of the estate of Szetlewek, with the farm buildings, for 12333 Rthl, 8333 Rthl of it to the pledge holder von Radzinski when he leaves, and a yearly rent of 500 Rthl. Lucke receives the drink monopoly, the brewhouse and the distillery for a yearly rent of 400; the services of the subjects are excepted, the manor having declared itself ready to free them from service at their wish. Lucke acts for several would-be buyers and asks for two to four weeks."),
 26: ("Protokoll vor dem Polizeimagistrat zu Zagórów: Der Polizeibürgermeister Nüchler aus Pyzdry, der Müller Luka aus Białobrzeg und Kriede aus Wrąbczynek hatten am 20. November 1798 mit Glenck, dem Generalbevollmächtigten des Fürsten zu Hohenlohe, vereinbart, das Gut Szetlewek aufzuteilen, Ansiedler zu stellen und den Kaufpreis zu Johanni zu zahlen. Weil der Pfandbesitzer von Szetlewek die Räumung erschwert, sagen sie sich vom Vertrag los, wenn ihnen 200 Rthl Reisekosten ersetzt werden und die angeworbenen Leute, die schon Handgeld gezahlt haben, sich an die Herrschaft halten. Glenck will zahlen, wenn der Fürst es genehmigt.",
      "A record made before the police magistrate at Zagórów: the police burgomaster Nüchler of Pyzdry, the miller Luka of Białobrzeg and Kriede of Wrąbczynek had agreed with Glenck, the general agent of the Prince of Hohenlohe, on 20 November 1798 to divide up the estate of Szetlewek, find settlers for it and pay the purchase money at midsummer. Because the pledge holder of Szetlewek is making difficulties about leaving, they renounce the contract, provided they are repaid 200 Rthl in travelling costs and the people they recruited, who have already paid earnest money, look to the manor. Glenck offers to pay if the Prince approves."),
 27: ("Titz und Bancke berichten aus Zagórów einem Bau- und Ökonomierat: Der Müller Luka hat sich von seinem Vertrag losgesagt, die 25 Rthl erhalten und will das Weitere mit dem Rat in Kalisz abmachen. Zwei Leute, die er zur Übernahme von Land mitbrachte, wurden vertröstet, bis man mit Trąbczyn und Herrn von Szucki fertig sei. Sie bitten, Szuckis Abzug der Regierung zu melden, und fragen, ob der Fürst zu den 1000 Rthl, die die Gemeinde für diesen Abzug geben will, etwas beitragen könne, da Szuckis Schikane gegen die Untertanen wachse. Ein Tischler, der in Szetlewek wohnen wollte, hat aus Verzweiflung ein Haus in Zagórów gekauft.",
      "Titz and Bancke report from Zagórów to a councillor for building and estate management: the miller Luka has withdrawn from his contract, has received the 25 Rthl and will settle the rest with the councillor at Kalisz. Two people he brought to take on land have been put off until matters with Trąbczyn and Herr von Szucki are ended. They ask that Szucki's withdrawal be reported to the Government, and whether the Prince could add something to the 1000 Rthl the community will pay for it, since Szucki's spite against the subjects is growing. A joiner who had meant to live at Szetlewek has in despair bought a house at Zagórów."),
 28: ("Glenck schreibt dem Kriminalrat Grimm in Kalisz: Sein Vertrag mit von Radzinski ist nach dem beigelegten Briefwechsel aufgehoben. Die drei Vertragspartner Luck, Kriede und Nüchler wollten nicht zurücktreten, da sie schon 18 Wirte vorgeführt haben, die gegen Pfand fast zwei Drittel der Felder nehmen; Griese bietet eine Kaution von 2000 Rthl. Den Schaden aus dem Abbruch will Glenck Radzinski anrechnen lassen. Im Vertrag der Trąbczyner Hauländer stehe nach Versicherung von Kramplitz, des Kommissars von Prusimskis, der Vorbehalt, dass ihr Privileg nur für die ersten Besitzer, ihre Söhne und Enkel gelte und sie schon jetzt ein neues nachsuchen müssten.",
      "Glenck writes to the criminal councillor Grimm at Kalisz: his contract with von Radzinski is cancelled, as the enclosed letters show. The three contracting parties Luck, Kriede and Nüchler would not withdraw, since they have already brought forward 18 farmers who have enrolled against a deposit and take nearly two thirds of the fields; Griese offers a security of 2000 Rthl. Glenck wants the loss from the breaking off charged to Radzinski. In the contract of the Trąbczyn Olęder settlers, he has been assured by von Kramplitz, von Prusimski's commissary, there stands the reservation that their privilege runs only to the first holders, their sons and grandsons, and that they must already apply for a new one."),
 29: ("Das fürstliche Gerichtsamt zu Pszczew meldet dem Fürsten zu Hohenlohe-Ingelfingen, dass Sigismund von Rzadkowski sein Erbzinsgut in Głażewo an seine Halbschwester Susanna geborene Treben verkauft hat; der Vertrag ist unter Vorbehalt der fürstlichen Rechte genehmigt. Da dem Fürsten das Vorkaufsrecht zusteht, soll er sich binnen einer Frist erklären, ob er es ausüben will; sonst gilt es nach dem Gesetz für diesen Fall als aufgegeben.",
      "The Prince's court office at Pszczew reports to the Prince of Hohenlohe-Ingelfingen that Sigismund von Rzadkowski has sold his hereditary-rent holding at Głażewo to his half-sister Susanna, born Treben; the contract has been approved without prejudice to the Prince's rights. Since the Prince holds the right of pre-emption, he is to declare within a set time whether he will use it; otherwise by law he is taken to have waived it in this case."),
 30: ("Beglaubigte deutsche Übersetzung, mit dem polnischen Text, eines Auszugs aus dem Privilegienbuch des Domkapitels zu Poznań: Bischof Teodor Czartoryski überlässt 1766 den Eheleuten Simeon und Apollonia Rządkowski eine Hufe wüsten Ackers in Głażewo im Pszczewer Schlüssel mit dem auf Kosten des Hofes erbauten Wohnhaus und der Scheune für 30 Dukaten. Sie zahlen jährlich 130 polnische Gulden in zwei Raten, dazu Kopfgeld und Winterquartiergeld, schicken viermal im Jahr Leute zur Arbeit auf das Vorwerk Głażewo und zur Wiese Obsko und dürfen für je zwei Viertel Gerste eine Tonne Bier aus dem Pszczewer Brauhaus nehmen. Der Bischof sichert ihnen den ruhigen Besitz zu.",
      "A certified German translation, with the Polish text, of an extract from the book of privileges of the cathedral chapter of Poznań: in 1766 Bishop Teodor Czartoryski makes over to the married couple Simeon and Apollonia Rządkowski one Hufe of waste land at Głażewo in the Pszczew estates, with the house and barn built at the manor's cost, for 30 ducats. They pay 130 Polish florins a year in two instalments, besides the poll tax and the winter-quarters money, send people four times a year to work on the Głażewo home farm and at the Obsko meadow, and may take a barrel of beer from the Pszczew brewhouse for every two quarters of barley. The Bishop assures them of quiet possession."),
}

S = {n: (de, group_digits(en)) for n, (de, en) in S.items()}

HEAD_DE = (f'# German summaries of {REF}, written again in the working session from a\n'
           '# reading of each document in its German text (intake/summaries_draft.py,\n'
           '# 2026-10-08). Each statement was checked against its document in session\n'
           '# (intake/claim_check.yml). A finding aid, not part of the edition text.\n')


def yaml_line(key, value):
    return yaml.safe_dump({key: value}, allow_unicode=True, width=10**6,
                          default_flow_style=False).rstrip('\n')


def replace_in_site(path, lang_i):
    with open(path, encoding='utf-8') as f:
        lines = f.read().split('\n')
    prefix = SLUG + '-'
    new = {f'{SLUG}-{n:03d}': pair[lang_i] for n, pair in S.items()}
    out, seen = [], set()
    for line in lines:
        key = line.split(':', 1)[0]
        if key.startswith(prefix) and key in new:
            out.append(yaml_line(key, new[key]))
            seen.add(key)
        else:
            out.append(line)
    missing = set(new) - seen
    if missing:
        sys.exit(f'{path}: no line for {sorted(missing)}')
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))


def main():
    with open(os.path.join(UNIT_DIR, 'summaries_de.yml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(HEAD_DE)
        for n, (de, _en) in sorted(S.items()):
            f.write(yaml_line(f'{SLUG}-{n:03d}', de) + '\n')
    replace_in_site(os.path.join(ROOT, 'site', '_data', 'summaries_de.yml'), 0)
    replace_in_site(os.path.join(ROOT, 'site', '_data', 'summaries.yml'), 1)
    cache = os.path.join(ROOT, 'cache')
    if os.path.isdir(cache):
        for sub, i in (('summaries-raw-de', 0), ('summaries-raw', 1)):
            d = os.path.join(cache, sub)
            os.makedirs(d, exist_ok=True)
            for n, pair in S.items():
                pad = f'{SLUG}-{n:03d}'
                with open(os.path.join(d, pad + '.json'), 'w', encoding='utf-8') as f:
                    json.dump({'letter': str(n), 'pad': pad, 'summary': pair[i],
                               'model': STAMP,
                               'usage': {'input': 0, 'output': 0, 'cache_read': 0}},
                              f, ensure_ascii=False, indent=1)
    words = [len(de.split()) for de, _ in S.values()]
    print(len(S), 'summaries written, German and English;',
          f'German words {min(words)}-{max(words)}, mean {sum(words) / len(words):.0f}')


if __name__ == '__main__':
    main()
