# -*- coding: utf-8 -*-
"""The summaries of Oe 1 Bü 14525, written again in the working session.

    python3 units/oe1bu14525/intake/summaries_draft.py

The first summaries of this holding (2026-09) were written by summarise.py from
the English translation, and the German ones beside them were never checked
against the documents. On 2026-10-08 every document was read whole in its
German text (corpus/text/, the corrected corpus) and summarised afresh in
German; the English is a translation of the German. Each statement was then
held to its document in session (claim_check.yml beside this file), as for the
other holdings. Not a paid run: there is no reading.json and no list of
suspected slips from read_letters.py.

The script writes units/<slug>/summaries_de.yml and replaces this holding's
lines, and only these, in site/_data/summaries.yml and summaries_de.yml (never
`summarise.py --build`: WORKING_NOTES, "The English, the summaries and the
claim check"). Where the desktop cache exists it writes the cache files too,
so that a later build there does not bring the old summaries back.
"""
import io
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
UNIT_DIR = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(UNIT_DIR))
SLUG = 'oe1bu14525'
REF = 'Oe 1 Bü 14525'
STAMP = 'in-session, 2026-10-08; claim-checked'
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, ROOT)
from numerals import group_digits  # noqa: E402  the English groups thousands, as english_forms.py does

S = {
 1: ("Beglaubigte Abschrift der Schenkungsurkunde König Friedrich Wilhelms vom 9. August 1796: Für langjährige Dienste erhält Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, Generalleutnant und Gouverneur von Wrocław, die dem König anheimgefallenen Güter Kamionna und Kolno im Posener Kreis, Trąbczyn, Szetlewek, Nowawies, Łazy, Alt- und Neu-Laske, Osiny und das Hauland Trąbczyński im Koniner Kreis sowie Brzyce in Kujawien erblich und zu freier Verfügung, vorbehaltlich der landesherrlichen Steuern. Die Regierung zu Kalisz beglaubigt die Abschrift; der Besitztitel für Szetlewek ist im Koniner Hypothekenbuch eingetragen.",
     "A certified copy of King Friedrich Wilhelm's deed of gift of 9 August 1796: for long service Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, lieutenant general and governor of Wrocław, receives the estates fallen to the King, Kamionna and Kolno in the Poznań district, Trąbczyn, Szetlewek, Nowawies, Łazy, Old and New Laske, Osiny and Hauland Trąbczyński in the Konin district, and Brzyce in Cujavia, heritably and to dispose of freely, saving the sovereign's taxes. The Government at Kalisz certifies the copy; the title to Szetlewek is entered in the Konin mortgage book."),
 2: ("Hypothekenschein der Regierung zu Kalisz für Friedrich Ludwig, regierenden Fürsten von Hohenlohe-Ingelfingen, über das Allodialgut Szetlewek, das ihm die Schenkungsurkunde vom 9. August 1796 verlieh und dessen Wert er mit 24000 Rthl angab. Eingetragen sind das Verbot, das Gut ohne Erlaubnis an Landeseingeborene zu verkaufen; 8333 Rthl 8 ggl (50000 polnische Gulden), die Ignatz von Radzinski dem Besitzer zinslos als Sicherheit für die Pachtgelder von Szetlewek geliehen hat; und eine Protestation Jacob von Przespolewskis wegen 30000 polnischer Gulden aus einer Verschreibung des Vorbesitzers von Prusimski, die zugleich auf Trąbczyn eingetragen ist.",
     "A mortgage certificate of the Government at Kalisz for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, on the allodial estate of Szetlewek, which the deed of gift of 9 August 1796 granted him and which he valued at 24000 Rthl. Entered on it are a ban on selling the estate to natives of the country without consent; 8333 Rthl 8 Groschen (50000 Polish florins), lent to the owner free of interest by Ignatz von Radzinski as security for the rent of Szetlewek; and a protest by Jacob von Przespolewski over 30000 Polish florins under a bond of the former owner, von Prusimski, which is entered on Trąbczyn as well."),
 3: ("Abschrift einer Schenkungsurkunde König Friedrich Wilhelms, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, Generalleutnant und Gouverneur von Wrocław, für langjährige Dienste dem König anheimgefallene Güter erblich und zu freier Verfügung erhält, vorbehaltlich der landesherrlichen Steuern. Der Text der Urkunde nennt Kamionna und Kolno im Posener Kreis und Brzyce in Kujawien; die Aufschrift nennt dazu Trąbczyn, Szetlewek und die übrigen Dörfer im Koniner Kreis. Der Gouvernementsauditeur Richter beglaubigt die Abschrift.",
     "A copy of a deed of gift of King Friedrich Wilhelm by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, lieutenant general and governor of Wrocław, receives for long service estates fallen to the King, heritably and to dispose of freely, saving the sovereign's taxes. The text of the deed names Kamionna and Kolno in the Poznań district and Brzyce in Cujavia; its endorsement names Trąbczyn, Szetlewek and the other villages of the Konin district as well. Richter, judge advocate of the governor's court, certifies the copy."),
 4: ("Abschrift einer Schenkungsurkunde König Friedrich Wilhelms, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, Generalleutnant und Gouverneur von Wrocław, für langjährige Dienste Güter erblich und zu freier Verfügung erhält, vorbehaltlich der landesherrlichen Steuern. Der Text der Urkunde nennt Kamionna und Kolno im Posener Kreis und Brzyce in Kujawien; die Aufschrift nennt dazu Trąbczyn, Szetlewek und die übrigen Dörfer im Koniner Kreis. Sonnabend, Auditeur des Hohenloheschen Infanterieregiments, beglaubigt die Abschrift nach dem Original.",
     "A copy of a deed of gift of King Friedrich Wilhelm by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, lieutenant general and governor of Wrocław, receives estates for long service, heritably and to dispose of freely, saving the sovereign's taxes. The text of the deed names Kamionna and Kolno in the Poznań district and Brzyce in Cujavia; its endorsement names Trąbczyn, Szetlewek and the other villages of the Konin district as well. Sonnabend, judge advocate of the Hohenlohe infantry regiment, certifies the copy against the original."),
 5: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 19. Juni 1797: Weil die Güter des entwichenen Starosten von Prusimski, mit denen der König Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, auszeichnen wollte, mit vielen Schulden belastet waren, erhält der Fürst sechzehn ehemals geistliche Dörfer, darunter Pszczew, Zagórów, Drzewce und Wieniec, erblich und zu freier Verfügung. Er zahlt dafür die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Sonnabend beglaubigt die Abschrift nach einer gerichtlichen Abschrift vom 24. Februar 1798.",
     "A copy of a deed of grant of King Friedrich Wilhelm of 19 June 1797: because the estates of the absconded Starost von Prusimski, with which the King had meant to honour Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, were burdened with many debts, the Prince receives sixteen former church villages, among them Pszczew, Zagórów, Drzewce and Wieniec, heritably and to dispose of freely. In return he pays the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. Sonnabend certifies the copy against a court copy of 24 February 1798."),
 6: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 1. Dezember 1797: Zu den im Juni verliehenen Gütern Pszczew, Zagórów und Wieniec erhält Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, deren Zubehör erblich und zu freier Verfügung: bei Pszczew mehrere Ortschaften und Hauländereien, bei Zagórów das Dörfchen Swięcia, bei Wieniec vier Orte, darunter Konty, Szedlemin und Bątkowo. Er zahlt dafür die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Sonnabend, Auditeur des Hohenloheschen Infanterieregiments, beglaubigt die Abschrift.",
     "A copy of a deed of grant of King Friedrich Wilhelm of 1 December 1797: to the estates of Pszczew, Zagórów and Wieniec granted in June, Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives their appurtenances, heritably and to dispose of freely: several villages and Olęder settlements by Pszczew, the hamlet of Swięcia by Zagórów, and four places by Wieniec, among them Konty, Szedlemin and Bątkowo. In return he pays the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. Sonnabend, judge advocate of the Hohenlohe infantry regiment, certifies the copy."),
 7: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 1. Dezember 1797, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, das Zubehör der ihm im Juni verliehenen Güter Pszczew, Zagórów und Wieniec erhält, darunter das Dörfchen Swięcia bei Zagórów. Die Regierung zu Kalisz hat die Abschrift für die Eintragung des Besitztitels beglaubigt. Beigefügt ist ein Hypothekenschein der Regierung zu Kalisz für das Gut Swięcia mit dem Vorwerk Broniki: Eingetragen ist allein das Verbot, es ohne besondere Erlaubnis an Landeseingeborene zu verkaufen; Schulden stehen keine darauf. Sonnabend beglaubigt beides in Wrocław.",
     "A copy of a deed of grant of King Friedrich Wilhelm of 1 December 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives the appurtenances of the estates of Pszczew, Zagórów and Wieniec granted to him in June, among them the hamlet of Swięcia by Zagórów. The Government at Kalisz has certified the copy for the entry of the title. Attached is a mortgage certificate of the Government at Kalisz for the estate of Swięcia with the farm of Broniki: the only entry is the ban on selling it to natives of the country without special consent; no debts stand on it. Sonnabend certifies both at Wrocław."),
 8: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 19. Juni 1797, mit der Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, sechzehn ehemals geistliche Dörfer erblich erhält, darunter Pszczew, Zagórów, Drzewce und Wieniec, gegen die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Begründet wird dies damit, dass die Güter des entwichenen Starosten von Prusimski, mit denen der König ihn auszeichnen wollte, mit vielen Schulden belastet waren. Der Gouvernementsauditeur Richter beglaubigt die Abschrift nach dem Original.",
     "A copy of a deed of grant of King Friedrich Wilhelm of 19 June 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives sixteen former church villages heritably, among them Pszczew, Zagórów, Drzewce and Wieniec, in return for the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. The reason given is that the estates of the absconded Starost von Prusimski, with which the King had meant to honour him, were burdened with many debts. Richter, judge advocate of the governor's court, certifies the copy against the original."),
 9: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom Juni 1797, mit der Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, sechzehn ehemals geistliche Dörfer erblich erhält, darunter Pszczew, Zagórów, Drzewce und Wieniec, gegen die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Begründet wird dies damit, dass die Güter des entwichenen Starosten von Prusimski, mit denen der König ihn auszeichnen wollte, mit vielen Schulden belastet waren. Sonnabend, Auditeur des Hohenloheschen Infanterieregiments, beglaubigt die Abschrift nach dem Original.",
     "A copy of a deed of grant of King Friedrich Wilhelm of June 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives sixteen former church villages heritably, among them Pszczew, Zagórów, Drzewce and Wieniec, in return for the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. The reason given is that the estates of the absconded Starost von Prusimski, with which the King had meant to honour him, were burdened with many debts. Sonnabend, judge advocate of the Hohenlohe infantry regiment, certifies the copy against the original."),
 10: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 19. Juni 1797, mit der Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, sechzehn ehemals geistliche Dörfer erblich erhält, darunter Pszczew, Zagórów, Drzewce und Wieniec, gegen die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Begründet wird dies damit, dass die Güter des entwichenen Starosten von Prusimski, mit denen der König ihn auszeichnen wollte, mit vielen Schulden belastet waren. Der Gouvernements- und Garnisonauditeur Richter beglaubigt die Abschrift nach dem Original.",
      "A copy of a deed of grant of King Friedrich Wilhelm of 19 June 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives sixteen former church villages heritably, among them Pszczew, Zagórów, Drzewce and Wieniec, in return for the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. The reason given is that the estates of the absconded Starost von Prusimski, with which the King had meant to honour him, were burdened with many debts. Richter, judge advocate of the governor's court and the garrison, certifies the copy against the original."),
 11: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 1. Dezember 1797: Zu den im Juni verliehenen Gütern Pszczew, Zagórów und Wieniec erhält Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, deren Zubehör erblich und zu freier Verfügung: bei Pszczew mehrere Ortschaften und Hauländereien, bei Zagórów das Dörfchen Swięcia, bei Wieniec Konty, Szedlemin, Bątkowo und Karczyn. Er zahlt dafür die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Das Geheime Südpreußische Archiv beglaubigt die Abschrift nach dem Original.",
      "A copy of a deed of grant of King Friedrich Wilhelm of 1 December 1797: to the estates of Pszczew, Zagórów and Wieniec granted in June, Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives their appurtenances, heritably and to dispose of freely: several villages and Olęder settlements by Pszczew, the hamlet of Swięcia by Zagórów, and Konty, Szedlemin, Bątkowo and Karczyn by Wieniec. In return he pays the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. The Secret South Prussian Archive certifies the copy against the original."),
 12: ("Hypothekenschein der Regierung zu Poznań für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, über das Gut Kolno, das aus der Stadt Kamionna und dem Marktflecken Kolno besteht. Es fiel an den Fiskus, als das ganze Vermögen Anton von Prusimskis wegen seiner Teilnahme am Aufstand von 1794 eingezogen wurde, und kam durch die Verleihungsurkunde vom 9. August 1796 an den Fürsten. Eingetragen sind Protestationen Anton von Broniewskis, der das Gut als Pfand zu besitzen behauptet und 79795 Rthl 18 g 8 4/5 pf fordert, beides vom Fürsten bestritten, sowie zwei dauernde Lasten zugunsten der Kirche zu Kamionna. Der Schein ist nur zur Information ausgestellt.",
      "A mortgage certificate of the Government at Poznań for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, on the estate of Kolno, which consists of the town of Kamionna and the market town of Kolno. It fell to the fisc when the whole property of Anton von Prusimski was confiscated for his part in the rising of 1794, and came to the Prince by the deed of grant of 9 August 1796. Entered on it are protests of Anton von Broniewski, who claims to hold the estate in pledge and demands 79795 Rthl 18 Groschen 8 4/5 pfennig, both disputed by the Prince, and two standing charges in favour of the church at Kamionna. The certificate is issued for information only."),
 13: ("Wertanschlag der Güter Kamionna und Kolno im Kreis Międzyrzecz, die dem Fürsten Friedrich Ludwig zu Hohenlohe-Ingelfingen gehören, aufgestellt auf sein Verlangen nach den westpreußischen Grundsätzen von 1794, nach südpreußischen Grundsätzen berichtigt von dem Kalkulator Bading und 1804 in Berlin beglaubigt. Beschrieben werden Lage, Grenzen und Fläche (10642 Morgen), die Stadt Kamionna mit 75 Feuerstellen und 466 Einwohnern, das Schankrecht der Herrschaft, die beiden Vorwerke und das Dorf Kolno mit seinen Bauern. Das freie Bau- und Brennholz aus der Krobilewer Heide wird der Stadt und der Herrschaft derzeit streitig gemacht. Der Text bricht vor der Berechnung des Werts ab.",
      "A valuation of the estates of Kamionna and Kolno in the Międzyrzecz district, which belong to Prince Friedrich Ludwig of Hohenlohe-Ingelfingen, drawn up at his request on the West Prussian principles of 1794, corrected to the South Prussian principles by the calculator Bading and certified at Berlin in 1804. It describes their position, bounds and area (10642 Morgen), the town of Kamionna with 75 hearths and 466 inhabitants, the lordship's right to sell drink, the two home farms and the village of Kolno with its peasants. The free building timber and firewood from the Krobilewer heath is at present disputed to the town and the lordship. The text breaks off before the reckoning of the value."),
 14: ("Schluss eines Wertanschlags der Güter Kamionna und Kolno: Zwei Notare in Kalisz bescheinigen, dass die Taxe in allen Stücken als richtig anerkannt wurde. Der Forstinspektor Rochlitz rechnet vor, wie der Wert der Güter steigen würde, wenn 344 Morgen Wald abgetrennt und mit 22 Familien zu je einer halben Hufe besetzt und das Land verkauft würde, das die Bürger von Kamionna (700 Morgen) und die Untertanen von Kolno (1200 Morgen) über ihre Verschreibungen hinaus besitzen. Nach seiner Rechnung stiege der Wert von 186943 Rthl, berechnet nach westpreußischen Grundsätzen, auf 255833 Rthl 12 g.",
      "The end of a valuation of the estates of Kamionna and Kolno: two notaries at Kalisz certify that the valuation was acknowledged as correct in every part. The forest inspector Rochlitz reckons how the value of the estates would rise if 344 Morgen of forest were separated off and settled with 22 families of half a Hufe each, and the land sold that the burgesses of Kamionna (700 Morgen) and the subjects of Kolno (1200 Morgen) hold beyond their deeds. By his reckoning the value would rise from 186943 Rthl, calculated on West Prussian principles, to 255833 Rthl 12 Groschen."),
 15: ("Hypothekenschein der Regierung zu Poznań für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, über die Herrschaft Pszczew mit ihren Dörfern, Hauländereien und der Heidemühle. Die Güter gehörten dem Domkapitel zu Poznań und kamen nach der Einziehung der geistlichen Güter durch die Verleihungsurkunden vom 19. Juni und 1. Dezember 1797 an den Fürsten. Eingetragen sind die jährliche Kompetenz der früheren geistlichen Besitzer, an die Kriegs- und Domänenkasse zu Poznań zu zahlen und noch nicht beziffert, und das Verbot, die Güter ohne königliche Erlaubnis an Eingeborene des früheren Polen zu verkaufen. Schulden sind keine eingetragen.",
      "A mortgage certificate of the Government at Poznań for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, on the lordship of Pszczew with its villages, Olęder settlements and the heath mill. The estates belonged to the cathedral chapter of Poznań and came to the Prince, after the church estates were taken over by the state, by the deeds of grant of 19 June and 1 December 1797. Entered on it are the yearly allowance due to the former church owners, payable to the treasury of the War and Domains Chamber at Poznań and not yet fixed in amount, and the ban on selling the estates to natives of former Poland without royal consent. No debts are entered."),
 16: ("Resignationsbrief, das heißt Urkunde über die förmliche Abtretung, ausgestellt unter dem Siegel der Regierung zu Poznań: Am 22. März 1802 hat der Kammerfiskal Beyer im Namen des Fiskus die Herrschaft Pszczew mit ihren Dörfern und Hauländereien aufgrund der Verleihungsurkunden von 1797 an Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, abgetreten; der Kreisjustizrat Melzer hat sie als Bevollmächtigter des Fürsten angenommen. Die Übertragung wird bestätigt, mit dem Recht, die Herrschaft zu verkaufen, zu verschenken, zu tauschen und zu verpfänden. Ein Vermerk bestätigt die Eintragung des Besitztitels im Hypothekenbuch.",
      "A brief of resignation, that is, a deed recording a formal surrender, issued under the seal of the Government at Poznań: on 22 March 1802 the chamber's fiscal officer Beyer, on behalf of the fisc, surrendered the lordship of Pszczew with its villages and Olęder settlements to Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, on the strength of the deeds of grant of 1797; the district justice councillor Melzer accepted it as the Prince's agent. The transfer is confirmed, with the right to sell, give away, exchange and pledge the lordship. A note confirms the entry of the title in the mortgage book."),
 17: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 19. Juni 1797, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, sechzehn ehemals geistliche Dörfer erblich erhält, darunter Pszczew, Zagórów, Drzewce und Wieniec, gegen die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz. Begründet wird dies damit, dass die Güter des entwichenen Starosten von Prusimski, mit denen der König ihn auszeichnen wollte, mit vielen Schulden belastet waren. Die Regierung zu Poznań beglaubigt die Abschrift für die Eintragung des Besitztitels der Herrschaft Pszczew; ein Vermerk bestätigt die Eintragung.",
      "A copy of a deed of grant of King Friedrich Wilhelm of 19 June 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives sixteen former church villages heritably, among them Pszczew, Zagórów, Drzewce and Wieniec, in return for the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies. The reason given is that the estates of the absconded Starost von Prusimski, with which the King had meant to honour him, were burdened with many debts. The Government at Poznań certifies the copy for the entry of the title to the lordship of Pszczew; a note confirms the entry."),
 18: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 1. Dezember 1797, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, das Zubehör der ihm im Juni verliehenen Güter Pszczew, Zagórów und Wieniec erhält. Die Regierung zu Poznań hat die Abschrift für die Eintragung des Besitztitels der Herrschaft Pszczew beglaubigt; ein Vermerk bestätigt die Eintragung. Der Gouvernementsauditeur Richter bescheinigt außerdem, dass die Abschriften des Hypothekenscheins und des Resignationsbriefs für Pszczew mit den ihm vorgelegten Originalen übereinstimmen.",
      "A copy of a deed of grant of King Friedrich Wilhelm of 1 December 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives the appurtenances of the estates of Pszczew, Zagórów and Wieniec granted to him in June. The Government at Poznań has certified the copy for the entry of the title to the lordship of Pszczew; a note confirms the entry. Richter, judge advocate of the governor's court, also certifies that the copies of the mortgage certificate and of the brief of resignation for Pszczew agree with the originals shown to him."),
 19: ("Die Regierung zu Kalisz fordert den regierenden Fürsten zu Hohenlohe-Ingelfingen in Wrocław auf, binnen vier Wochen sein Eigentum an den ehemals geistlichen Gütern Kopojno, Drzewce, Swięcia und Zagórów im Koniner Kreis nachzuweisen und einen Termin zur Eintragung seines Besitztitels zu beantragen. Nach der Kriegs- und Domänenkammer sind ihm die Güter verliehen und bereits übergeben.",
      "The Government at Kalisz calls on the reigning Prince of Hohenlohe-Ingelfingen at Wrocław to prove within four weeks his ownership of the former church estates of Kopojno, Drzewce, Swięcia and Zagórów in the Konin district, and to apply for a hearing to enter his title. According to the War and Domains Chamber the estates have been granted to him and already handed over."),
 20: ("Die Regierung zu Kalisz bewilligt Glenck, dem Bau- und Ökonomierat des Fürsten zu Hohenlohe-Ingelfingen in Wrocław, auf sein Gesuch vom 8. des Monats eine letzte Frist bis Ende Oktober, um den Besitztitel des Fürsten für Drzewce, Kopojno, Swięcia und Zagórów eintragen zu lassen.",
      "The Government at Kalisz grants Glenck, the Prince of Hohenlohe-Ingelfingen's councillor for building and estate management at Wrocław, at his request of the 8th of the month, a final extension to the end of October to have the Prince's title to Drzewce, Kopojno, Swięcia and Zagórów entered."),
 21: ("Amtlicher Auszug aus dem Hypothekenbuch für die Stadt Zagórów, die Friedrich Ludwig, regierender Fürst zu Hohenlohe-Ingelfingen, durch die Verleihungsurkunde vom 19. Juni 1797 erhielt; der Hypothekenbewahrer des Departements Kalisz bestätigt 1811 auf Polnisch, dass sich der Stand nicht geändert hat. Eingetragen sind eine jährliche Kompetenz von 88 Rthl 5 g 9 d, Protestationen des Fiskus und der Erbpächter von Oleśnica wegen Rechten am Holz der Zagórówer Forsten, eine Anleihe des Eigentümers über 250000 Rthl zugunsten des Kriegs- und Forstrats Peter Friedrich August von Triebenfeld, der Teile davon der Generalinvalidenkasse verpfändet und an Bankiers in Berlin und Königsberg abgetreten hat, und eine Protestation über 8000 Rthl für die Erben des Grafen Seher-Thoss.",
      "An official extract from the mortgage book for the town of Zagórów, which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, received by the deed of grant of 19 June 1797; the keeper of mortgages of the department of Kalisz confirms in 1811, in Polish, that the entries have not changed. Entered are a yearly church allowance of 88 Rthl 5 Groschen 9 pfennig, protests of the fisc and of the hereditary leaseholders of Oleśnica over rights to wood in the Zagórów forests, a loan of 250000 Rthl secured by the owner in favour of the councillor of war and forests Peter Friedrich August von Triebenfeld, who has pledged parts of it to the General Invalids' Fund and assigned parts to bankers in Berlin and Königsberg, and a protest over 8000 Rthl for the heirs of Count Seher-Thoss."),
 22: ("Abschrift einer Verleihungsurkunde König Friedrich Wilhelms vom 19. Juni 1797, mit der Friedrich Ludwig, regierender Fürst von Hohenlohe-Ingelfingen, sechzehn ehemals geistliche Dörfer erblich erhält, darunter Pszczew, Zagórów, Drzewce und Wieniec, gegen die bisherigen landesherrlichen Abgaben als festen Kanon und die den geistlichen Körperschaften zustehende Kompetenz; die Regierung zu Kalisz hat sie für die Eintragung des Besitztitels beglaubigt. Beigefügt ist ein Hypothekenschein der Regierung zu Kalisz für die Stadt Zagórów: Eingetragen ist allein das Verbot, sie ohne besondere Erlaubnis an Landeseingeborene zu verkaufen; Schulden stehen keine darauf. Schenck, Justizbürgermeister, beglaubigt beide Abschriften in Trąbczyn.",
      "A copy of a deed of grant of King Friedrich Wilhelm of 19 June 1797 by which Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, receives sixteen former church villages heritably, among them Pszczew, Zagórów, Drzewce and Wieniec, in return for the sovereign's dues paid from them so far, as a fixed rent, and the allowance due from them to the church bodies; the Government at Kalisz has certified it for the entry of the title. Attached is a mortgage certificate of the Government at Kalisz for the town of Zagórów: the only entry is the ban on selling it to natives of the country without special consent; no debts stand on it. Schenck, the burgomaster for justice, certifies both copies at Trąbczyn."),
 23: ("Gerichtlicher Wertanschlag des Guts Szetlewek im Koniner Kreis, den die Regierung zu Kalisz für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, ausfertigen ließ. Das Gut misst 1724 Morgen; darauf sitzen drei Ganzhüfner, fünf Halbhüfner und neun Einlieger, mit einem Krug, einer Schmiede und einer Wassermühle. Die Untertanen erhielten Brennholz aus dem Wald von Trąbczyn, da beide Güter stets einen Herrn hatten. Szetlewek ist von 1799 bis 1805 für jährlich 7800 Gulden an Ignatz von Radzinski verpachtet. Nach Abzug des Inventars, das dem Pächter gehört, wird der Wert auf 31171 Rthl 23 gg 4 d festgesetzt.",
      "A court valuation of the estate of Szetlewek in the Konin district, issued by the Government at Kalisz for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen. The estate measures 1724 Morgen; on it live three full-holding peasants, five half-holders and nine lodgers, with an inn, a smithy and a water mill. The subjects have had their firewood from the Trąbczyn wood, since the two estates always had one lord. Szetlewek is leased from 1799 to 1805 to Ignatz von Radzinski for 7800 florins a year. Less the stock, which belongs to the lessee, the value is set at 31171 Rthl 23 Groschen 4 pfennig."),
 24: ("Ein kurzer Vermerk, großenteils nicht gelesen. Erkennbar sind der Name Melzer, das Datum 18. April 1803 und ein Erbpachtkontrakt über Bątkowo.",
      "A short note, for the most part not read. What can be made out is the name Melzer, the date 18 April 1803 and a hereditary-lease contract for Bątkowo."),
 25: ("Notariell beglaubigte Abschrift eines Hypothekenscheins der Regierung zu Poznań über die Herrschaft Pszczew, ausgestellt für Johann Wilhelm Glenck, Bau- und Ökonomierat im Dienst des Fürsten zu Hohenlohe-Ingelfingen, wegen seiner Forderung von 5000 Rthl. Eingetragen sind die jährliche Kompetenz der früheren geistlichen Besitzer, nun auf 2470 Rthl 16 gg 3 pf festgesetzt, und Schulden des Fürsten: 48000 Rthl an Glenck, 2000 Rthl an den Breslauer Handelsmann Abraham Moses Hirschel und je 5000 Rthl an den Freiherrn von der Marwitz auf Rudnik, an die Witwe Christiane Dorothea Michaelis und nochmals an Glenck.",
      "A notarially certified copy of a mortgage certificate of the Government at Poznań on the lordship of Pszczew, issued to Johann Wilhelm Glenck, councillor for building and estate management in the service of the Prince of Hohenlohe-Ingelfingen, for his claim of 5000 Rthl. Entered on the lordship are the yearly allowance due to the former church owners, now fixed at 2470 Rthl 16 Groschen 3 pfennig, and the Prince's debts: 48000 Rthl to Glenck, 2000 Rthl to the Wrocław merchant Abraham Moses Hirschel, and 5000 Rthl each to Freiherr von der Marwitz of Rudnik, to the widow Christiane Dorothea Michaelis and again to Glenck."),
 26: ("Die Regierung zu Poznań teilt dem Fürsten zu Hohenlohe-Ingelfingen mit, dass auf sein Gesuch hin je 5000 Rthl für den Baron von der Marwitz, die Oberamtsrätin Michaelis und den Ökonomierat Glenck auf die Herrschaft Pszczew eingetragen und für jeden der drei Gläubiger ein Hypothekenschein verfügt worden ist. Die Scheine kann er nach vier Wochen gegen die Kosten im Archiv der Regierung abholen lassen.",
      "The Government at Poznań informs the Prince of Hohenlohe-Ingelfingen that, at his request, 5000 Rthl each for Baron von der Marwitz, for Mrs Michaelis, wife or widow of a senior councillor, and for the estate councillor Glenck have been entered on the lordship of Pszczew, and a mortgage certificate ordered for each of the three creditors. He may have the certificates collected from the Government's archive after four weeks, on payment of the costs."),
 27: ("Bescheinigung der Regierung zu Poznań für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, aus den Hypothekenakten der Güter von Pszczew im Kreis Międzyrzecz: Die Güter sind ihm durch die Schenkungsurkunde vom Juni 1797 und deren Erklärung vom 1. Dezember 1797 verliehen; die Eintragung seines Besitztitels wartet nur noch auf die Abtretung durch den Fiskus. Die Güter gehörten früher dem Bistum Poznań, und der Fürst hat darauf bisher keine Schulden aufgenommen und keine Schuldurkunden zur Eintragung eingereicht.",
      "A certificate of the Government at Poznań for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, from the mortgage files of the estates of Pszczew in the Międzyrzecz district: the estates have been granted to him by the deed of gift of June 1797 and its declaration of 1 December 1797; the entry of his title waits only on the formal surrender by the fisc. The estates formerly belonged to the bishopric of Poznań, and the Prince has so far raised no debts on them and submitted no bonds for entry."),
 28: ("Hypothekenschein der Regierung zu Poznań für Friedrich Ludwig, regierenden Fürsten zu Hohenlohe-Ingelfingen, über das Gut Bątkowo im Kreis Radziejów mit dem Gut Szedlemin im Kreis Brześć. Beide gehörten dem Domkapitel zu Włocławek und kamen nach der Einziehung der geistlichen Güter durch die Verleihungsurkunde vom 1. Dezember 1797 an den Fürsten. Eingetragen sind die jährliche Kompetenz des Domkapitels, noch nicht beziffert, und das Verbot, die Güter ohne königliche Erlaubnis an Eingeborene des früheren Polen zu verkaufen; Schulden sind keine eingetragen.",
      "A mortgage certificate of the Government at Poznań for Friedrich Ludwig, reigning Prince of Hohenlohe-Ingelfingen, on the estate of Bątkowo in the Radziejów district with the estate of Szedlemin in the Brześć district. Both belonged to the cathedral chapter of Włocławek and came to the Prince, after the church estates were taken over by the state, by the deed of grant of 1 December 1797. Entered on them are the yearly allowance due to the chapter, not yet fixed in amount, and the ban on selling the estates to natives of former Poland without royal consent; no debts are entered."),
 29: ("Abschrift eines Schreibens Johann Wilhelm Glencks, des Bau- und Ökonomierats des Fürsten zu Hohenlohe, an den König: Dem königlichen Befehl gemäß, den Besitztitel der fürstlichen Güter Kopojno, Zagórów, Drzewce und anderer zu berichtigen, habe er alles getan, um die Urkunden beizubringen. Er hofft, das bisherige Hindernis sei behoben und der Befehl könne binnen vier Wochen ausgeführt werden, und bittet, alle strengen Verfügungen aufzuschieben. Der Befehl, auf den er antwortet, ist auf den 18. November datiert, sein Schreiben auf den 3. November.",
      "A copy of a letter of Johann Wilhelm Glenck, the Prince of Hohenlohe's councillor for building and estate management, to the King: in obedience to the King's order to put in order the title to the Prince's estates of Kopojno, Zagórów, Drzewce and others, he has done everything needed to supply the documents. He hopes that the obstacle so far is removed and the order can be carried out within four weeks, and asks that all severe measures be held off. The order he answers is dated 18 November, his letter 3 November."),
 30: ("Die Regierung zu Kalisz setzt Glenck, dem Bau- und Ökonomierat des Fürsten zu Hohenlohe-Ingelfingen in Wrocław, in der Hypothekensache des Guts Swięcia eine Frist von 14 Tagen für das Hypothekenwesen dieses Guts und der dazugehörigen Güter Kopojno, Drzewce und Zagórów, mit der Ankündigung, dass dann unausbleiblich der Fiskus gegen den Fürsten tätig werden müsse.",
      "The Government at Kalisz, in the mortgage business of the estate of Swięcia, sets Glenck, the Prince of Hohenlohe-Ingelfingen's councillor for building and estate management at Wrocław, a term of 14 days for the mortgage records of that estate and of the estates belonging with it, Kopojno, Drzewce and Zagórów, with the warning that the fisc would then without fail have to be set in motion against the Prince."),
 31: ("Die Regierung zu Kalisz teilt dem Fürsten von Hohenlohe-Ingelfingen mit: Da er das Gut Trąbczyn mit Zubehör vom Fiskus erworben hat, muss zuerst sein Besitztitel im Hypothekenbuch eingetragen werden. Dazu soll er binnen vier Wochen eine beglaubigte Abschrift des Urteils einreichen, mit dem das ganze Vermögen Anton von Prusimskis dem Fiskus zugesprochen wurde, und eine Bescheinigung des zuständigen Gerichts, dass das Urteil rechtskräftig ist.",
      "The Government at Kalisz informs the Prince of Hohenlohe-Ingelfingen that, since he has acquired the estate of Trąbczyn with its appurtenances from the fisc, his title must first be entered in the mortgage book. For this he is to submit within four weeks a certified copy of the judgment by which the whole property of Anton von Prusimski was awarded to the fisc, and a certificate of the competent court that the judgment is final."),
 32: ("Ein Schreiben aus Kalisz, unterzeichnet Schultz, ersucht die Oberamtsregierung zu Wrocław, dem regierenden Fürsten Friedrich Ludwig von Hohenlohe-Ingelfingen, wie am 24. September des Vorjahres erbeten, baldigst den Huldigungseid abzunehmen und das Protokoll darüber zu übersenden.",
      "A letter from Kalisz, signed Schultz, asks the Oberamtsregierung, the provincial high court at Wrocław, to take the oath of homage from the reigning Prince Friedrich Ludwig of Hohenlohe-Ingelfingen as soon as possible, as requested on 24 September of the year before, and to send the record of it."),
 33: ("Entwurf Glencks, im Namen des Fürsten zu Hohenlohe, in zwei Fassungen, die eine an die Kammer zu Poznań, die andere an die Regierung gerichtet: Die Regierung zu Poznań habe die Berichtigung des Besitztitels der fürstlichen Güter binnen 14 Tagen gefordert und sonst mit dem Fiskus gedroht; der Fürst habe darauf die fehlenden Schenkungsurkunden im Original eingeschickt. Nun bittet Glenck um die schleunige Abtretung aller fürstlichen Güter in Kujawien und bei Pszczew durch den Fiskus.",
      "Glenck's draft, written in the name of the Prince of Hohenlohe, in two versions, one addressed to the Chamber at Poznań, the other to the Government: the Government at Poznań, he says, demanded that the title to the Prince's estates be put in order within 14 days, or the fisc would act; the Prince then sent in the missing deeds of gift in the original. Glenck now asks for the speedy formal surrender by the fisc of all the Prince's estates in Cujavia and at Pszczew."),
 34: ("Die Regierung zu Poznań antwortet Glenck, dem Bau- und Ökonomierat des Fürsten zu Hohenlohe in Wrocław, auf seine Vorstellung vom 13. des Monats: Der Fiskus hat die Güter Kolno und Kamionna bereits abgetreten; für die Güter von Pszczew ist der Termin auf den 22. März angesetzt. Für die Güter in Kujawien ist die Abtretung noch gar nicht beantragt worden; die Regierung erwartet, dass ein zugelassener Justizkommissar die Berichtigung des Besitztitels betreibt.",
      "The Government at Poznań answers Glenck, the Prince of Hohenlohe's councillor for building and estate management at Wrocław, on his representation of the 13th of the month: the fisc has already surrendered the estates of Kolno and Kamionna; for the estates of Pszczew the hearing is set for 22 March. For the estates in Cujavia the surrender has not yet been applied for at all; the Government expects a qualified justice commissary to see to the entry of the title."),
 35: ("Die Kriegs- und Domänenkammer zu Poznań teilt Glenck, dem Bau- und Ökonomierat des Fürsten von Hohenlohe-Ingelfingen in Wrocław, auf seinen Antrag vom 13. des Monats mit, dass der Kammerfiskal Beyer die nötigen Aufträge erhalten hat, um für den Fiskus alle Güter des Fürsten bei Pszczew und in Kujawien abzutreten.",
      "The War and Domains Chamber at Poznań informs Glenck, the Prince of Hohenlohe-Ingelfingen's councillor for building and estate management at Wrocław, on his application of the 13th of the month, that the chamber's fiscal officer Beyer has received the orders needed to surrender, on behalf of the fisc, all the Prince's estates at Pszczew and in Cujavia."),
 36: ("Johann Wilhelm Glenck, Bau- und Ökonomierat des Fürsten zu Hohenlohe, schreibt dem König: Die Regierung zu Poznań habe die Berichtigung des Besitztitels der fürstlichen Güter als nötig und eilig gefordert, und der Fürst habe die fehlenden Schenkungsurkunden im Original eingeschickt. Im Namen des Fürsten bittet er inständig um die schleunigste Abtretung aller fürstlichen Güter in Kujawien und bei Pszczew durch den Fiskus.",
      "Johann Wilhelm Glenck, the Prince of Hohenlohe's councillor for building and estate management, writes to the King: the Government at Poznań, he says, demanded as necessary and urgent that the title to the Prince's estates be put in order, and the Prince sent in the missing deeds of gift in the original. In the Prince's name he asks urgently for the speediest formal surrender by the fisc of all the Prince's estates in Cujavia and at Pszczew."),
 37: ("Die Regierung zu Poznań mahnt Glenck, den Bau- und Ökonomierat des Fürsten zu Hohenlohe-Ingelfingen, binnen einer letzten Frist von 14 Tagen die Verfügung vom 30. Oktober des Vorjahres über die Berichtigung des Besitztitels der Herrschaft Pszczew für den Fürsten zu erfüllen.",
      "The Government at Poznań orders Glenck, the Prince of Hohenlohe-Ingelfingen's councillor for building and estate management, to comply within a final 14 days with the order of 30 October of the year before on putting in order the Prince's title to the lordship of Pszczew."),
 38: ("Melzer schreibt einem Bau- und Ökonomierat: Im heutigen Termin zur Abtretung der Güter von Pszczew ist der Kammerfiskal wieder nicht erschienen, weil ihn die Kammer noch nicht ermächtigt hat. Melzer hat um einen neuen Termin gebeten, sieht aber kein Ende, solange die Kammer dem Fiskal keine klare Anweisung gibt, und rät, der Fürst möge den Kammerpräsidenten von Harlem um Beschleunigung bitten. In einer Nachschrift meldet er, dass das Urteil zweiter Instanz in einer Sache mit dem Domkapitel abändernd ausgefallen und das Domkapitel abgewiesen worden ist.",
      "Melzer writes to a councillor for building and estate management: at today's hearing for the formal surrender of the estates of Pszczew the chamber's fiscal officer again failed to appear, because the Chamber has not yet authorised him. Melzer has asked for a new hearing, but sees no end to it unless the Chamber gives the fiscal officer clear instructions, and advises that the Prince ask the Chamber's president, von Harlem, to hasten matters. In a postscript he reports that the judgment on appeal in a case with the cathedral chapter has reversed the first and dismissed the chapter."),
 39: ("Abschrift eines Schreibens Hoyms an den Fürsten zu Hohenlohe-Ingelfingen: Der König hat ihm durch Kabinettsordre vom 23. des Monats Kamionna und Kolno, Trąbczyn und die übrigen Dörfer im Koniner Kreis sowie Brzyce in Kujawien erblich geschenkt; Hoym betreibt die Ausfertigung der Schenkungsurkunde. Da die Güter dem Hauptaufständischen von Prusimski gehörten, erkundigt er sich bei der Regierung zu Poznań nach den Schulden darauf. Die Güter sollen jährlich mindestens 4000 Taler tragen; zur Veranschlagung empfiehlt er den Kammerrat Peucker in Fraustadt, der sie auch verkaufen könnte, falls der Fürst sie nicht behalten will. Oberst von Sanitz hat Prusimskis Güter im Kreis Wągrowiec erhalten.",
      "A copy of a letter of Hoym to the Prince of Hohenlohe-Ingelfingen: by a cabinet order of the 23rd of the month the King has given him Kamionna and Kolno, Trąbczyn and the other villages of the Konin district and Brzyce in Cujavia, heritably; Hoym is seeing to the issue of the deed of gift. Since the estates belonged to the chief insurgent von Prusimski, he is asking the Government at Poznań about the debts on them. The estates are said to yield at least 4000 thalers a year; to value them he recommends the chamber councillor Peucker at Fraustadt, who could also sell them should the Prince not wish to keep them. Colonel von Sanitz has received Prusimski's estates in the Wągrowiec district."),
 40: ("Abschrift eines königlichen Reskripts, unterzeichnet von Hoym, an die Kammern zu Poznań und Petrikau: Die Übergabe der dem Fürsten zu Hohenlohe verliehenen konfiszierten und geistlichen Güter sei nur ein oberflächliches Zeremoniell gewesen; Leute mit ungeprüften, zum Teil angeblich falschen Pfand- und Pachtverträgen säßen auf den Gütern. Die Kammern sollen die Ansprüche rasch prüfen, die Güter den Bevollmächtigten des Fürsten zur freien Bewirtschaftung übergeben, Streit möglichst gütlich beilegen und nötige Prozesse auf kürzestem Weg führen lassen. Auch sollen sie die Abgaben und Kompetenzgelder, die der Fürst zu zahlen hat, schleunigst festsetzen.",
      "A copy of a royal rescript, signed by Hoym, to the Chambers at Poznań and Petrikau: the handing over of the confiscated and church estates granted to the Prince of Hohenlohe was, it says, a mere superficial ceremony; people with unexamined, in part allegedly false, pledge and lease contracts are said to sit on the estates. The Chambers are to examine the claims quickly, hand the estates over to the Prince's agents to manage freely, settle disputes amicably as far as possible and have any necessary lawsuits conducted by the shortest way. They are also to fix at once the dues and church allowances the Prince has to pay."),
 41: ("Beglaubigte Abschrift eines Schreibens Hoyms an den Fürsten zu Hohenlohe-Ingelfingen vom 3. Oktober 1797: Die Unruhe des Fürsten wegen der Übergabe seiner südpreußischen Güter beruhe auf einem Missverständnis; Hoym legt seine Verfügungen an die Kammern zu Poznań und Petrikau bei, die Güter baldigst zu übernehmen und zu übergeben. Die geistlichen Besitzer säßen seit dem 1. Juni 1796 auf Rechnung des Fiskus und müssten räumen, sobald sie ihre Kompetenz erhielten; der Bischof von Kujawien sei nur noch in Wieniec und Wolica, weil der Fürst ihn dort lassen wolle. Einen Pächter, der nicht gütlich weiche, möge der Fürst lieber bis Juni 1798 gegen das Pachtgeld lassen, sonst müsse die königliche Kasse ihn entschädigen.",
      "A certified copy of a letter of Hoym to the Prince of Hohenlohe-Ingelfingen of 3 October 1797: the Prince's unease about the handing over of his South Prussian estates rests, he says, on a misunderstanding; Hoym encloses his orders to the Chambers at Poznań and Petrikau to take over and hand over the estates as soon as possible. The church owners, he writes, have sat on them for the fisc's account since 1 June 1796 and must leave as soon as they receive their allowance; the Bishop of Cujavia is still at Wieniec and Wolica only because the Prince is willing to leave him there. A lessee who will not leave amicably the Prince had better leave in his lease until June 1798, taking the rent, or the royal treasury would have to compensate him."),
 42: ("Die Regierung zu Kalisz fordert den Fürsten von Hohenlohe-Ingelfingen auf, zur vollständigen Berichtigung seines Besitztitels für das Gut Szetlewek binnen vier Wochen eine beglaubigte Abschrift des Konfiskationsurteils gegen Anton von Prusimski samt einer Bescheinigung seiner Rechtskraft einzureichen.",
      "The Government at Kalisz calls on the Prince of Hohenlohe-Ingelfingen, so that his title to the estate of Szetlewek can be entered in full, to submit within four weeks a certified copy of the judgment confiscating the property of Anton von Prusimski, with a certificate that it is final."),
 43: ("Abschrift eines Bescheids der Regierung zu Poznań an den Fürsten von Hohenlohe-Ingelfingen auf sein Gesuch vom 31. Januar, in dem er für die Berichtigung seines Besitztitels an den Gütern von Trąbczyn eine beglaubigte Abschrift des Konfiskationsurteils gegen von Prusimski mit Rechtskraftbescheinigung erbeten hatte: Das Urteil sei nicht in Poznań, sondern von der Regierung zu Toruń gefällt worden, und er müsse sich dorthin wenden. Seine Anlage erhält er im Original zurück.",
      "A copy of a ruling of the Government at Poznań to the Prince of Hohenlohe-Ingelfingen on his request of 31 January, in which he had asked, for the entry of his title to the Trąbczyn estates, for a certified copy of the judgment confiscating von Prusimski's property, with a certificate that it is final: the judgment, it says, was given not at Poznań but by the Government at Toruń, and he must apply there. His enclosure is returned to him in the original."),
 44: ("Bescheid der Regierung zu Poznań an den Fürsten von Hohenlohe-Ingelfingen auf sein Gesuch vom 31. Januar, in dem er für die Berichtigung seines Besitztitels an den Gütern von Trąbczyn eine beglaubigte Abschrift des Konfiskationsurteils gegen von Prusimski mit Rechtskraftbescheinigung erbeten hatte: Das Urteil sei nicht in Poznań, sondern von der Regierung zu Toruń gefällt worden, und er müsse sich dorthin wenden. Seine Anlage erhält er im Original zurück.",
      "A ruling of the Government at Poznań to the Prince of Hohenlohe-Ingelfingen on his request of 31 January, in which he had asked, for the entry of his title to the Trąbczyn estates, for a certified copy of the judgment confiscating von Prusimski's property, with a certificate that it is final: the judgment, it says, was given not at Poznań but by the Government at Toruń, and he must apply there. His enclosure is returned to him in the original."),
}

S = {n: (de, group_digits(en)) for n, (de, en) in S.items()}

HEAD_DE = (f'# German summaries of {REF}, written again in the working session from a\n'
           '# reading of each document in its German text (intake/summaries_draft.py,\n'
           '# 2026-10-08). Each statement was checked against its document in session\n'
           '# (intake/claim_check.yml). A finding aid, not part of the edition text.\n')


def yaml_line(key, value):
    return yaml.safe_dump({key: value}, allow_unicode=True, width=10**6,
                          default_flow_style=False).rstrip('\n')


def replace_in_site(path, lang_i):
    with open(path, encoding='utf-8') as f:
        lines = f.read().split('\n')
    prefix = SLUG + '-'
    new = {f'{SLUG}-{n:03d}': pair[lang_i] for n, pair in S.items()}
    out, seen = [], set()
    for line in lines:
        key = line.split(':', 1)[0]
        if key.startswith(prefix) and key in new:
            out.append(yaml_line(key, new[key]))
            seen.add(key)
        else:
            out.append(line)
    missing = set(new) - seen
    if missing:
        sys.exit(f'{path}: no line for {sorted(missing)}')
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))


def main():
    with open(os.path.join(UNIT_DIR, 'summaries_de.yml'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(HEAD_DE)
        for n, (de, _en) in sorted(S.items()):
            f.write(yaml_line(f'{SLUG}-{n:03d}', de) + '\n')
    replace_in_site(os.path.join(ROOT, 'site', '_data', 'summaries_de.yml'), 0)
    replace_in_site(os.path.join(ROOT, 'site', '_data', 'summaries.yml'), 1)
    cache = os.path.join(ROOT, 'cache')
    if os.path.isdir(cache):
        for sub, i in (('summaries-raw-de', 0), ('summaries-raw', 1)):
            d = os.path.join(cache, sub)
            os.makedirs(d, exist_ok=True)
            for n, pair in S.items():
                pad = f'{SLUG}-{n:03d}'
                with open(os.path.join(d, pad + '.json'), 'w', encoding='utf-8') as f:
                    json.dump({'letter': str(n), 'pad': pad, 'summary': pair[i],
                               'model': STAMP,
                               'usage': {'input': 0, 'output': 0, 'cache_read': 0}},
                              f, ensure_ascii=False, indent=1)
    words = [len(de.split()) for de, _ in S.values()]
    print(len(S), 'summaries written, German and English;',
          f'German words {min(words)}-{max(words)}, mean {sum(words) / len(words):.0f}')


if __name__ == '__main__':
    main()
